CATEGORIES = {
    'type_of_synthesis_categories': {
        'solvent-assisted grinding': 'liquid-assisted grinding',
        'solvent-drop grinding': 'liquid-assisted grinding',
        'slurry grinding': 'liquid-assisted grinding',
        'slurry conversion': 'solvent evaporation'},
    'ultrasonic_apparatus_categories': {
        'Branson 2510R-DTM': 'ultrasonic bath', 
        '1/8” sonicating probe': 'ultrasonic probe',
        'Kraintek Czech ultrasonic bath K-12': 'ultrasonic bath', 
        'cleaning bath': 'ultrasonic bath',
        'ultrasonic bath': 'ultrasonic bath'},
    'mixing_apparatus_categories': {
        'pulverisette': 'planetary mill',
        'planetary': 'planetary mill',
        'qm-100s': 'planetary mill',
        'xqm-0.4a': 'planetary mill',
        'fritsch pulverizette 23 mini-mill': 'planetary mill',
        'vibration mill': 'vibration mill',
        'vibratory mill': 'vibration mill',
        'vibrational rod mill': 'vibration mill',
        'oscillatory ball mill': 'vibration mill',
        'spex': 'vibration mill',
        'mortar and pestle': 'mortar and pestle',
        'pestle and mortar': 'mortar and pestle',
        'mortar-pestle': 'mortar and pestle',
        'mortar–pestle': 'mortar and pestle',
        'agate mortar': 'mortar and pestle',
        'porcelain mortar': 'mortar and pestle',
        'ceramic mortar': 'mortar and pestle',
        'mortar-and-pestle': 'mortar and pestle',
        'agate pestle-and-mortar': 'mortar and pestle',
        'mortar pestle': 'mortar and pestle',
        'mortar': 'mortar and pestle',
        'pestle': 'mortar and pestle',
        'manual': 'mortar and pestle',
        'manually': 'mortar and pestle',
        'spatula': 'mortar and pestle',
        'grinding jar': 'mortar and pestle',
        'mortal': 'mortar and pestle',
        'mechanical shaker': 'mortar and pestle',
        'agate mill': 'mortar and pestle',
        'wig-l-bug': 'ball mill',
        'wiggle-bug': 'ball mill',
        'wigglebug (grindex) apparatus': 'ball mill',
        'wigglebug (grindex) apparatus with stainless steel tube and steel ball': 'ball mill',
        'mixer/mill': 'ball mill',
        'fts1000': 'ball mill',
        'form-tech': 'ball mill',
        'ball mill': 'ball mill',
        'ball-mill': 'ball mill',
        'shaker mill': 'ball mill',
        'mixer mill': 'ball mill',
        'mm200': 'ball mill',
        'mm300': 'ball mill', 
        'mm400': 'ball mill',
        'mm301': 'ball mill',
        'mm 200': 'ball mill',
        'mm 300': 'ball mill',
        'mm 400': 'ball mill',
        'mm 301': 'ball mill',
        'retsch mm2 grinding apparatus': 'ball mill',
        'retsch pm1 mill': 'ball mill',
        'retsch cryomill': 'ball mill',
        'mixer-mill': 'ball mill',
        'milling jar': 'ball mill',
        'bench-top mill': 'ball mill',
        'laboratory stirrer (kamush, gdansk, poland) with two agate grinding balls 5 mm in diameter (eqiumed, cracow, poland)': 'ball mill'},
    'solvent_categories': {
        'bromoform': 'bromoform',
        'chbr3': 'bromoform',
        'bromocyclohexane': 'bromocyclohexane',
        'ch2br2': 'dibromomethane',
        'dibromomethane': 'dibromomethane',
        '1,2-dibromoethane': '1,2-dibromoethane',
        'benzyl bromide': 'benzyl bromide',
        '1,3-dibromobenzene': '1,3-dibromobenzene',
        'bromobenzene': 'bromobenzene',
        '1,2-dibromobenzene': '1,2-dibromobenzene',
        '2-bromopyridine': '2-bromopyridine',
        '3-bromopyridine': '3-bromopyridine',
        'propiolic acid': 'propiolic acid',
        '3-butyn-2-ol': '3-butyn-2-ol',
        'ethynylbenzene': 'ethynylbenzene',
        'phenylacetylene': 'ethynylbenzene',
        'dicyclopentadiene': 'dicyclopentadiene',
        'cyclododecene': 'cyclododecene',
        'indene': 'indene',
        'dicyclohexylamine': 'dicyclohexylamine',
        'dbu': 'diazabicycloundecene',
        'decalin': 'decahydronaphthalene',
        'perhydroisoquinoline': 'decahydroisoquinoline',
        'cyclohexane': 'cyclohexane',
        'cyclooctane': 'cyclooctane',
        'cyclodecane': 'cyclodecane',
        'pyrrolidine': 'pyrrolidine',
        'piperidine': 'piperidine',
        'tetrahydrofuran': 'tetrahydrofuran',
        'tetrahydrofurane': 'tetrahydrofuran',
        'terahydrofuran': 'tetrahydrofuran',
        'thf': 'tetrahydrofuran',
        'tetrahydropyrane': 'tetrahydropyran',
        'tetrahydropyran': 'tetrahydropyran',
        'morpholine': 'morpholine',
        'dioxane': '1,4-dioxane',
        'p-dioxane': '1,4-dioxane',
        '1,4 dioxane': '1,4-dioxane',
        'di-oxane': '1,4-dioxane',
        '1,4-dioxane': '1,4-dioxane',
        '1,3-dioxolane': '1,3-dioxolane',
        '1,3-dioxane': '1,3-dioxane',
        'thiomorpholine': 'thiomorpholine',
        '1,4-thioxane': '1,4-oxathiane',
        'methacrylic acid': 'methacrylic acid',
        'methyl methacrylate': 'methyl methacrylate',
        'benzyl methacrylate': 'benzyl methacrylate',
        'l-carvone': 'carvone',
        'carvone': 'carvone',
        'isopropenylbenzene': 'alpha-methylstyrene',
        'acrylonitrile': 'acrylonitrile',
        'ch2=chcooh': 'acrylic acid',
        '3-buten-2-ol': '3-buten-2-ol',
        '1,1,1-trifluoro-2-(trifluoromethyl)pent-4-en-2-ol': '2-allyl hexafluoroisopropanol',
        '2-allyl-1,1,1,3,3,3-hexafluoropropan-2-ol': '2-allyl hexafluoroisopropanol',
        'allyl acetate': 'allyl acetate',
        'allylbenzene': 'allylbenzene',
        'styrene': 'styrene',
        '4-vinylpyridine': '4-vinylpyridine',
        '4-vinyl pyridine': '4-vinylpyridine',
        'ketone': 'formaldehyde',
        'acetonitrile': 'acetonitrile',
        'acn': 'acetonitrile',
        'ch3cn': 'acetonitrile',
        'acétonitrile': 'acetonitrile',
        'mecn': 'acetonitrile',
        'acetonitril': 'acetonitrile',
        'pyruvic acid': 'pyruvic acid',
        'pyr': 'pyruvic acid',
        'pinacolone': 'pinacolone',
        '3-phenyl-2-butanone': '3-phenylbutan-2-one',
        'acetylacetone': 'acetylacetone',
        '2,4-pentadione': 'acetylacetone',
        'methylisobutylketone': '4-methyl-2-pentanone',
        'isobutyl methyl ketone': '4-methyl-2-pentanone',
        'mibk': '4-methyl-2-pentanone',
        'methyl isobutyl ketone': '4-methyl-2-pentanone',
        'acetonylacetone': '2,5-hexanedione',
        'n,n-dimethylacetamide': 'n,n-dimethylacetamide',
        'dmac': 'n,n-dimethylacetamide',
        'dimethylacetamide': 'n,n-dimethylacetamide',
        '6n h2so4': 'sulfuric acid',
        'acetic acid': 'acetic acid',
        'acoh': 'acetic acid',
        'glacial acetic acid': 'acetic acid',
        'ch3cooh': 'acetic acid',
        'tert-butyl acetate': 'tert-butyl acetate',
        'acetic anhydride': 'acetic anhydride',
        'isopropyl acetate': 'isopropyl acetate',
        'styralyl acetate': '1-phenylethyl acetate',
        'glycerol triacetate': 'triacetin',
        'isoamyl acetate': 'isoamyl acetate',
        'benzyl acetate': 'benzyl acetate',
        'phenyl acetate': 'phenyl acetate',
        'p-fluoroacetophenone': "4'-fluoroacetophenone",
        "4'-fluoroacetophenone": "4'-fluoroacetophenone",
        "3'-fluoroacetophenone": "3'-fluoroacetophenone",
        "1'-acetonaphthone": "1'-acetonaphthone",
        'acetophenone': 'acetophenone',
        "2'-chloroacetophenone": "2'-chloroacetophenone",
        '3,3-dimethyl-1-butanol': '3,3-dimethyl-1-butanol',
        '2,2-dimethyl-1-propanol': 'neopentyl alcohol',
        't-butylamine': 'tert-butylamine',
        'tert-butyl alcohol': 'tert-butanol',
        'tbuoh': 'tert-butanol',
        '2-methyl-2-propanol': 'tert-butanol',
        't-butanol': 'tert-butanol',
        'tert-butanol': 'tert-butanol',
        'tert-butyl benzoate': 'tert-butyl benzoate',
        '2,6-di-tert-butylpyridine': '2,6-di-tert-butylpyridine',
        'toluene, cumene': 'cumene',
        'geraniol': '3,7-dimethyl-2,6-octadienol',
        'dma': 'n,n-dimethylacetamide',
        '2-propanone': 'acetone',
        'deuterated acetone-d6': 'acetone',
        'acétone': 'acetone',
        'acetone': 'acetone',
        'aceton': 'acetone',
        'isobutyrophenone': 'isobutyrophenone',
        '3-methyl-2-butanol': '3-methyl-2-butanol',
        '2,4-dimethyl-3-pentanol': '2,4-dimethyl-3-pentanol',
        '4-methyl-2-pentanol': '4-methyl-2-pentanol',
        '4-methyl-1-pentanol': '4-methyl-1-pentanol',
        '3-methyl-1-butanol': 'isoamyl alcohol',
        'isoamyl alcohol': 'isoamyl alcohol',
        'isopentyl benzoate': 'isoamyl benzoate',
        'isobutanol': 'isobutanol',
        '2-methyl-1-propanol': 'isobutanol',
        'i-butanol': 'isobutanol',
        'iso-butanol': 'isobutanol',
        'i-buoh': 'isobutanol',
        'isobutyl benzoate': 'isobutyl benzoate',
        'isobutylbenzene': 'isobutylbenzene',
        'isopropyl alcohol': 'isopropyl alcohol',
        '2-propanol': 'isopropyl alcohol',
        'i-proh': 'isopropyl alcohol',
        'i-propanol': 'isopropyl alcohol',
        'iproh': 'isopropyl alcohol',
        'i-propyl-alcohol': 'isopropyl alcohol',
        'ipa': 'isopropyl alcohol',
        'iso-propanol': 'isopropyl alcohol',
        'isopropanol': 'isopropyl alcohol',
        'propan-2-ol': 'isopropyl alcohol',
        'isopropyl benzoate': 'isopropyl benzoate',
        'ipr2o': 'diisopropyl ether',
        'diisopropylether': 'diisopropyl ether',
        'di-isopropyl ether': 'diisopropyl ether',
        'diisopropyl ether': 'diisopropyl ether',
        'isopropyl ether': 'diisopropyl ether',
        'cumene': 'cumene',
        'isopropylbenzene': 'cumene',
        '1,1,1-trichloroethane': '1,1,1-trichloroethane',
        'ch3ccl3': '1,1,1-trichloroethane',
        'dichloroethane': '1,1-dichloroethane',
        'ace': 'acetic acid',
        '2-hydroxypropionitrile': 'lactonitrile',
        '3,3-dimethyl-2-butanol': '3,3-dimethyl-2-butanol',
        '2,3-butandiol': '2,3-butanediol',
        '4,4-dimethyl-2-pentanol': '4,4-dimethylpentan-2-ol',
        '1,2-propanediol': 'propylene glycol',
        '1-(4-chlorophenyl)ethanol': '1-(4-chlorophenyl)ethanol',
        '1-(3-fluorophenyl)ethanol': '1-(3-fluorophenyl)ethanol',
        'phenylethanol': '1-phenylethanol',
        'pyrr': 'pyrrolidine',
        'equimolar mixture of pyridine and 2-methylpyridine': 'pyridine',
        'isophorone': 'isophorone',
        'xylenes (isomeric mixture)': 'xylene',
        '3,5-dimethylcyclohexanol': '3,5-dimethylcyclohexanol',
        '3-methylcyclopentanone': '3-methylcyclopentanone',
        '4-methylcyclohexanone': '4-methylcyclohexanone',
        'gamma-valerolactone': 'gamma-valerolactone',
        'y-valerolactone': 'gamma-valerolactone',
        'menthone': 'menthone',
        '2,5-dimethylcyclohexanol': '2,5-dimethylcyclohexan-1-ol',
        '4-methylcyclohexylamine': '4-methylcyclohexylamine',
        '4-methylcyclohexanol': '4-methylcyclohexanol',
        '3,4-dimethylcyclohexanol': '3,4-dimethylcyclohexanol',
        '3-methylcyclohexanone': '3-methylcyclohexanone',
        'rac-3-methylcyclohexanone': '3-methylcyclohexanone',
        '3-methylcyclohexanol': '3-methylcyclohexanol',
        '2-methylcyclopentanone': '2-methylcyclopentanone',
        'methylcyclohexane': 'methylcyclohexane',
        '2-methylcyclohexanone': '2-methylcyclohexanone',
        '2-methylcyclohexanol': '2-methylcyclohexanol',
        'methyloxirane': 'propylene oxide',
        'propylene carbonate': 'propylene carbonate',
        'propionitrile': 'propionitrile',
        'etcn': 'propionitrile',
        'pentan-3-one': '3-pentanone',
        '3-pentanone': '3-pentanone',
        'propionic acid': 'propionic acid',
        'methyl propionate': 'methyl propionate',
        'benzyl propionate': 'benzyl propionate',
        'phenyl propionate': 'phenyl propionate',
        'p-fluoropropiophenone': 'p-fluoropropiophenone',
        '2-methylacetophenone': '1-phenyl-1-propanone',
        'propiophenone': '1-phenyl-1-propanone',
        '2-methyl-2-butanol': '2-methyl-2-butanol',
        't-pentanol': '2-methyl-2-butanol',
        '3-methyl-3-pentanol': '3-methyl-3-pentanol',
        '2-butanone': '2-butanone',
        'methyl ethyl ketone': '2-butanone',
        'butan-2-one': '2-butanone',
        '2-butanon': '2-butanone',
        'ethyl methyl ketone': '2-butanone',
        'butanone': '2-butanone',
        'ethylmethyl ketone': '2-butanone',
        'mek': '2-butanone',
        's-butyl bromide': '2-bromobutane',
        '2-methylbutyric acid': '2-methylbutanoic acid',
        'methyl ethyl acetone': '3-methyl-2-pentanone',
        '3-methyl-2-pentanol': '3-methyl-2-pentanol',
        '3-methyl-1-pentanol': '3-methyl-1-pentanol',
        '2-methyl-1-butanol': '2-methyl-1-butanol',
        '2-methylbutan-1-ol': '2-methyl-1-butanol',
        's-butyl chloride': '2-chlorobutane',
        's-butyl iodide': '2-iodobutane',
        's-butyl amine': 'butan-2-amine',
        'butan-2-ol': '2-butanol',
        'sec-butyl alcohol': '2-butanol',
        '2-butanol': '2-butanol',
        's-butyl methyl ether': 'sec-butyl methyl ether',
        's-butyl acetate': 'sec-butyl acetate',
        '2-ethyl-1-butanol': '2-ethyl-1-butanol',
        'a-ethylbenzylamine': '1-phenylpropan-1-amine',
        '2-methyl-3-pentanol': '2-methyl-3-pentanol',
        '3-pentanol': '3-pentanol',
        '1,2-butandiol': '1,2-butanediol',
        '1-phenyl-1-propanol': '1-phenyl-1-propanol',
        '2-ethylpiperidine': '2-ethylpiperidine',
        'butane': 'butane',
        '4-heptanone': '4-heptanone',
        'butyric acid': 'butyric acid',
        'benzyl n-butyrate': 'benzyl butyrate',
        'n-butyrophenone': 'butyrophenone',
        '2-methyl-2-pentanol': '2-methyl-2-pentanol',
        '2-pentanone': '2-pentanone',
        '2-methyl-1-pentanol': '2-methyl-1-pentanol',
        'racemic 3-methyl-2-pentanol': '2-pentanol',
        '2-pentanol': '2-pentanol',
        'pentan-2-ol': '2-pentanol',
        '3-hexanol': '3-hexanol',
        '4-heptanol': '4-heptanol',
        '1,2-pentandiol': '1,2-pentanediol',
        'pentane': 'pentane',
        'n-pentane': 'pentane',
        'pentanoic acid': 'valeric acid',
        'valeric acid': 'valeric acid',
        'n-valeric acid': 'valeric acid',
        '2-hexanone': '2-hexanone',
        '2-methyl-1-hexanol': '2-methylhexan-1-ol',
        '2-hexanol': '2-hexanol',
        '3-heptanol': 'heptan-3-ol',
        '5-nonanol': '5-nonanol',
        'n-hexane': 'hexane',
        'n-hexan': 'hexane',
        'hexane': 'hexane',
        'hexanes': 'hexane',
        'hexanoic acid': 'hexanoic acid',
        'caproic acid': 'hexanoic acid',
        'n-hexanophenone': 'hexanophenone',
        'methyl pentyl ketone': '2-heptanone',
        'isooctane': '2-methylheptane',
        '2-heptanol': '2-heptanol',
        '3-octanol': '3-octanol',
        '5-decanol': '5-decanol',
        'n-heptane': 'heptane',
        'heptane': 'heptane',
        'heptanoic acid': 'heptanoic acid',
        '2-octanol': '2-octanol',
        'n-octane': 'octane',
        'octane': 'octane',
        'caprylic acid': 'octanoic acid',
        'octanoic acid': 'octanoic acid',
        'nonanoic acid': 'nonanoic acid',
        'n-decane': 'decane',
        'undecanoic acid': 'undecanoic acid',
        'n-dodecane': 'dodecane',
        'dodecane': 'dodecane',
        'tetradecane': 'tetradecane',
        'ea': 'ethyl acetate',
        '1-decanol': '1-decanol',
        '1-nonanol': '1-nonanol',
        '1-octanol': '1-octanol',
        '1-heptanol': '1-heptanol',
        'n-hexanol': '1-hexanol',
        '1-hexanol': '1-hexanol',
        'hexanol': '1-hexanol',
        'n-hexyl benzoate': 'hexyl benzoate',
        'n-hexylbenzene': 'hexylbenzene',
        'pentanol': '1-pentanol',
        '1-pentanol': '1-pentanol',
        'amyl alcohol': '1-pentanol',
        'n-pentanol': '1-pentanol',
        'n-pentyl benzoate': 'pentyl benzoate',
        'n-pentylbenzene': 'pentylbenzene',
        '1-chlorobutane': '1-chlorobutane',
        'n-buoh': '1-butanol',
        'n-butanol': '1-butanol',
        'butan-1-ol': '1-butanol',
        'n-butyl alcohol': '1-butanol',
        'butanol': '1-butanol',
        '1-butanol': '1-butanol',
        'n-butyl benzoate': 'butyl benzoate',
        'butyl acetate': 'butyl acetate',
        '1-butyl acetate': 'butyl acetate',
        'n-butyl acetate': 'butyl acetate',
        'n-butylether': 'butyl ether',
        'n-butyl ether': 'butyl ether',
        'n-butylbenzene': 'butylbenzene',
        'n-propylamine': 'propylamine',
        'propylamine': 'propylamine',
        'tri-n-propylamine': 'tripropylamine',
        'di-n-propylamine': 'dipropylamine',
        'propan-1-ol': '1-propanol',
        'n-propanol': '1-propanol',
        'propanol': '1-propanol',
        'n-proh': '1-propanol',
        '1-propanol': '1-propanol',
        'n-propyl benzoate': 'propyl benzoate',
        '1-propyl acetate': 'propyl acetate',
        'propyl acetate': 'propyl acetate',
        'n-propylbenzene': 'propylbenzene',
        'ethylamine': 'ethylamine',
        'n,n-diethylformamide': 'n,n-diethylformamide',
        'tetraethylurea': '1,1,3,3-tetraethylurea',
        'triethylamine': 'triethylamine',
        'diethylamine': 'diethylamine',
        'n-ethylaniline': 'n-ethylaniline',
        'anhydrous ethanol': 'ethanol',
        'alcohol': 'ethanol',
        'absolute ethanol': 'ethanol',
        'etoh': 'ethanol',
        'ethanol': 'ethanol',
        'triflouro ethanol': 'ethanol',
        'ethyl alcohol': 'ethanol',
        'rectified ethanol': 'ethanol',
        'c2h5oh': 'ethanol',
        'absolute ethyl alcohol': 'ethanol',
        'ch3ch2oh': 'ethanol',
        'diethyl oxalate': 'diethyl oxalate',
        '6-carbethoxy-2,2,6-trimethylcyclohexanone': '6-carbethoxy-2,2,6-trimethylcyclohexanone',
        'ethyl 2-oxocyclohexanecarboxylate': 'ethyl 2-oxocyclohexanecarboxylate',
        'eda': 'ethylenediamine',
        'ethyl phenylacetate': 'ethyl phenylacetate',
        'ethyl methyl carbonate': 'ethyl methyl carbonate',
        'ethyl d-lactate': 'ethyl lactate',
        'ethyl l-lactate': 'ethyl lactate',
        'ethyl benzoate': 'ethyl benzoate',
        'ethyl acetate': 'ethyl acetate',
        'acoet': 'ethyl acetate',
        'etoac': 'ethyl acetate',
        'ethyl-acetate': 'ethyl acetate',
        'ethylacetate': 'ethyl acetate',
        'ethyl formate': 'ethyl formate',
        'diethyl ether': 'diethyl ether',
        'ethylether': 'diethyl ether',
        'diethylether': 'diethyl ether',
        'ethyl ether': 'diethyl ether',
        'ether': 'diethyl ether',
        'et2o': 'diethyl ether',
        '2-ethoxyethanol': '2-ethoxyethanol',
        'transcutol': 'diethylene glycol monoethyl ether',
        'diethyl sulfate': 'diethyl sulfate',
        '95% ethanol': 'ethanol',
        'petrol ether': 'petroleum ether',
        'melted ofn': 'octafluoronaphthalene',
        'p-diethoxybenzene': '1,4-diethoxybenzene',
        'phenetole': 'phenetole',
        'nitroethane': 'nitroethane',
        'etbr': 'ethidium bromide',
        'pet ether': 'petroleum ether',
        'ethyl benzene': 'ethylbenzene',
        'toluene, ethylbenzene, cumene': 'ethylbenzene',
        'toluene, ethylbenzene': 'ethylbenzene',
        'ethylbenzene, cumene': 'ethylbenzene',
        'ethylbenzene': 'ethylbenzene',
        'xylenes': 'xylene',
        '2-ethylpyridine': '2-ethylpyridine',
        '4-ethylpyridine': '4-ethylpyridine',
        'ch3cl': 'chloromethane',
        'iodomethane': 'iodomethane',
        'methyl iodide': 'iodomethane',
        '1,1,3,3-tetramethylurea': '1,1,3,3-tetramethylurea',
        'tetramethylurea': '1,1,3,3-tetramethylurea',
        'dimethylformamide (dmf)': 'n,n-dimethylformamide',
        'n,n-dimethylformamide': 'n,n-dimethylformamide',
        'dimethylformamide': 'n,n-dimethylformamide',
        'dimethyl formamide': 'n,n-dimethylformamide',
        'dmf': 'n,n-dimethylformamide',
        'hexamethylphosphoramide': 'hexamethylphosphoramide',
        'n,n-dimethylaniline': 'n,n-dimethylaniline',
        'nm': '1-methyl-2-pyrrolidinone',
        '1-methyl-2-pyrrolidinone': '1-methyl-2-pyrrolidinone',
        'n-methyl pyrrolidone': '1-methyl-2-pyrrolidinone',
        'n-methyl-pyrrolidone': '1-methyl-2-pyrrolidinone',
        'nmp': '1-methyl-2-pyrrolidinone',
        'n-methylpyrrolidone': '1-methyl-2-pyrrolidinone',
        'l-nicotine': '3-(1-methylpyrrolidin-2-yl)pyridine',
        '1,3-dimethyltetrahydropyrimidin-2(1h)-one': 'n,n′-dimethylpropyleneurea',
        'n,n-dimethylpiperazine': '1,4-dimethylpiperazine',
        '1,4-dimethylpiperazine': '1,4-dimethylpiperazine',
        'n-methylmorpholine': '4-methylmorpholine',
        'dimethylformamid': 'n-methylacetamide',
        'n-methylacetamide': 'n-methylacetamide',
        'n-methylisopropylamine': 'n-isopropylmethylamine',
        'perhydroisoquinoline mixture': 'perhydroisoquinoline',
        'c8h10 mixture': 'xylene',
        'c12h12 mixture': 'dimethylnaphthalene',
        'n-methylformamide': 'n-methylformamide',
        'dmi': '1,3-dimethyl-2-imidazolidinone',
        'n-methylaniline': 'n-methylaniline',
        'methyl alcohol': 'methanol',
        'methanol-water mixture': 'methanol',
        'meod': 'methanol',
        'distilled methanol': 'methanol',
        'deuterated methanol': 'methanol',
        'meoh': 'methanol',
        'methanol': 'methanol',
        'ch3oh': 'methanol',
        'water-methanol': 'methanol',
        'dimethyl ether': 'dimethyl ether',
        'methyl chloroacetate': 'methyl chloroacetate',
        'methyl phenylacetate': 'methyl phenylacetate',
        'dimethyl carbonate': 'dimethyl carbonate',
        'lambda-butyrolactone': 'oxolan-2-one',
        'trimethyl benzene-1,3,5-tricarboxylate': 'trimethyl benzene-1,3,5-tricarboxylate',
        'methyl benzoate': 'methyl benzoate',
        '4-methoxycarbonylpyridine': 'methyl isonicotinate',
        'methyl tertiary butyl ether': 'tert-butyl methyl ether',
        'tert-butylmethyl ether': 'tert-butyl methyl ether',
        'methyl tert-butyl ether': 'tert-butyl methyl ether',
        'mtbe': 'tert-butyl methyl ether',
        'tert-butyl methyl ether': 'tert-butyl methyl ether',
        't-buome': 'tert-butyl methyl ether',
        'tbme': 'tert-butyl methyl ether',
        'methyl acetate': 'methyl acetate',
        'ahf': 'hydrogen fluoride',
        '1-methoxy-2-propanol': '1-methoxy-2-propanol',
        '2-methoxyethanol': '2-methoxyethanol',
        'diglyme': 'diglyme',
        'benzyl methyl ether': 'benzyl methyl ether',
        'dimethyl isosorbide': 'dimethyl isosorbide',
        'tetramethoxysilane': 'tetramethoxysilane',
        '1,3,5-trimethoxybenzene': '1,3,5-trimethoxybenzene',
        'éther de pétrole': 'petroleum ether',
        '4-bromoanisole': '4-bromoanisole',
        '4mp': '4-methylpyrazole',
        '4-methylanisole': '4-methylanisole',
        'p-methylanisole': '4-methylanisole',
        'p-chloroanisole': '4-chloroanisole',
        '4-chloroanisole': '4-chloroanisole',
        '1,4-dimethoxybenzene': '1,4-dimethoxybenzene',
        'p-dimethoxybenzene': '1,4-dimethoxybenzene',
        'sf4': 'sulfur tetrafluoride',
        'tol': 'toluene',
        '3-methylanisole': '3-methoxytoluene',
        'm-methylanisole': '3-methoxytoluene',
        'm-chloroanisole': '3-chloroanisole',
        'm-dimethoxybenzene': '1,3-dimethoxybenzene',
        '1,3-dimethoxybenzene': '1,3-dimethoxybenzene',
        'anisole': 'anisole',
        'o-methylanisole': '2-methylanisole',
        '2-methylanisole': '2-methylanisole',
        'o-chloroanisole': '2-chloroanisole',
        'guaiacol': 'guaiacol',
        'o-dimethoxybenzene': '1,2-dimethoxybenzene',
        '1,2-dimethoxybenzene': '1,2-dimethoxybenzene',
        '4-methoxypyridine': '4-methoxypyridine',
        'dimethyl sulfoxide': 'dimethyl sulfoxide',
        'dimethylsulphoxide': 'dimethyl sulfoxide',
        'dmso': 'dimethyl sulfoxide',
        'dimethylsulfoxide': 'dimethyl sulfoxide',
        'dimethyl sulphoxide': 'dimethyl sulfoxide',
        'd6-dmso': 'dimethyl sulfoxide',
        'dimethylsulfoxyde': 'dimethyl sulfoxide',
        'dimethyl sulfide': 'dimethyl sulfide',
        'l-lactic acid': 'lactic acid',
        'anhydrous nitromethane': 'nitromethane',
        'ch3no2': 'nitromethane',
        'nitromethane': 'nitromethane',
        'meno2': 'nitromethane',
        'dme': 'dimethyl ether',
        '99% etoh': 'ethanol',
        'mesitylene': 'mesitylene',
        '1,3,5-trimethylbenzene (mesitylene)': 'mesitylene',
        '3,5-xylidine': '3,5-dimethylaniline',
        'collidine': '2,4,6-trimethylpyridine',
        '2,4,6-trimethylpyridine': '2,4,6-trimethylpyridine',
        '2,4,6-collidine': '2,4,6-trimethylpyridine',
        'dimethylnaphthalene mixture': 'dimethylnaphthalene',
        '4-bromotoluene': '4-bromotoluene',
        'carvacrol': 'carvacrol',
        '2-(4-methylphenyl)-1-propanol': '2-(4-methylphenyl)propan-1-ol',
        '1,2,4-trimethylbenzene': '1,2,4-trimethylbenzene',
        'para-xylene': 'p-xylene',
        'p-xylene': 'p-xylene',
        '2,5-dimethylpyridine': '2,5-lutidine',
        '4-chlorotoluene': '4-chlorotoluene',
        'p-chlorotoluene': '4-chlorotoluene',
        'p-cresol': 'p-cresol',
        '2mp': '2-methylpentane',
        'abs. etoh': 'ethanol',
        '2-methylquinoline': '2-methylquinoline',
        '6-methylquinoline': '6-methylquinoline',
        'meta-xylene': 'm-xylene',
        'm-xylene': 'm-xylene',
        '1,2,3-trimethylbenzene': '1,2,3-trimethylbenzene',
        '2,6-xylidine': '2,6-dimethylaniline',
        '2,6-dimethyl-aniline': '2,6-dimethylaniline',
        '2,6-dimethylaniline': '2,6-dimethylaniline',
        'lutidine': 'lutidine',
        '2,6-lutidine': '2,6-lutidine',
        '2,3-xylidine': '2,3-dimethylaniline',
        'm-cresol': 'm-cresol',
        '1-methylnaphthalene': '1-methylnaphthalene',
        '8-methylquinoline': '8-methylquinoline',
        'toluene': 'toluene',
        'toluol': 'toluene',
        'xylene': 'o-xylene',
        'o-xylene': 'o-xylene',
        'ortho-xylene': 'o-xylene',
        'o-cresol': 'o-cresol',
        '2-methylpyridine': '2-methylpyridine',
        'picoline': 'methylpyridine',
        '2-picoline': '2-methylpyridine',
        '2-methylpyridine and 4-methylpyridine': 'methylpyridine',
        '3-picoline': '3-methylpyridine',
        '3-methylpyridine': '3-methylpyridine',
        '3-methylpyridine and 4-methylpyridine': 'methylpyridine',
        'pyridine and 3-methylpyridine': 'methylpyridine',
        '2,3-lutidine': '2,3-lutidine',
        '2-amino-3-picoline': '2-amino-3-methylpyridine',
        '2,4-dimethylpyridine': '2,4-lutidine',
        '2,4-lutidine': '2,4-lutidine',
        '4-picoline': '4-methylpyridine',
        '4-methylpyridine': '4-methylpyridine',
        'pyridine and 4-methylpyridine': 'methylpyridine',
        '3,4-lutidine': '3,4-lutidine',
        '2,3,5-trimethylpyrazine': '2,3,5-trimethylpyrazine',
        '2,5-dimethylpyrazine': '2,5-dimethylpyrazine',
        '3,5-lutidine': '3,5-lutidine',
        '2-methylpyrazine': '2-methylpyrazine',
        'acetonitrile (ch,cn)': 'acetonitrile',
        'hydrochloric acid': 'hydrochloric acid',
        'trans-1,2-dichloroethene': '1,2-dichloroethylene',
        'cis-dichloroethylene': '1,2-dichloroethylene',
        'cis-1,2-dichloroethylene': '1,2-dichloroethylene',
        'cis-1,2-dichloroethene': '1,2-dichloroethylene',
        'bromotrichloromethane': 'bromotrichloromethane',
        'tetrachlormethan': 'carbon tetrachloride',
        'carbon tetrachloride': 'carbon tetrachloride',
        'tetrachloromethane': 'carbon tetrachloride',
        'carbon-tetrachloride': 'carbon tetrachloride',
        'ccl4': 'carbon tetrachloride',
        'chcl3': 'chloroform',
        'cdcl3': 'chloroform',
        'trichloromethane': 'chloroform',
        'dry chloroform': 'chloroform',
        'chloroforme': 'chloroform',
        'chloroform': 'chloroform',
        'dichlorobenzene-chloroform [1:1]': 'chloroform',
        'chlorocyclohexane': 'chlorocyclohexane',
        '1,1,2-trichloroethene': 'trichloroethylene',
        'trichloroethene': 'trichloroethylene',
        'tce': 'trichloroethylene',
        'bromochloromethane': 'bromochloromethane',
        'tetrachloroethane': '1,1,1,2-tetrachloroethane',
        '1,2,3-trichloropropane': '1,2,3-trichloropropane',
        'chcl2ch2cl': '1,1,2-trichloroethane',
        '1,1,2-trichloroethane': '1,1,2-trichloroethane',
        '1,2-dichloroethane': '1,2-dichloroethane',
        '1,2-dichlorethan': '1,2-dichloroethane',
        'cd2cl2': 'dichloromethane',
        'methylene chloride': 'dichloromethane',
        'dichloromethane': 'dichloromethane',
        'ch2cl2': 'dichloromethane',
        'dichloromethane (dcm)': 'dichloromethane',
        'h2ccl2': 'dichloromethane',
        'dichlormethan': 'dichloromethane',
        'benzyl chloride': 'benzyl chloride',
        'hexachlorobenzene': 'hexachlorobenzene',
        '1,2,4-trichlorobenzene': '1,2,4-trichlorobenzene',
        'tetrachlorobenzene': '1,2,3,4-tetrachlorobenzene',
        'ortho-dichlorobenzene, meta-dichlorobenzene': '1,4-dichlorobenzene',
        '1,3-dichlorobenzene': '1,3-dichlorobenzene',
        'meta-dichlorobenzene': '1,3-dichlorobenzene',
        'chlorbenzol': 'chlorobenzene',
        'chlorobenzene': 'chlorobenzene',
        'o-dcb': '1,2-dichlorobenzene',
        '1,2-dichlorobenzene': '1,2-dichlorobenzene',
        'o-dichlorobenzene': '1,2-dichlorobenzene',
        'ortho-dichlorobenzene': '1,2-dichlorobenzene',
        'dichlorobenzene': '1,2-dichlorobenzene',
        '2-chloropyridine': '2-chloropyridine',
        '3-chloropyridine': '3-chloropyridine',
        'hydrofluoric acid': 'hydrofluoric acid',
        'sulfur tetrafluoride': 'sulfur tetrafluoride',
        'bromopentafluorobenzene': 'bromopentafluorobenzene',
        'hexafluorobenzene': 'hexafluorobenzene',
        'perfluorobenzene': 'hexafluorobenzene',
        'iodopentafluorobenzene': 'iodopentafluorobenzene',
        '1,2,3,5-tetrafluorobenzene': '1,2,3,5-tetrafluorobenzene',
        'pentafluorobenzene': 'pentafluorobenzene',
        '1,2,4,5-tetrafluorobenzene': '1,2,4,5-tetrafluorobenzene',
        '1,3,5-trifluorobenzene': '1,3,5-trifluorobenzene',
        'trifluorobenzene': '1,2,3-trifluorobenzene',
        'fluorobenzene': 'fluorobenzene',
        'perfluoropyridine': 'pentafluoropyridine',
        'diiodomethane': 'diiodomethane',
        'iodobenzene': 'iodobenzene',
        'ammonia': 'ammonia',
        'n,n-dimethylphenylglyoxylamide (3a)': 'n,n-dimethylphenylglyoxylamide',
        'liquid ammonia': 'ammonia',
        'n,n-diethylphenylglyoxylamide (3b)': 'n,n-diethylphenylglyoxylamide',
        'cinnamonitrile': '3-phenylprop-2-enenitrile',
        'benzyl cyanide': 'phenylacetonitrile',
        'benzonitrile': 'benzonitrile',
        'benzonitril': 'benzonitrile',
        '2-cyanopyridine': 'pyridine-2-carbonitrile',
        'n-methyl-n-phenylphenylglyoxylamide (3d)': 'n-methyl-2-oxo-2-phenylacetamide',
        'cyclohexylamine': 'cyclohexanamine',
        'cyclooctyl amine': 'cyclooctanamine',
        'decalin mixture': 'decalin',
        'formamide': 'formamide',
        'ethylenediamine': 'ethylenediamine',
        'ethylene diamine': 'ethylenediamine',
        '3mp': '3-methylpyridine',
        'hydrazine hydrate': 'hydrazine hydrate',
        'formylhydrazine': 'formylhydrazine',
        '3,4-difluoroaniline': '3,4-difluoroaniline',
        '4-fluoroaniline': '4-fluoroaniline',
        '3-chloroaniline': '3-chloroaniline',
        '3-fluoroaniline': '3-fluoroaniline',
        'aniline': 'aniline',
        '2-fluoroaniline': '2-fluoroaniline',
        'anhydrous n2h4': 'hydrazine',
        'anhydrous methanol': 'methanol',
        'dcm': "dichloromethane",
        'double distilled water': 'water',
        'triple distilled water': 'water',
        'pure water': 'water',
        'millipore water': 'water',
        'milli-q water': 'water',
        'deionized water': 'water',
        'distillated water': 'water',
        'h2o': 'water',
        'h2o (water)': 'water',
        'distilled water': 'water',
        'tripled distilled water': 'water',
        'ice water': 'water',
        'wasser': 'water',
        'distilled deionized water': 'water',
        'water': 'water',
        'purified water': 'water',
        '1,3-diphenylacetone': '1,3-diphenylacetone',
        'benzoyl chloride': 'benzoyl chloride',
        'trifluoroacetic acid': 'trifluoroacetic acid',
        'benzyl benzoate': 'benzyl benzoate',
        'phenyl benzoate': 'phenyl benzoate',
        'benzophenone': 'benzophenone',
        '2-cyclopenten-1-one': '2-cyclopenten-1-one',
        'cyclopentenone': '2-cyclopenten-1-one',
        'cyclohexenone': '2-cyclohexen-1-one',
        '2-cyclohexen-1-one': '2-cyclohexen-1-one',
        'cyclopentanone': 'cyclopentanone',
        'cyclohexanone': 'cyclohexanone',
        'cycloheptanone': 'cycloheptanone',
        'epsilon-caprolactone': 'epsilon-caprolactone',
        '2-pyrrolidone': '2-pyrrolidinone',
        'g-butyrolactone': 'gamma-butyrolactone',
        'gamma-butyrolactone': 'gamma-butyrolactone',
        '4-hydroxybutanoic acid lactone': 'gamma-butyrolactone',
        'butyrolactone': 'gamma-butyrolactone',
        '1-tetralone': '1-tetralone',
        'phh': 'benzene',
        '98% formic acid': 'formic acid',
        'formic acid': 'formic acid',
        'benzyl formate': 'benzyl formate',
        'benzaldehyde': 'benzaldehyde',
        'salicylaldehyde': 'salicylaldehyde',
        '1,1,1,3,3,3-hexaflouro-2-propanol': 'hexafluoroisopropanol',
        'sulfolane': 'sulfolane',
        'so2': 'sulfur dioxide',
        'trichloronitromethane': 'chloropicrin',
        '1,3-dinitrobenzene': '1,3-dinitrobenzene',
        'nitrobenzene': 'nitrobenzene',
        '2-pyridone': '2-hydroxypyridine',
        '1,1,1,3,3,3-hexafluoro-2-propanol': 'hexafluoroisopropanol',
        '2-chloro-1-phenylethanol': '2-chloro-1-phenylethanol',
        'trifluoroethanol': '2,2,2-trifluoroethanol',
        '2-phenyl-1,1,1,3,3,3-hexafluoropropan-2-ol': 'hexafluoroisopropanol',
        'cyclopentanol': 'cyclopentanol',
        'cyclohexanol': 'cyclohexanol',
        'pe': 'petroleum ether',
        '2,2,2-trifluoroethanol': '2,2,2-trifluoroethanol',
        'tfe': '2,2,2-trifluoroethanol',
        '2,2,2-trifluoro ethanol': '2,2,2-trifluoroethanol',
        '1,7-heptandiol': '1,7-heptanediol',
        '1,6-hexanediol': '1,6-hexanediol',
        '1,4-dihydroxybutane': '1,4-butanediol',
        'butane-1,4-diol': '1,4-butanediol',
        '1,4-butandiol': '1,4-butanediol',
        '1,3-propanediol': '1,3-propanediol',
        '1,3-dihydroxypropane': '1,3-propanediol',
        '2-morpholinoethanol': '2-morpholinoethanol',
        '1,2-dihydroxyethane': 'ethylene glycol',
        'ethylene glycol': 'ethylene glycol',
        'diethylene glycol': 'diethylene glycol',
        '2-phenylethanol': '2-phenylethanol',
        '4-fluorobenzyl alcohol': 'p-fluorobenzyl alcohol',
        '3-fluorobenzyl alcohol': '3-fluorobenzyl alcohol',
        'benzyl alcohol': 'benzyl alcohol',
        'isoamylic alcohol': 'benzyl alcohol',
        '2-fluorobenzyl alcohol': 'benzenemethanol, 2-fluoro-',
        'h2o2': 'hydrogen peroxide',
        'hydrogen peroxide': 'hydrogen peroxide',
        '96% wt. hydrogen peroxide': 'hydrogen peroxide',
        '75% hydrogen peroxide': 'hydrogen peroxide',
        '96% hydrogen peroxide': 'hydrogen peroxide',
        'aqueous hydrogen peroxide': 'hydrogen peroxide',
        '98% hydrogen peroxide': 'hydrogen peroxide',
        '1,3,5-trihydroxybenzene': 'phloroglucinol',
        '4-chlorophenol': '4-chlorophenol',
        'm-bromophenol': '3-bromophenol',
        '3-chlorophenol': '3-chlorophenol',
        'm-fluorophenol': '3-fluorophenol',
        'phenol': 'phenol',
        'o-chlorophenol': '2-chlorophenol',
        'o-fluorophenol': '2-fluorophenol',
        'cs2': 'carbon disulfide',
        'carbon disulfide': 'carbon disulfide',
        'ipa (isopropanol)': 'isopropyl alcohol',
        'hex-ace': 'hexyl acetate',
        'pyridine, 4-methylpyridine (equimolar mixture)': 'pyridine',
        'mixture of 2-methylpyridine and 4-methylpyridine (varied ratios)': 'methylpyridine',
        'conc. acetic acid': 'acetic acid',
        'pyridine, 2-methylpyridine (equimolar mixture)': 'pyridine',
        'mixture of pyridine and 2-methylpyridine (varied ratios)': 'pyridine',
        'cis-dce': '1,2-dichloroethylene',
        'anhydrous 2-butanone': '2-butanone',
        'mixture of three lutidine isomers': 'lutidine',
        'ma isomer mixture': 'methacrylic acid',
        'butyl acetate saturated with polyvinylpyrrolidone (pvp) k25': 'butyl acetate',
        'mixture of guests (pyridine, 2-picoline, 3-picoline, 4-picoline)': 'pyridine',
        '50% ethanol': 'ethanol',
        'hf2p': 'hexafluoroisopropanol',
        'mixture of 3,5-lutidine and 2,6-lutidine': 'lutidine',
        'pyridine, 3-methylpyridine (equimolar mixture)': 'pyridine',
        'prioh': 'isopropyl alcohol',
        'dry acetonitrile': 'acetonitrile',
        'petroleum (60-80 °)': 'petroleum ether',
        'dry methanol': 'methanol',
        'isopropanol (ipa)': 'isopropyl alcohol',
        '1:1 mixture of 2-methyl- and 3-methylcyclopentanone': '2-methylcyclopentanone',
        'petrol spirit': 'petroleum ether',
        'dioxane-h2o (v : v = 2 : 1)': '1,4-dioxane',
        'equimolar mixture of 2,3-lutidine and 3,4-lutidine': 'lutidine',
        'essigsäure': 'acetic acid',
        'mixture of 2-picoline, 3-picoline, and 4-picoline': 'methylpyridine',
        'pyr (pyridine)': 'pyridine',
        'mixture of liquid quinoline and 8-methylquinoline': 'quinoline',
        'n-valerophenone': 'valerophenone',
        '2-proh': 'isopropyl alcohol',
        'benzene or toluene': 'benzene',
        'dry diethyl ether': 'diethyl ether',
        'equimolar mixture of pyridine and 4-methylpyridine': 'pyridine',
        'concentrated nitric acid': 'nitric acid',
        'aniline, n-methylaniline, n,n-dimethylaniline': 'aniline',
        'propan-2-01': 'isopropyl alcohol',
        'cl2acoh': 'dichloroacetic acid',
        'ch2c12': 'dichloromethane',
        'aqueous buffer solution (ph 7)': 'water',
        'ethyl acetate, acetonitrile': 'ethyl acetate',
        'equimolar mixture of 2-methylpyridine and 4-methylpyridine': 'methylpyridine',
        'dry ethanol': 'ethanol',
        'dry ether': 'diethyl ether',
        'h2o nanopure': 'water',
        'mixture of 3-methylpyridine and 2-methylpyridine (varied ratios)': 'methylpyridine',
        'pyridine, 3-methylpyridine, 4-methylpyridine (equimolar mixture)': 'pyridine',
        'mixed solvent of 2:3 (v/v) ethanol/water': 'ethanol',
        'chc13': 'chloroform',
        '15 %-iger wässriger perchlorsäure': 'perchloric acid',
        'petroleum spirit': 'petroleum ether',
        'petroleum ether 40/60': 'petroleum ether',
        'f2ani': '3,4-difluoroaniline',
        "n,n,n',n',n'',n''-hexamethylphosphoramide": 'hexamethylphosphoramide',
        'mixture of pyridine and picolines': 'pyridine',
        'different hplc grade solvent systems (esi table s1)': 'acetonitrile',
        'n,n-diethyl-m-toluamide (deet)': 'diethyltoluamide',
        'ac6tonitrile': 'acetonitrile',
        'racemic butan-2-ol': '2-butanol',
        'eiessig': 'acetic acid',
        'mixture of 2-picoline and 3-picoline': 'methylpyridine',
        'pyridine, 2-methylpyridine, 4-methylpyridine (equimolar mixture)': 'pyridine',
        'diethyl acetate': 'diethyl acetate',
        'light petroleum': 'petroleum ether',
        'etac': 'ethyl acetate',
        'tbutanol': 'tert-butanol',
        '3mp (3-methylpyridine)': '3-methylpyridine',
        'damp methanol': 'methanol',
        'petroleum ether': 'petroleum ether',
        '1:4 mecn:water': 'acetonitrile',
        'isopropylic alcohol': 'isopropyl alcohol',
        'mixture of 3-methylpyridine and 4-methylpyridine (varied ratios)': 'methylpyridine',
        'ethanol/water mixture (3:7 v/v)': 'ethanol',
        'mixture of liquid 6-methylquinoline and 8-methylquinoline': 'methylquinoline',
        'o-toluidine (1)': 'o-toluidine',
        'distilled h2o': 'water',
        '1,4-dioxane, acetonitrile': '1,4-dioxane',
        'pentane or hexane': 'hexane',
        '1,2-dichloromoethane': '1,2-dichloroethane',
        'o-chlorotoluene (3)': 'o-chlorotoluene',
        '50% hydrogen peroxide': 'hydrogen peroxide',
        'ethanol, distilled water': 'ethanol',
        'aniline, n-methylaniline': 'aniline',
        'phenyl azide (1)': 'phenyl azide',
        'mixed solvent of 1:4 (v/v) ethanol/water': 'ethanol',
        'éther sulfurique': 'diethyl ether',
        '4mp (4-methylpyridine)': '4-methylpyridine',
        'mixture of liquid 2-methylquinoline and 8-methylquinoline': 'methylquinoline',
        'equimolar mixture of 2-methylpyridine and 3-methylpyridine': 'methylpyridine',
        '1:1 v/v mixture of cis- and trans-dce': '1,2-dichloroethylene',
        'o-bromotoluene (4)': 'o-bromotoluene',
        '1,2-dme': '1,2-dimethoxyethane',
        '2-methylpyridine, 3-methylpyridine and 4-methylpyridine': 'methylpyridine',
        'dry meoh': 'methanol',
        'dry hydrazine': 'hydrazine',
        'mixture of pyridine and 3-methylpyridine (varied ratios)': 'pyridine',
        'aniline, n,n-dimethylaniline': 'aniline',
        'ethanol (95%)': 'ethanol',
        'ch3ch2cooh': 'propionic acid',
        'o cl2c6h4': '1,2-dichlorobenzene',
        'pyridine, 2-methylpyridine and 3-methylpyridine': 'pyridine',
        'dry chcl3': 'chloroform',
        'concentrated hydrochloric acid': 'hydrochloric acid',
        'mixture of 2,4-lutidine and 3,5-lutidine': 'lutidine',
        'dried ethanol': 'ethanol',
        'mixture of liquid 2-methylquinoline and 6-methylquinoline': 'methylquinoline',
        '(ch3)2c=o': 'acetone',
        'mixture of 2,4-lutidine and 2,6-lutidine': 'lutidine',
        'ethanol-water mixture': 'ethanol',
        'ethyl d/l-lactate': 'ethyl lactate',
        'methanol/water mixture': 'methanol',
        '2-methylpyridine, 4-methylpyridine (equimolar mixture)': 'methylpyridine',
        'equimolar mixture of pyridine and 3-methylpyridine': 'pyridine',
        'mixture of two picoline isomers': 'methylpyridine',
        '2-salicylaldehyde': 'salicylaldehyde',
        'trichloracetonitrile': 'trichloracetonitrile',
        'racemic 2-butanol': '2-butanol',
        'pyridine, 2-methylpyridine, 3-methylpyridine (equimolar mixture)': 'pyridine',
        'thf-h2o (v : v = 2 : 1)': 'tetrahydrofuran',
        'n-methylaniline, n,n-dimethylaniline': 'n-methylaniline',
        '2-methylpyridine, 3-methylpyridine, 4-methylpyridine (equimolar mixture)': 'methylpyridine',
        'equimolar mixture of pyridine, 2-methylpyridine, 3-methylpyridine, 4-methylpyridine': 'pyridine',
        'equimolar mixture of 3-methylpyridine and 4-methylpyridine': 'methylpyridine',
        'mixed xylenes': 'xylene',
        'm-fluoroaniline (2)': '3-fluoroaniline',
        '3-picoline and 4-picoline mixture': 'methylpyridine',
        '30% hydrogen peroxide': 'hydrogen peroxide',
        'eisessig': 'acetic acid',
        'n,n′-dimethylformamide': 'n,n-dimethylformamide',
        'equimolar mixture of 2,3-lut and 3,4-lut': 'lutidine',
        'mixture of two lutidine isomers': 'lutidine',
        'ethanol/water mixture': 'ethanol',
        '2,4-lutidine and 3,5-lutidine mixture': 'lutidine',
        'mixture of three picoline isomers': 'methylpyridine',
        'mixture of liquid quinoline and 2-methylquinoline': 'quinoline',
        'tetrahydrofuran (thf)': 'tetrahydrofuran',
        'pyridine, 2-methylpyridine, 3-methylpyridine and 4-methylpyridine': 'pyridine',
        'mixture of 3-picoline and 4-picoline': 'methylpyridine',
        'anhydrous benzene': 'benzene',
        '2 m hcl solution': 'hydrochloric acid',
        '2-methylpyridine, 3-methylpyridine (equimolar mixture)': 'methylpyridine',
        'mixture of lutidines': 'lutidine',
        'deionized h2o': 'water',
        'aqueous naclo4 solution': 'water',
        '40% methanol aqueous solution': 'methanol',
        'diiosopropylether': 'diisopropyl ether',
        'mixture of 2,4-lutidine, 3,5-lutidine, and 2,6-lutidine': 'lutidine',
        'ethyl acetate saturated with pvp k25': 'ethyl acetate',
        'acetone and water (4:1 v/v mixture)': 'acetone',
        'mixture of pyridine and 4-methylpyridine (varied ratios)': 'pyridine',
        'organic solvent or water/organic mixture': 'water',
        'aqueous solution': 'water',
        'equimolar mixture of 2-methylpyridine, 3-methylpyridine, 4-methylpyridine': 'methylpyridine',
        'mixture of liquid quinoline and 6-methylquinoline': 'quinoline',
        'indene (5)': 'indene',
        'liquid xylidines': '2,6-dimethylaniline',
        'ethanol/water mixture (1:1 v/v)': 'ethanol',
        'pyridine, 2-methylpyridine, 3-methylpyridine, 4-methylpyridine (equimolar mixture)': 'pyridine',
        'dry acoet': 'ethyl acetate',
        '3-methylpyridine, 4-methylpyridine (equimolar mixture)': 'methylpyridine',
        'isopropyl benzoate (3e)': 'isopropyl benzoate',
        'r,r,r-trifluorotoluene': 'benzotrifluoride',
        'acetone-d6': 'acetone',
        'ch3od': 'methanol',
        'deuterated water': 'water',
        'd2o': 'water',
        'heavy water': 'water',
        'benzene-d6': 'benzene',
        'pyridine-d5': 'pyridine',
        'bromine': 'hydrogen bromide',
        'perchloric acid': 'perchloric acid',
        'cyclohexylbenzene': 'cyclohexylbenzene',
        'benzyl phenyl ether': 'benzyl phenyl ether',
        'benzylbenzene': 'diphenylmethane',
        'ph2o': 'diphenyl ether',
        'diphenyl ether': 'diphenyl ether',
        'tetralin': 'tetralin',
        'indoline': 'indoline',
        'naphthalene': 'naphthalene',
        'isoquinoline': 'isoquinoline',
        'quinoline': 'quinoline',
        'c6h6': 'benzene',
        'benzol': 'benzene',
        'benzene': 'benzene',
        'pyridine': 'pyridine',
        'py': 'pyridine',
        'furan': 'furan',
        'thiophene': 'thiophene',
        'pyrazine': 'pyrazine'},
    "solvent_families": {'hydrogen bromide': 'acids',
        'ethylene glycol': 'alcohols',
        'propionic acid': 'acids',
        '1,2-pentanediol': 'alcohols',
        'isoamyl alcohol': 'alcohols',
        'petroleum ether': 'ethers',
        'bromoform': 'halogenated',
        'methyl methacrylate': 'esters',
        '1,7-heptanediol': 'alcohols',
        'nitromethane': 'special',
        '4-methylpyrazole': 'amines',
        'benzyl methyl ether': 'ethers',
        'dimethyl sulfoxide': 'sulfur',
        'allyl acetate': 'esters',
        'dimethyl isosorbide': 'ethers',
        '2-methyl-1-butanol': 'alcohols',
        'benzyl benzoate': 'esters',
        'pinacolone': 'carbonyls',
        'n-methyl-2-oxo-2-phenylacetamide': 'amides',
        'toluene': 'hydrocarbons',
        'phenyl acetate': 'esters',
        '2-pentanone': 'carbonyls',
        'iodomethane': 'halogenated',
        'phenyl azide': 'special',
        '3-chlorophenol': 'alcohols',
        'thiophene': 'ethers',
        'isoquinoline': 'amines',
        'iodopentafluorobenzene': 'halogenated',
        '4-ethylpyridine': 'amines',
        '3-chloroanisole': 'ethers',
        'diphenyl ether': 'ethers',
        'nonanoic acid': 'acids',
        'isopropyl benzoate': 'esters',
        '2-methylpentane': 'hydrocarbons',
        'tert-butylamine': 'amines',
        '3,3-dimethyl-1-butanol': 'alcohols',
        'heptane': 'hydrocarbons',
        '2-ethoxyethanol': 'alcohols',
        '1,4-butanediol': 'alcohols',
        '4-methyl-1-pentanol': 'alcohols',
        '2-pentanol': 'alcohols',
        'heptan-3-ol': 'alcohols',
        'water': 'water',
        "4'-fluoroacetophenone": 'carbonyls',
        '1,3-propanediol': 'alcohols',
        '2-pyrrolidinone': 'amides',
        'oxolan-2-one': 'esters',
        '1,6-hexanediol': 'alcohols',
        'mesitylene': 'hydrocarbons',
        'tetrahydropyran': 'ethers',
        '4-methylanisole': 'ethers',
        '2,5-lutidine': 'amines',
        '3,7-dimethyl-2,6-octadienol': 'alcohols',
        '1,3-dichlorobenzene': 'halogenated',
        'methyl chloroacetate': 'esters',
        'allylbenzene': 'hydrocarbons',
        'propylbenzene': 'hydrocarbons',
        'indoline': 'amines',
        '1,3-dibromobenzene': 'halogenated',
        'methylcyclohexane': 'hydrocarbons',
        'heptanoic acid': 'acids',
        'phenyl benzoate': 'esters',
        '1-butanol': 'alcohols',
        '1-methyl-2-pyrrolidinone': 'amides',
        '2,4-dimethyl-3-pentanol': 'alcohols',
        'pentane': 'hydrocarbons',
        '1-propanol': 'alcohols',
        'hexyl acetate': 'esters',
        '1,1,2-trichloroethane': 'halogenated',
        'isophorone': 'carbonyls',
        '1-phenylethyl acetate': 'esters',
        'tetralin': 'hydrocarbons',
        'n,n-dimethylaniline': 'amines',
        'benzene': 'hydrocarbons',
        'ethylbenzene': 'hydrocarbons',
        '4-chloroanisole': 'ethers',
        'n-methylformamide': 'amides',
        '2-hexanol': 'alcohols',
        '2-chloropyridine': 'amines',
        '3,5-dimethylcyclohexanol': 'alcohols',
        'dipropylamine': 'amines',
        'dimethyl carbonate': 'esters',
        'hexamethylphosphoramide': 'amides',
        '4-fluoroaniline': 'amines',
        'acetophenone': 'carbonyls',
        'alpha-methylstyrene': 'hydrocarbons',
        '3-methylcyclohexanol': 'alcohols',
        '1,4-diethoxybenzene': 'hydrocarbons',
        'epsilon-caprolactone': 'esters',
        '1-nonanol': 'alcohols',
        'tert-butyl benzoate': 'esters',
        '4-vinylpyridine': 'amines',
        '6-methylquinoline': 'amines',
        'naphthalene': 'hydrocarbons',
        '2-methylcyclohexanol': 'alcohols',
        'butyl acetate': 'esters',
        '1-phenylethanol': 'alcohols',
        'tert-butyl acetate': 'esters',
        'tert-butanol': 'alcohols',
        '2,3-dimethylaniline': 'amines',
        '2-butanone': 'carbonyls',
        '1,2-butanediol': 'alcohols',
        '8-methylquinoline': 'amines',
        '2-methylpyrazine': 'amines',
        'quinoline': 'amines',
        'ethanol': 'alcohols',
        'isobutanol': 'alcohols',
        '2-butanol': 'alcohols',
        '2-methyl-2-pentanol': 'alcohols',
        '3-bromopyridine': 'amines',
        "1'-acetonaphthone": 'carbonyls',
        '4-methylmorpholine': 'amines',
        'carvacrol': 'alcohols',
        'formamide': 'amides',
        'diethyl sulfate': 'special',
        '1,4-dimethoxybenzene': 'hydrocarbons',
        'o-bromotoluene': 'halogenated',
        'perhydroisoquinoline': 'amines',
        'hydrofluoric acid': 'acids',
        '3,4-dimethylcyclohexanol': 'alcohols',
        'dichloroacetic acid': 'acids',
        'ethyl acetate': 'esters',
        'cyclododecene': 'hydrocarbons',
        '3-fluoroaniline': 'amines',
        '4-heptanol': 'alcohols',
        '3-methylcyclohexanone': 'carbonyls',
        '4-methylpyridine': 'amines',
        'acetone': 'carbonyls',
        '2-heptanone': 'carbonyls',
        'styrene': 'hydrocarbons',
        '3-fluorophenol': 'alcohols',
        '2,6-di-tert-butylpyridine': 'amines',
        'trifluoroacetic acid': 'acids',
        'bromobenzene': 'halogenated',
        'morpholine': 'amines',
        '1,1,3,3-tetraethylurea': 'amides',
        '3-methyl-2-pentanol': 'alcohols',
        'hexachlorobenzene': 'halogenated',
        'carbon disulfide': 'special',
        '2,3,5-trimethylpyrazine': 'amines',
        '1,2,3-trichloropropane': 'halogenated',
        'benzyl acetate': 'esters',
        'ethyl phenylacetate': 'esters',
        '4-methyl-2-pentanol': 'alcohols',
        'undecanoic acid': 'acids',
        'pyruvic acid': 'acids',
        'pyrazine': 'amines',
        'acetic acid': 'acids',
        '1,3,5-trimethoxybenzene': 'hydrocarbons',
        'dicyclohexylamine': 'amines',
        '1,1,1-trichloroethane': 'halogenated',
        'bromopentafluorobenzene': 'halogenated',
        '1,2,3-trimethylbenzene': 'hydrocarbons',
        'hydrogen peroxide': 'special',
        '2-octanol': 'alcohols',
        '1,2-dichlorobenzene': 'halogenated',
        'piperidine': 'amines',
        'pentyl benzoate': 'esters',
        'dodecane': 'hydrocarbons',
        '1-heptanol': 'alcohols',
        'benzaldehyde': 'carbonyls',
        'acetylacetone': 'carbonyls',
        '2-fluoroaniline': 'amines',
        'o-xylene': 'hydrocarbons',
        '3-methylcyclopentanone': 'carbonyls',
        '1,2,3,4-tetrachlorobenzene': 'halogenated',
        '2-fluorophenol': 'alcohols',
        '1-hexanol': 'alcohols',
        '2,4,6-trimethylpyridine': 'amines',
        '4,4-dimethylpentan-2-ol': 'alcohols',
        'pyridine-2-carbonitrile': 'amines',
        'butane': 'hydrocarbons',
        'cyclohexanol': 'alcohols',
        'gamma-valerolactone': 'esters',
        'diethylene glycol': 'alcohols',
        '2,6-lutidine': 'amines',
        'ethyl formate': 'esters',
        'n,n-dimethylformamide': 'amides',
        'carvone': 'carbonyls',
        '1,3-dinitrobenzene': 'hydrocarbons',
        'o-chlorotoluene': 'halogenated',
        'pyridine': 'amines',
        'butan-2-amine': 'amines',
        '4-bromoanisole': 'ethers',
        '2,3-lutidine': 'amines',
        'chloroform': 'halogenated',
        'carbon tetrachloride': 'halogenated',
        'bromochloromethane': 'halogenated',
        '2-methylquinoline': 'amines',
        'ethyl lactate': 'esters',
        '1,2,4,5-tetrafluorobenzene': 'halogenated',
        '4-heptanone': 'carbonyls',
        'hexanoic acid': 'acids',
        '1-octanol': 'alcohols',
        'diethyl oxalate': 'esters',
        '2-(4-methylphenyl)propan-1-ol': 'alcohols',
        'hexafluorobenzene': 'halogenated',
        'benzyl butyrate': 'esters',
        'octane': 'hydrocarbons',
        'hydrogen fluoride': 'acids',
        '4-methoxypyridine': 'amines',
        'hydrazine': 'amines',
        'phenylacetonitrile': 'nitriles',
        'methyl benzoate': 'esters',
        '2-cyclopenten-1-one': 'carbonyls',
        'phloroglucinol': 'alcohols',
        'o-toluidine': 'amines',
        'p-fluoropropiophenone': 'carbonyls',
        'benzoyl chloride': 'special',
        'decalin': 'hydrocarbons',
        '4-chlorotoluene': 'halogenated',
        '2-phenylethanol': 'alcohols',
        'sulfolane': 'sulfur',
        'tetradecane': 'hydrocarbons',
        'benzophenone': 'carbonyls',
        "3'-fluoroacetophenone": 'carbonyls',
        '1,2,3,5-tetrafluorobenzene': 'halogenated',
        'dimethyl ether': 'ethers',
        'chlorobenzene': 'halogenated',
        '1,4-oxathiane': 'ethers',
        '2-bromopyridine': 'amines',
        'hexanophenone': 'carbonyls',
        '4-methyl-2-pentanone': 'carbonyls',
        'neopentyl alcohol': 'alcohols',
        'diethyltoluamide': 'amides',
        'diiodomethane': 'halogenated',
        '1,1,3,3-tetramethylurea': 'amides',
        '1,2,4-trimethylbenzene': 'hydrocarbons',
        '3-chloropyridine': 'amines',
        '1,2,4-trichlorobenzene': 'halogenated',
        '1-decanol': 'alcohols',
        'methanol': 'alcohols',
        'methacrylic acid': 'acids',
        '3-methyl-1-pentanol': 'alcohols',
        '1-phenyl-1-propanone': 'carbonyls',
        '2-chlorobutane': 'hydrocarbons',
        '1,2-dichloroethylene': 'halogenated',
        '2-heptanol': 'alcohols',
        'cyclopentanone': 'carbonyls',
        'anisole': 'ethers',
        "2'-chloroacetophenone": 'carbonyls',
        'propylene oxide': 'ethers',
        '2-ethylpyridine': 'amines',
        'n,n-dimethylphenylglyoxylamide': 'amides',
        '2-cyclohexen-1-one': 'carbonyls',
        'methylquinoline': 'amines',
        'propiolic acid': 'acids',
        '1,3-dimethyl-2-imidazolidinone': 'amides',
        'isopropyl alcohol': 'alcohols',
        'acrylonitrile': 'nitriles',
        'benzenemethanol, 2-fluoro-': 'alcohols',
        'benzonitrile': 'nitriles',
        'salicylaldehyde': 'carbonyls',
        '1-(3-fluorophenyl)ethanol': 'alcohols',
        'isobutylbenzene': 'hydrocarbons',
        'benzyl bromide': 'halogenated',
        '1-phenyl-1-propanol': 'alcohols',
        'propylamine': 'amines',
        '2,6-dimethylaniline': 'amines',
        'm-cresol': 'alcohols',
        '2-methylhexan-1-ol': 'alcohols',
        '1,3-dioxane': 'ethers',
        '2,3-butanediol': 'alcohols',
        '3,4-lutidine': 'amines',
        '1-tetralone': 'carbonyls',
        'ethynylbenzene': 'hydrocarbons',
        'isobutyrophenone': 'carbonyls',
        '2,5-hexanedione': 'carbonyls',
        'butylbenzene': 'hydrocarbons',
        'guaiacol': 'alcohols',
        'diglyme': 'ethers',
        '4-bromotoluene': 'halogenated',
        'perchloric acid': 'acids',
        '1-pentanol': 'alcohols',
        '3-methylpyridine': 'amines',
        'pentafluoropyridine': 'amines',
        '1,4-dimethylpiperazine': 'amines',
        '2-methylheptane': 'hydrocarbons',
        'isoamyl acetate': 'esters',
        '2-iodobutane': 'hydrocarbons',
        'lutidine': 'amines',
        'nitroethane': 'special',
        '2-methylanisole': 'ethers',
        'butyl benzoate': 'esters',
        '3,5-lutidine': 'amines',
        '1,1-dichloroethane': 'halogenated',
        '2-hydroxypyridine': 'amines',
        'triacetin': 'esters',
        'decane': 'hydrocarbons',
        '3-butyn-2-ol': 'alcohols',
        'sec-butyl acetate': 'esters',
        'benzotrifluoride': 'halogenated',
        'trimethyl benzene-1,3,5-tricarboxylate': 'esters',
        '1,4-dioxane': 'ethers',
        'propylene carbonate': 'esters',
        '3-methyl-2-pentanone': 'carbonyls',
        'hexyl benzoate': 'esters',
        'methyl acetate': 'esters',
        '4-chlorophenol': 'alcohols',
        '2-chloro-1-phenylethanol': 'alcohols',
        '3-fluorobenzyl alcohol': 'alcohols',
        '1,2-dibromobenzene': 'halogenated',
        'n-ethylaniline': 'amines',
        'pentafluorobenzene': 'halogenated',
        'bromocyclohexane': 'hydrocarbons',
        '3-bromophenol': 'alcohols',
        'benzyl formate': 'esters',
        'diethylene glycol monoethyl ether': 'alcohols',
        'diphenylmethane': 'hydrocarbons',
        '2-chlorophenol': 'alcohols',
        '3-hexanol': 'alcohols',
        'fluorobenzene': 'halogenated',
        'phenol': 'alcohols',
        '1,2-dimethoxybenzene': 'hydrocarbons',
        '1,3,5-trifluorobenzene': 'halogenated',
        'pentylbenzene': 'hydrocarbons',
        'cyclohexylbenzene': 'hydrocarbons',
        '4-methylcyclohexanone': 'carbonyls',
        'diethyl acetate': 'esters',
        'ethylamine': 'amines',
        '1,2-dichloroethane': 'halogenated',
        'thiomorpholine': 'amines',
        '2-methyl-3-pentanol': 'alcohols',
        'dicyclopentadiene': 'hydrocarbons',
        '6-carbethoxy-2,2,6-trimethylcyclohexanone': 'carbonyls',
        'propyl benzoate': 'esters',
        'nitrobenzene': 'special',
        '5-nonanol': 'alcohols',
        'm-xylene': 'hydrocarbons',
        'benzyl alcohol': 'alcohols',
        '2,5-dimethylpyrazine': 'amines',
        'benzyl chloride': 'halogenated',
        '3-phenylprop-2-enenitrile': 'nitriles',
        'triethylamine': 'amines',
        'isoamyl benzoate': 'esters',
        '3,4-difluoroaniline': 'amines',
        'decahydroisoquinoline': 'amines',
        'n,n′-dimethylpropyleneurea': 'amides',
        'chlorocyclohexane': 'hydrocarbons',
        'n,n-diethylphenylglyoxylamide': 'amides',
        '2-amino-3-methylpyridine': 'amines',
        'tetrahydrofuran': 'ethers',
        'sec-butyl methyl ether': 'ethers',
        '3-phenylbutan-2-one': 'carbonyls',
        '2-ethyl-1-butanol': 'alcohols',
        'chloromethane': 'halogenated',
        'dibromomethane': 'halogenated',
        'acetic anhydride': 'special',
        '3,5-dimethylaniline': 'amines',
        '1,2-dibromoethane': 'halogenated',
        '2-methylbutanoic acid': 'acids',
        'ethyl 2-oxocyclohexanecarboxylate': 'esters',
        '1-phenylpropan-1-amine': 'amines',
        'n-isopropylmethylamine': 'amines',
        'xylene': 'hydrocarbons',
        '1,3-diphenylacetone': 'carbonyls',
        'diethylamine': 'amines',
        'tetramethoxysilane': 'special',
        'cyclohexane': 'hydrocarbons',
        'octafluoronaphthalene': 'halogenated',
        'cumene': 'hydrocarbons',
        'ethyl benzoate': 'esters',
        '2-chloroanisole': 'ethers',
        '1,3-dioxolane': 'ethers',
        '2,2,2-trifluoroethanol': 'alcohols',
        'p-fluorobenzyl alcohol': 'alcohols',
        '1,3-dimethoxybenzene': 'hydrocarbons',
        'p-cresol': 'alcohols',
        'cycloheptanone': 'carbonyls',
        'tripropylamine': 'amines',
        '5-decanol': 'alcohols',
        'tert-butyl methyl ether': 'ethers',
        'ethylenediamine': 'amines',
        'furan': 'ethers',
        'n,n-dimethylacetamide': 'amides',
        'hexane': 'hydrocarbons',
        'isopropyl acetate': 'esters',
        'n,n-diethylformamide': 'amides',
        '3-chloroaniline': 'amines',
        '2-methyl-2-butanol': 'alcohols',
        'o-cresol': 'alcohols',
        '1,2-dimethoxyethane': 'ethers',
        'cyclodecane': 'hydrocarbons',
        'pyrrolidine': 'amines',
        '2-allyl hexafluoroisopropanol': 'alcohols',
        '2,5-dimethylcyclohexan-1-ol': 'alcohols',
        'hexylbenzene': 'hydrocarbons',
        'bromotrichloromethane': 'halogenated',
        '3,3-dimethyl-2-butanol': 'alcohols',
        '1-methylnaphthalene': 'hydrocarbons',
        '3-pentanol': 'alcohols',
        'methyl isonicotinate': 'esters',
        'lactic acid': 'acids',
        'nitric acid': 'acids',
        '1,4-dichlorobenzene': 'halogenated',
        'p-xylene': 'hydrocarbons',
        'phenetole': 'ethers',
        'diisopropyl ether': 'ethers',
        'dimethyl sulfide': 'sulfur',
        'ethidium bromide': 'special',
        'methyl phenylacetate': 'esters',
        'aniline': 'amines',
        'diazabicycloundecene': 'amines',
        'dichloromethane': 'halogenated',
        'cyclooctane': 'hydrocarbons',
        'ammonia': 'special',
        'sulfur tetrafluoride': 'special',
        '1-methoxy-2-propanol': 'alcohols',
        'trichloroethylene': 'halogenated',
        'decahydronaphthalene': 'hydrocarbons',
        'cyclooctanamine': 'amines',
        'propionitrile': 'nitriles',
        'valeric acid': 'acids',
        '2,4-lutidine': 'amines',
        'sulfur dioxide': 'special',
        '2-bromobutane': 'hydrocarbons',
        '2-methyl-1-pentanol': 'alcohols',
        '3-methoxytoluene': 'hydrocarbons',
        'iodobenzene': 'halogenated',
        'phenyl propionate': 'esters',
        'gamma-butyrolactone': 'esters',
        'methyl propionate': 'esters',
        '2-hexanone': 'carbonyls',
        '3-pentanone': 'carbonyls',
        '3-methyl-3-pentanol': 'alcohols',
        '2-methylcyclopentanone': 'carbonyls',
        '3-octanol': 'alcohols',
        'formic acid': 'acids',
        '1,1,1,2-tetrachloroethane': 'halogenated',
        '2-methylpyridine': 'amines',
        '4-methylcyclohexanol': 'alcohols',
        '1-chlorobutane': 'hydrocarbons',
        'n-methylaniline': 'amines',
        '3-methyl-2-butanol': 'alcohols',
        'acrylic acid': 'acids',
        '1-(4-chlorophenyl)ethanol': 'alcohols',
        'butyric acid': 'acids',
        'hydrazine hydrate': 'amines',
        'indene': 'hydrocarbons',
        'valerophenone': 'carbonyls',
        'benzyl phenyl ether': 'ethers',
        'trichloracetonitrile': 'nitriles',
        'hydrochloric acid': 'acids',
        'benzyl propionate': 'esters',
        'dimethylnaphthalene': 'hydrocarbons',
        'formylhydrazine': 'amines',
        '2-methylcyclohexanone': 'carbonyls',
        'hexafluoroisopropanol': 'alcohols',
        'ethyl methyl carbonate': 'esters',
        'menthone': 'carbonyls',
        'butyrophenone': 'carbonyls',
        'lactonitrile': 'nitriles',
        '2-methoxyethanol': 'alcohols',
        'sulfuric acid': 'acids',
        'benzyl methacrylate': 'esters',
        'cyclopentanol': 'alcohols',
        'diethyl ether': 'ethers',
        '1,2,3-trifluorobenzene': 'halogenated',
        '2-morpholinoethanol': 'alcohols',
        'cyclohexanone': 'carbonyls',
        'propylene glycol': 'alcohols',
        'n-methylacetamide': 'amides',
        'chloropicrin': 'halogenated',
        'formaldehyde': 'carbonyls',
        'acetonitrile': 'nitriles',
        'propyl acetate': 'esters',
        'isobutyl benzoate': 'esters',
        'methylpyridine': 'amines',
        '3-(1-methylpyrrolidin-2-yl)pyridine': 'amines',
        'butyl ether': 'ethers',
        'octanoic acid': 'acids',
        '4-methylcyclohexylamine': 'amines',
        'cyclohexanamine': 'amines',
        '2-ethylpiperidine': 'amines',
        '3-buten-2-ol': 'alcohols'},
    'description_of_holes_categories': {
        'sealed': 'no holes',
        'no holes': 'no holes',
        'loosely sealed tubes': 'loosely closed',
        'loosely closed': 'loosely closed',
        'slightly open': 'loosely closed',
        'loosely capped': 'loosely closed',
        'partially covered': 'loosely closed',
        'a small hole': 'single hole',
        'small hole': 'single hole',
        'one small hole': 'single hole',
        'a very small hole': 'single hole',
        '1-mm hole': 'single hole',
        '1 pinhole': 'single hole',
        'pinhole': 'single hole',
        'pin hole': 'single hole',
        'evaporation through the needle': 'single hole',
        'placed off center to the vial’s opening': 'single hole',
        'single hole': 'single hole',
        'two small holes': 'few holes',
        'small holes': 'few holes',
        'a few holes': 'few holes',
        'few holes': 'few holes',
        'some holes': 'few holes',
        'several holes': 'few holes',
        'few pinholes': 'few holes',
        'few small holes': 'few holes',
        'a few small holes': 'few holes',
        'some small holes': 'few holes',
        'several small holes': 'few holes',
        'few tiny holes': 'few holes',
        '2–3 holes': 'few holes',
        '3–5 holes': 'few holes',
        '3 pinholes': 'few holes',
        'three pinholes': 'few holes',
        '5 holes': 'few holes',
        '5 pinholes': 'few holes',
        'five perforations': 'few holes',
        'four to ﬁve small holes': 'few holes',
        'four to five small holes': 'few holes',
        'three small holes (1 mm diameter each)': 'few holes',
        'three single small holes were pricked using a needle': 'few holes',
        'a couple of small holes were then pricked with a needle': 'few holes',
        'perforated with a needle': 'few holes',
        'pierced with a needle': 'few holes',
        'needle-pierced': 'few holes',
        'Holes were pierced': 'few holes',
        'few small holes pierced': 'few holes',
        'eight holes': 'few holes',
        'perforated': 'few holes',
        'pinholes': 'few holes',
        'pinhole/s': 'few holes',
        'pin holed': 'few holes',
        'pierced': 'few holes',
        'pierced lid': 'few holes',
        'punched holes': 'few holes',
        'bored holes': 'few holes',     
        'holes': 'few holes',     
        'several small apertures': 'few holes',
        'needle in the cap': 'needle vent',
        'needle vent': 'needle vent'},
    "covering_method_categories": {
        "open setup": "open setup",
        "open air": "open setup",
        "open vessel": "open setup",
        "open container": "open setup",
        "open to the ambient atmosphere": "open setup",
        "open to air": "open setup",
        "open to the atmosphere": "open setup",
        "open": "open setup",
        "open flask": "open setup",
        "open vial": "open setup",
        "uncovered": "open setup",
        "uncovered vial": "open setup",
        "uncapped": "open setup",
        "opened snap-on glass": "open setup",
        "open vial closed in a cylindrical bottle": "open setup",
        "parafilm": "parafilm",
        "Parafilm": "parafilm",
        "parafilm": "parafilm",
        "Parafilm™": "parafilm",
        "Parafilm®": "parafilm",
        "paraﬁlm": "parafilm",
        "Paraﬁlm2": "parafilm",
        "paraffin film": "parafilm",
        "parafirm": "parafilm",
        "perforated parafilm": "parafilm",
        "seal film": "parafilm",
        "sealing film": "parafilm",
        "perforated sealing film": "parafilm",
        "perforated seal film": "parafilm",
        "plastic sheet": "plastic sheet",
        "polythene sheet": "plastic sheet",
        "thick polythene sheet": "plastic sheet",
        "transparent polythene paper": "plastic sheet",
        "plastic wrap": "plastic sheet",
        "perforated polythene sheet": "plastic sheet",
        "tiny holed polyethene paper": "plastic sheet",
        "perforated sheet": "plastic sheet",
        "aluminum foil": "aluminum foil",
        "aluminium foil": "aluminum foil",
        "aluminum foil": "aluminum foil",
        "foil": "aluminum foil",
        "Folie": "aluminum foil",
        "tinfoil paper": "aluminum foil",
        "pin-holed aluminium foil": "aluminum foil",
        "paper": "paper",
        "filter paper": "paper",
        "4 sheets of gauze and a piece of filter paper": "paper",
        "Glasrohr aufgesetzt, die Engstelle mit mehreren Filterpapieren verschlossen": "paper",
        "oil": "oil",
        "cylindrical bottle containing paraffin oil": "oil",
        "liquid paraffin": "oil",
        "mineral oil": "oil",
        "vaseline oil": "oil",
        "cylindrical bottle containing vaseline oil": "oil",
        "septum": "septum",
        "serum cap": "septum",
        "septum capped tube": "septum",
        "Screw caps lined with rubber": "septum",
        "screw caps and polytetraﬂuoroethylene-coated rubber septa": "septum",
        "cap": "cap",
        "sealed in a vial": "cap",
        "sealed container": "cap",
        "sealed": "cap",
        "sealed vessel": "cap",
        "sealed vial": "cap",
        "sealed bottles": "cap",
        "sealed vials": "cap",
        "sealed tube": "cap",
        "sealed test tube": "cap",
        "sealed micro tubes": "cap",
        "sealed flask": "cap",
        "sealed glass vial": "cap",
        "sealed glass desiccator": "cap",
        "sealed solution": "cap",
        "sealed in a chamber": "cap",
        "tightly sealed glass vessel": "cap",
        "closed": "cap",
        "closed vial": "cap",
        "closed vials": "cap",
        "closed glass vial": "cap",
        "closed vessel": "cap",
        "closed container": "cap",
        "closed flask": "cap",
        "closed system": "cap",
        "vial was closed": "cap",
        "optimally closed": "cap",
        "capped": "cap",
        "capped vial": "cap",
        "capped 20-mL vial": "cap",
        "tightly capped": "cap",
        "tightly caped glass vials": "cap",
        "tightly closed vial": "cap",
        "loosely capped": "cap",
        "loosely capped vial": "cap",
        "loosely capped 25-mL round-bottomed flask": "cap",
        "loosely capped 1-dram screw-top vial inside a loosely capped 10 inch vial": "cap",
        "capped loosely": "cap",
        "screw cap": "cap",
        "screwcap": "cap",
        "screw cap vial": "cap",
        "screw-top glass vial lid": "cap",
        "screw shutter": "cap",
        "plastic cap": "cap",
        "vial cap": "cap",
        "lid": "cap",
        "lid of the vial": "cap",
        "cap of the vial": "cap",
        "cap turned upside down": "cap",
        "loosely closed lid": "cap",
        "loosely closed vial lid": "cap",
        "lid resting on top of the vial": "cap",
        "lid resting loosely": "cap",
        "lids resting loosely on top of the vials": "cap",
        "loosely fitted weighing cup": "cap",
        "cover": "cap",
        "covered": "cap",
        "covered Dewar flask": "cap",
        "corked Dewar flask": "cap",
        "loosely covered": "cap",
        "partially covered": "cap",
        "partial covering": "cap",
        "partially covered vessels": "cap",
        "partially-tightened/covered vial": "cap",
        "glass stopper": "cap",
        "watchglass resting on top of the beaker": "cap",
        "desiccator": "cap",
        "desiccator with P2O5": "cap",
        "glass capillaries": "cap",
        "capillary": "cap",
        "borosilicate glass capillary": "cap",
        "glass vials": "cap",
        "vial": "cap",
        "vials": "cap",
        "Teflon seal": "cap",
        "Teflon-coated crimp top": "cap",
        "Teflon-lined autoclave": "cap",
        "PTFE-lined autoclave": "cap",
        "Teﬂon-lined stainless steel autoclave": "cap",
        "Teflon-lined stainless steel autoclave": "cap",
        "Teflon-lined stainless steel vessel": "cap",
        "sealed Teflon-lined stainless steel vessel": "cap",
        "Teflon-lined reactor": "cap",
        "Teflon-lined stainless-steel reactor": "cap",
        "Teﬂon-lined acid digestion bomb": "cap",
        "stainless steel vessel": "cap",
        "sealed reactor": "cap",
        "lid with a small hole in it": "cap",
        "perforated lid": "cap",
        "perforated cap": "cap",
        "pierced lid": "cap",
        "vial with pierced lid": "cap",
        "speziell angefertigten Glasaufsatz": "cap",
        "dry nitrogen atmosphere": "cap",
        "nitrogen atmosphere": "cap",
        "polysiloxane lid": "cap"}
        }
