METHODS = [
    "grinding",
    "slurry",
    "solution_crystallization",
    "antisolvent",
    "laser_irradiation",
    "ultrasound",
]
 
METHODS_SMALL = [
    "freeze_drying",
    "hot_melt_extrusion",
    "resonant_acoustic",
    "spray_drying",
]
 
NO_VALUE = "NO_VALUE"
MISSING_MARKER = "NOT_DETECTED"
SMILES_COLS = ["API", "Coformer"]
NECESSARY_COLS = ["API", "Coformer"]
RATIO_COLS = ["Part of Ratio API", "Part of Ratio Coformer"]
 
NUMERIC_COLS = {
    "grinding": [
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount of Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
        "Mixing Frequency",
        "Mixing Time",
        "Mixing Temperature",
        "Drying Time",
        "Drying Temperature",
    ],
    "slurry": [
        "Amount of API",
        "Amount of Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
        "Mixing Temperature",
        "Mixing Time",
        "Evaporation Temperature",
        "Evaporation Time",
        "Drying Temperature",
        "Drying Time",
    ],
    "solution_crystallization": [
        "Amount of API",
        "Amount of Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
        "Mixing Temperature",
        "Mixing Time",
        "Time of Cooling or Evaporation",
    ],
    "antisolvent": [
        "Amount of API",
        "Amount of Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of Solvent",
        "Amount of Anti-solvent",
        "Speed of Addition",
        "Mixing Frequency",
        "Mixing Temperature",
        "Drying Temperature",
    ],
    "laser_irradiation": [
        "Amount of API",
        "Amount of Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
        "Focal Length",
        "Power",
        "Raster Speed",
        "Drying Temperature",
        "Drying Time",
    ],
    "ultrasound": [
        "Amount of API",
        "Amount of Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
        "Sonication Time",
        "Mixing Frequency",
        "Mixing Temperature",
        "Power",
        "Drying Temperature",
        "Drying Time",
    ],
}
 
NUMERIC_COLS_FILL = {
    "grinding": NUMERIC_COLS["grinding"],
    "slurry": NUMERIC_COLS["slurry"],
    "solution_crystallization": NUMERIC_COLS["solution_crystallization"],
    "antisolvent": NUMERIC_COLS["antisolvent"],
    "laser_irradiation": NUMERIC_COLS["laser_irradiation"],
    "ultrasound": NUMERIC_COLS["ultrasound"],
}
 
PARAMETERS_RANGES = {
    "grinding": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 200},
        "Amount of Second Solvent": {"min": 0, "max": 200},
        "Amount of Third Solvent": {"min": 0, "max": 200},
        "Mixing Frequency": {"min": 0},
        "Mixing Time": {"min": 0, "max": 10080},
        "Mixing Temperature": {"min": -100, "max": 120},
        "Drying Time": {"min": 0, "max": 2880},
        "Drying Temperature": {"min": 0, "max": 120},
    },
    "slurry": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 1200},
        "Amount of Second Solvent": {"min": 0, "max": 1200},
        "Amount of Third Solvent": {"min": 0, "max": 1200},
        "Mixing Temperature": {"min": -100, "max": 120},
        "Mixing Time": {"min": 0, "max": 10080},
        "Evaporation Temperature": {"min": 0, "max": 250},
        "Evaporation Time": {"min": 0, "max": 10080},
        "Drying Temperature": {"min": 0, "max": 250},
        "Drying Time": {"min": 0, "max": 2880},
    },
    "solution_crystallization": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 6000},
        "Amount of Second Solvent": {"min": 0, "max": 6000},
        "Amount of Third Solvent": {"min": 0, "max": 6000},
        "Mixing Temperature": {"min": -100, "max": 250},
        "Mixing Time": {"min": 0, "max": 20160},
        "Time of Cooling or Evaporation": {"min": 0, "max": 60480},
    },
    "antisolvent": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 6000},
        "Amount of Anti-solvent": {"min": 0, "max": 6000},
        "Speed of Addition": {"min": 0, "max": 1000},
        "Mixing Frequency": {"min": 0},
        "Mixing Temperature": {"min": -100, "max": 250},
        "Drying Temperature": {"min": 0, "max": 250},
    },
    "laser_irradiation": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 200},
        "Amount of Second Solvent": {"min": 0, "max": 200},
        "Amount of Third Solvent": {"min": 0, "max": 200},
        "Focal Length": {"min": 0},
        "Power": {"min": 0},
        "Raster Speed": {"min": 0},
        "Drying Temperature": {"min": 0, "max": 250},
        "Drying Time": {"min": 0, "max": 2880},
    },
    "ultrasound": {
        "Amount of API": {"min": 0, "max": 10000},
        "Amount of Coformer": {"min": 0, "max": 10000},
        "Amount of Solvent": {"min": 0, "max": 6000},
        "Amount of Second Solvent": {"min": 0, "max": 6000},
        "Amount of Third Solvent": {"min": 0, "max": 6000},
        "Sonication Time": {"min": 0, "max": 2880},
        "Mixing Frequency": {"min": 0},
        "Mixing Temperature": {"min": -100, "max": 10000},
        "Power": {"min": 0},
        "Drying Temperature": {"min": 0, "max": 250},
        "Drying Time": {"min": 0, "max": 2880},
    },
}
 
ROUNDING_STEPS = {
    "Amount of API": 0.1,  # mg
    "Amount of Coformer": 0.1,  # mg
    "Amount of Solvent": 0.01,  # mL
    "Amount of Second Solvent": 0.01,  # mL
    "Amount of Third Solvent": 0.01,  # mL
    "Amount of Anti-solvent": 0.01,  # mL
    "Drying Temperature": 1.0,  # °C
    "Evaporation Temperature": 1.0,  # °C
    "Mixing Temperature": 1.0,  # °C
    "Drying Time": 1.0,  # min
    "Evaporation Time": 1.0,  # min
    "Mixing Time": 1.0,  # min
    "Sonication Time": 1.0,  # min
    "Time of Cooling or Evaporation": 1.0,  # min
    "Focal Length": 1.0,  # mm
    "Mixing Frequency": 1.0,  # Hz
    "Power": 1.0,  # W
    "Raster Speed": 0.1,  # mm/s
    "Speed of Addition": 0.1,  # mL/min
    "Part of Ratio API": 1.0,  # integer parts
    "Part of Ratio Coformer": 1.0,  # integer parts
}
 
STRING_COLS = {
    "grinding": [
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Apparatus",
        "Frequency Unit",
        "Mixing Time Unit",
        "Mixing Temperature Unit",
        "Drying Time Unit",
        "Drying Temperature Unit",
    ],
    "slurry": [
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Time Unit",
        "Mixing Temperature Unit",
        "Evaporation Time Unit",
        "Evaporation Temperature Unit",
        "Drying Time Unit",
        "Drying Temperature Unit",
    ],
    "solution_crystallization": [
        "Type of Synthesis",
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Temperature Unit",
        "Mixing Time Unit",
        "Covering Method",
        "Description of Holes",
        "Time of Cooling or Evaporation Unit",
    ],
    "antisolvent": [
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Anti-solvent",
        "Anti-solvent Amount Unit",
        "Speed of Addition Unit",
        "Frequency Unit",
        "Mixing Temperature Unit",
        "Drying Temperature Unit",
    ],
    "laser_irradiation": [
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Third Solvent Amount Unit",
        "Foil Material",
        "Laser Apparatus",
        "Focal Length Unit",
        "Power Unit",
        "Raster Speed Unit",
        "Drying Temperature Unit",
        "Drying Time Unit",
    ],
    "ultrasound": [
        "Amount Unit of API",
        "Amount Unit of Coformer",
        "Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Third Solvent Amount Unit",
        "Sonication Time Unit",
        "Ultrasonic Apparatus",
        "Mixing Frequency Unit",
        "Mixing Temperature Unit",
        "Power Unit",
        "Drying Temperature Unit",
        "Drying Time Unit",
    ],
}
 
 
STRING_COLS_FILL = {
    "grinding": ["Solvent", "Mixing Apparatus"],
    "slurry": ["Solvent"],
    "solution_crystallization": ["Solvent", "Covering Method", "Description of Holes"],
    "antisolvent": ["Solvent", "Anti-solvent"],
    "laser_irradiation": ["Solvent", "Foil Material", "Laser Apparatus"],
    "ultrasound": ["Solvent", "Ultrasonic Apparatus"],
}
 
 
SOLVENT_COLS = {
    "grinding": ["Solvent", "Second Solvent", "Third Solvent"],
    "slurry": ["Solvent", "Second Solvent", "Third Solvent"],
    "solution_crystallization": ["Solvent", "Second Solvent", "Third Solvent"],
    "antisolvent": ["Solvent", "Anti-solvent"],
    "laser_irradiation": ["Solvent", "Second Solvent", "Third Solvent"],
    "ultrasound": ["Solvent", "Second Solvent", "Third Solvent"],
}
 
 
APPARATUS_COLS = {
    "grinding": ["Mixing Apparatus", "Mixing Frequency", "Frequency Unit"],
    "slurry": [],
    "solution_crystallization": [],
    "antisolvent": [],
    "laser_irradiation": [],
    "ultrasound": ["Ultrasonic Apparatus"],
}
 
 
COVERING_AND_HOLES_COLS = {
    "grinding": [],
    "slurry": [],
    "solution_crystallization": ["Covering Method", "Description of Holes"],
    "antisolvent": [],
    "laser_irradiation": [],
    "ultrasound": [],
}
 
 
REPLACE_COLS = {
    "grinding": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Second Solvent Amount Unit": "Solvent Amount Unit",
        "Third Solvent Amount Unit": "Solvent Amount Unit",
        "Drying Temperature": "Temperature of Drying",
        "Drying Time": "Time of Drying",
    },
    "slurry": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Amount of Solvent": "Volume of Solvent",
        "Solvent Amount Unit": "Solvent Volume Unit",
        "Second Solvent Amount Unit": "Solvent Volume Unit",
        "Third Solvent Amount Unit": "Solvent Volume Unit",
    },
    "solution_crystallization": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Second Solvent Amount Unit": "Solvent Amount Unit",
        "Third Solvent Amount Unit": "Solvent Amount Unit",
        "Mixing Temperature": "Stirring Temperature",
        "Mixing Temperature Unit": "Temperature Unit",
        "Mixing Time": "Stirring Time",
        "Mixing Time Unit": "Stirring Time Unit",
    },
    "antisolvent": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
    },
    "laser_irradiation": {
        "Amount of API": "API Amount",
        "Amount Unit of API": "Amount Unit",
        "Amount of Coformer": "Coformer Amount",
        "Amount Unit of Coformer": "Amount Unit",
        "Solvent Amount Unit": "Amount of Solvent Unit",
        "Second Solvent Amount Unit": "Amount of Solvent Unit",
        "Third Solvent Amount Unit": "Amount of Solvent Unit",
    },
    "ultrasound": {
        "Amount of API": "API Amount",
        "Amount Unit of API": "Amount Unit",
        "Amount of Coformer": "Coformer Amount",
        "Amount Unit of Coformer": "Amount Unit",
        "Second Solvent Amount Unit": "Solvent Amount Unit",
        "Third Solvent Amount Unit": "Solvent Amount Unit",
        "Mixing Temperature": "Temperature",
        "Mixing Temperature Unit": "Temperature Unit",
        "Mixing Frequency": "Frequency",
        "Mixing Frequency Unit": "Frequency Unit",
        "Power": "Maximum Power Output",
        "Power Unit": "Maximum Power Output Unit",
    },
    "freeze_drying": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Second Solvent Amount Unit": "Solvent Amount Unit",
        "Third Solvent Amount Unit": "Solvent Amount Unit",
    },
    "hot_melt_extrusion": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
    },
    "resonant_acoustic": {
        "Amount of API": "API Amount",
        "Amount of Coformer": "Coformer Amount",
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Solvent Amount Unit": "Amount of Solvent Unit",
        "Second Solvent Amount Unit": "Amount of Solvent Unit",
        "Third Solvent Amount Unit": "Amount of Solvent Unit",
    },
    "spray_drying": {
        "Amount Unit of API": "Amount Unit",
        "Amount Unit of Coformer": "Amount Unit",
        "Second Solvent Amount Unit": "Solvent Amount Unit",
        "Third Solvent Amount Unit": "Solvent Amount Unit",
    },
}
 
 
REMOVE_UNIT_COLS = {
    "grinding": [
        "Amount Unit",
        "Temperature of Drying (numeric)",
        "Temperature of Drying",
        "Time of Drying",
    ],
    "slurry": ["Amount Unit", "Solvent Volume Unit", "Volume of Solvent"],
    "solution_crystallization": [
        "Amount Unit",
        "Time of Evaporation Unit",
        "Stirring Temperature",
        "Temperature Unit",
        "Stirring Time",
        "Stirring Time Unit",
    ],
    "antisolvent": ["Amount Unit"],
    "laser_irradiation": [
        "API Amount",
        "Amount Unit",
        "Coformer Amount",
        "Amount of Solvent Unit",
    ],
    "ultrasound": [
        "API Amount",
        "Coformer Amount",
        "Amount Unit",
        "Temperature",
        "Temperature Unit",
        "Frequency",
        "Frequency Unit",
        "Maximum Power Output",
        "Maximum Power Output Unit",
    ],
    "freeze_drying": ["Amount Unit"],
    "hot_melt_extrusion": ["Amount Unit"],
    "resonant_acoustic": ["API Amount", "Coformer Amount", "Amount Unit"],
    "spray_drying": ["Amount Unit"],
}
 
 
UNIT_DEPENDENCIES = {
    "Amount Unit of API": ["Amount of API", "API Amount"],
    "Amount Unit of Coformer": ["Amount of Coformer", "Coformer Amount"],
    "Solvent Amount Unit": ["Amount of Solvent", "Volume of Solvent", "Solvent Amount"],
    "Second Solvent Amount Unit": [
        "Second Solvent Amount",
        "Amount of Second Solvent",
        "Second Solvent Volume",
    ],
    "Third Solvent Amount Unit": [
        "Third Solvent Amount",
        "Amount of Third Solvent",
        "Third Solvent Volume",
    ],
}
 
 
UNIT_COLS = {
    "grinding": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Second Solvent", "Second Solvent Amount Unit"],
            ["Amount of Third Solvent", "Third Solvent Amount Unit"],
        ],
        "hz": [["Mixing Frequency", "Frequency Unit"]],
        "c": [
            ["Mixing Temperature", "Mixing Temperature Unit"],
            ["Drying Temperature", "Drying Temperature Unit"],
        ],
        "min": [
            ["Mixing Time", "Mixing Time Unit"],
            ["Drying Time", "Drying Time Unit"],
        ],
    },
    "slurry": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Second Solvent", "Second Solvent Amount Unit"],
            ["Amount of Third Solvent", "Third Solvent Amount Unit"],
        ],
        "c": [
            ["Mixing Temperature", "Mixing Temperature Unit"],
            ["Evaporation Temperature", "Evaporation Temperature Unit"],
            ["Drying Temperature", "Drying Temperature Unit"],
        ],
        "min": [
            ["Mixing Time", "Mixing Time Unit"],
            ["Evaporation Time", "Evaporation Time Unit"],
            ["Drying Time", "Drying Time Unit"],
        ],
    },
    "solution_crystallization": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Second Solvent", "Second Solvent Amount Unit"],
            ["Amount of Third Solvent", "Third Solvent Amount Unit"],
        ],
        "c": [
            ["Mixing Temperature", "Mixing Temperature Unit"],
        ],
        "min": [
            ["Mixing Time", "Mixing Time Unit"],
            ["Time of Cooling or Evaporation", "Time of Cooling or Evaporation Unit"],
        ],
    },
    "antisolvent": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Anti-solvent", "Anti-solvent Amount Unit"],
        ],
        "hz": [
            ["Mixing Frequency", "Frequency Unit"],
        ],
        "c": [
            ["Mixing Temperature", "Mixing Temperature Unit"],
            ["Drying Temperature", "Drying Temperature Unit"],
        ],
        "ml/min": [
            ["Speed of Addition", "Speed of Addition Unit"],
        ],
    },
    "laser_irradiation": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Second Solvent", "Second Solvent Amount Unit"],
            ["Amount of Third Solvent", "Third Solvent Amount Unit"],
        ],
        "c": [
            ["Drying Temperature", "Drying Temperature Unit"],
        ],
        "min": [
            ["Drying Time", "Drying Time Unit"],
        ],
        "mm": [
            ["Focal Length", "Focal Length Unit"],
        ],
        "w": [
            ["Power", "Power Unit"],
        ],
        "mm/s": [
            ["Raster Speed", "Raster Speed Unit"],
        ],
    },
    "ultrasound": {
        "mg": [
            ["API", "Amount of API", "Amount Unit of API"],
            ["Coformer", "Amount of Coformer", "Amount Unit of Coformer"],
        ],
        "ml": [
            ["Amount of Solvent", "Solvent Amount Unit"],
            ["Amount of Second Solvent", "Second Solvent Amount Unit"],
            ["Amount of Third Solvent", "Third Solvent Amount Unit"],
        ],
        "hz": [
            ["Mixing Frequency", "Mixing Frequency Unit"],
        ],
        "c": [
            ["Mixing Temperature", "Mixing Temperature Unit"],
            ["Drying Temperature", "Drying Temperature Unit"],
        ],
        "min": [
            ["Sonication Time", "Sonication Time Unit"],
            ["Drying Time", "Drying Time Unit"],
        ],
        "w": [
            ["Power", "Power Unit"],
        ],
    },
}
 
FINAL_COLS = {
    "grinding": [
        "ids",
        "doi",
        "Type of Synthesis",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Apparatus",
        "Mixing Frequency",
        "Frequency Unit",
        "Mixing Time",
        "Mixing Time Unit",
        "Mixing Temperature",
        "Mixing Temperature Unit",
        "Drying Time",
        "Drying Time Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
    ],
    "slurry": [
        "ids",
        "doi",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Temperature",
        "Mixing Temperature Unit",
        "Mixing Time",
        "Mixing Time Unit",
        "Evaporation Temperature",
        "Evaporation Temperature Unit",
        "Evaporation Time",
        "Evaporation Time Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
        "Drying Time",
        "Drying Time Unit",
    ],
    "solution_crystallization": [
        "ids",
        "doi",
        "Type of Synthesis",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Mixing Temperature",
        "Mixing Temperature Unit",
        "Mixing Time",
        "Mixing Time Unit",
        "Covering Method",
        "Description of Holes",
        "Time of Cooling or Evaporation",
        "Time of Cooling or Evaporation Unit",
    ],
    "antisolvent": [
        "ids",
        "doi",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Anti-solvent",
        "Amount of Anti-solvent",
        "Anti-solvent Amount Unit",
        "Speed of Addition",
        "Speed of Addition Unit",
        "Mixing Frequency",
        "Frequency Unit",
        "Mixing Temperature",
        "Mixing Temperature Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
    ],
    "laser_irradiation": [
        "ids",
        "doi",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Foil Material",
        "Laser Apparatus",
        "Focal Length",
        "Focal Length Unit",
        "Power",
        "Power Unit",
        "Raster Speed",
        "Raster Speed Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
        "Drying Time",
        "Drying Time Unit",
    ],
    "ultrasound": [
        "ids",
        "doi",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Ultrasonic Apparatus",
        "Mixing Frequency",
        "Mixing Frequency Unit",
        "Sonication Time",
        "Sonication Time Unit",
        "Mixing Temperature",
        "Mixing Temperature Unit",
        "Power",
        "Power Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
        "Drying Time",
        "Drying Time Unit",
    ],
    "freeze_drying": [
        "ids",
        "doi",
        "answer",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Freeze-Dryer Apparatus",
        "Freeze-Drying Temperature",
        "Freeze-Drying Temperature Unit",
        "Freeze-Drying Pressure",
        "Freeze-Drying Pressure Unit",
        "Cooling Temperature",
        "Cooling Temperature Unit",
    ],
    "hot_melt_extrusion": [
        "ids",
        "doi",
        "answer",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Additional Substance",
        "Amount of Additional Substance",
        "Amount of Additional Substance Unit",
        "Type of Extruder",
        "Screw Diameter",
        "Screw Diameter Unit",
        "L/D Ratio",
        "List of Screw Type",
        "Screw Speed",
        "Screw Speed Unit",
        "Amount of Types of Zones",
        "List of Types of Zones",
        "List of Temperature in Zones",
        "Temperature in Zones Unit",
        "Feed Rate",
        "Feed Rate Unit",
        "Batch Size",
        "Batch Size Unit",
        "Mixing Apparatus",
        "Mixing Time",
        "Mixing Time Unit",
        "Type of Die",
        "Die Diameter",
        "Die Diameter Unit",
    ],
    "resonant_acoustic": [
        "ids",
        "doi",
        "answer",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Reaction Time",
        "Reaction Time Unit",
        "Reaction Times of Gravity Acceleration",
        "Reaction Times of Gravity Acceleration Unit",
        "Reaction Frequency",
        "Reaction Frequency Unit",
        "Drying Temperature",
        "Drying Temperature Unit",
        "Drying Time",
        "Drying Time Unit",
    ],
    "spray_drying": [
        "ids",
        "doi",
        "answer",
        "Formula",
        "API",
        "Coformer",
        "Part of Ratio API",
        "Part of Ratio Coformer",
        "Amount of API",
        "Amount Unit of API",
        "Amount of Coformer",
        "Amount Unit of Coformer",
        "Solvent",
        "Amount of Solvent",
        "Solvent Amount Unit",
        "Second Solvent",
        "Amount of Second Solvent",
        "Second Solvent Amount Unit",
        "Third Solvent",
        "Amount of Third Solvent",
        "Third Solvent Amount Unit",
        "Spray Dryer Model",
        "Drying Gas",
        "Air Flow Speed",
        "Air Flow Unit",
        "Inlet Temperature",
        "Inlet Temperature Unit",
        "Aspiration Rate",
        "Aspiration Flow Rate",
        "Flow Rate Unit",
        "Feed Rate",
        "Feed Rate Unit",
        "Outlet Temperature",
        "Outlet Temperature Unit",
    ],
}
 
STANDART_VALUES = {
    "grinding": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 100.0,
        "Amount of Coformer": 100.0,
        "Amount of Solvent": 0.05,
        "Amount of Second Solvent": 0.05,
        "Amount of Third Solvent": 0.05,
        "Mixing Frequency": 30.0,
        "Mixing Time": 25.0,
        "Mixing Temperature": 25.0,
        "Drying Time": 720.0,
        "Drying Temperature": 45.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": "methanol",
        "Solvent Amount Unit": "ml",
        "Second Solvent Amount Unit": "ml",
        "Third Solvent Amount Unit": "ml",
        "Mixing Apparatus": "ball mill",
        "Frequency Unit": "hz",
        "Mixing Time Unit": "min",
        "Mixing Temperature Unit": "c",
        "Drying Time Unit": "min",
        "Drying Temperature Unit": "c",
    },
    "slurry": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 100.0,
        "Amount of Coformer": 100.0,
        "Amount of Solvent": 2.0,
        "Amount of Second Solvent": 2.0,
        "Amount of Third Solvent": 2.0,
        "Mixing Time": 1440.0,
        "Mixing Temperature": 25.0,
        "Evaporation Time": 1440.0,
        "Evaporation Temperature": 25.0,
        "Drying Time": 1440.0,
        "Drying Temperature": 50.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": "acetonitrile",
        "Solvent Amount Unit": "ml",
        "Second Solvent Amount Unit": "ml",
        "Third Solvent Amount Unit": "ml",
        "Mixing Time Unit": "min",
        "Mixing Temperature Unit": "c",
        "Evaporation Time Unit": "min",
        "Evaporation Temperature Unit": "c",
        "Drying Time Unit": "min",
        "Drying Temperature Unit": "c",
    },
    "solution_crystallization": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 100.0,
        "Amount of Coformer": 100.0,
        "Amount of Solvent": 5.0,
        "Amount of Second Solvent": 5.0,
        "Amount of Third Solvent": 5.0,
        "Mixing Temperature": 25.0,
        "Mixing Time": 120.0,
        "Time of Cooling or Evaporation": 1440.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": "methanol",
        "Solvent Amount Unit": "ml",
        "Second Solvent Amount Unit": "ml",
        "Third Solvent Amount Unit": "ml",
        "Covering Method": "no holes",
        "Description of Holes": "cap",
        "Mixing Temperature Unit": "c",
        "Mixing Time Unit": "min",
        "Time of Cooling or Evaporation Unit": "min",
    },
    "antisolvent": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 100.0,
        "Amount of Coformer": 100.0,
        "Amount of Solvent": 10.0,
        "Amount of Anti-solvent": 10.0,
        "Speed of Addition": 0.5,
        "Mixing Frequency": 30.0,
        "Mixing Temperature": 25.0,
        "Drying Temperature": 100.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": "methanol",
        "Solvent Amount Unit": "ml",
        "Anti-solvent": "hexane",
        "Anti-solvent Amount Unit": "ml",
        "Speed of Addition Unit": "ml/min",
        "Frequency Unit": "hz",
        "Mixing Temperature Unit": "c",
        "Drying Temperature Unit": "c",
    },
    "laser_irradiation": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 10.0,
        "Amount of Coformer": 10.0,
        "Amount of Solvent": 0.5,
        "Amount of Second Solvent": 0.5,
        "Amount of Third Solvent": 0.5,
        "Focal Length": 68.0,
        "Power": 40.0,
        "Raster Speed": 50.0,
        "Drying Time": 60.0,
        "Drying Temperature": 25.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": NO_VALUE,
        "Solvent Amount Unit": "ml",
        "Second Solvent Amount Unit": "ml",
        "Third Solvent Amount Unit": "ml",
        "Foil Material": "aluminum",
        "Laser Apparatus": "FS laser",
        "Focal Length Unit": "mm",
        "Power Unit": "w",
        "Raster Speed Unit": "mm/s",
        "Drying Time Unit": "min",
        "Drying Temperature Unit": "c",
    },
    "ultrasound": {
        "Part of Ratio API": 1.0,
        "Part of Ratio Coformer": 1.0,
        "Amount of API": 100.0,
        "Amount of Coformer": 100.0,
        "Amount of Solvent": 10.0,
        "Amount of Second Solvent": 10.0,
        "Amount of Third Solvent": 10.0,
        "Mixing Frequency": 40000.0,
        "Sonication Time": 30.0,
        "Mixing Temperature": 55.0,
        "Power": 100.0,
        "Drying Temperature": 25.0,
        "Drying Time": 1440.0,
        "Amount Unit of API": "mg",
        "Amount Unit of Coformer": "mg",
        "Solvent": "acetonitrile",
        "Solvent Amount Unit": "ml",
        "Second Solvent Amount Unit": "ml",
        "Third Solvent Amount Unit": "ml",
        "Ultrasonic Apparatus": "ultrasonic bath",
        "Mixing Frequency Unit": "hz",
        "Sonication Time Unit": "min",
        "Mixing Temperature Unit": "c",
        "Power Unit": "w",
        "Drying Temperature Unit": "c",
        "Drying Time Unit": "min",
    },
}
 
GROUP_LEVELS_CANDIDATES = {
    "default": [
        ["API", "Coformer"],
        ["API"],
        ["Coformer"],
    ]
}
 
 
NUMERIC_GROUP_LEVELS_CANDIDATES = {
    "default": {
        "default": [
            ["API", "Coformer"],
            ["API"],
            ["Coformer"],
        ],
 
        "amount": [
            ["API", "Coformer", "Part of Ratio API", "Part of Ratio Coformer"],
            ["API", "Coformer"],
            ["API"],
            ["Coformer"],
        ],
 
        "ratio": [
            ["API", "Coformer"],
            ["API"],
            ["Coformer"],
        ],
 
        "solvent": [
            ["API", "Coformer", "Solvent"],
            ["API", "Coformer", "Second Solvent"],
            ["API", "Coformer", "Third Solvent"],
            ["API", "Coformer", "Anti-solvent"],   
            ["API"],
            ["Coformer"],
        ],
 
        "mixing": [
            ["API", "Coformer", "Mixing Apparatus"],
            ["API", "Coformer"],
            ["API"],
            ["Coformer"],
        ],
 
        "thermal": [
            ["API", "Coformer", "Solvent"],
            ["API", "Coformer"],
            ["API"],
            ["Coformer"],
        ],
    },
}
 
NUMERIC_COL_GROUP = {
    # --- ratio / stoichiometry ---
    "Part of Ratio API": "ratio",
    "Part of Ratio Coformer": "ratio",
 
    # --- main amounts ---
    "Amount of API": "amount",
    "Amount of Coformer": "amount",
 
    # --- solvent amounts ---
    "Amount of Solvent": "solvent",
    "Amount of Second Solvent": "solvent",
    "Amount of Third Solvent": "solvent",
 
    # --- mixing related ---
    "Mixing Frequency": "mixing",
    "Mixing Time": "mixing",
    "Mixing Temperature": "mixing",
 
    # --- post-processing / thermal steps ---
    "Drying Time": "thermal",
    "Drying Temperature": "thermal",
    "Evaporation Time": "thermal",
    "Evaporation Temperature": "thermal",
    "Time of Cooling or Evaporation": "thermal",
}
 
 
 
SECOND_THIRD_SOLVENT_PAIRS = [
    ("Second Solvent", "Second Solvent Amount Unit", "Amount of Second Solvent"),
    ("Third Solvent", "Third Solvent Amount Unit", "Amount of Third Solvent"),
]
 
SECOND_AMOUNT_PREV = "Amount of Solvent"
THIRD_AMOUNT_PREV = "Amount of Second Solvent"
 
METHOD_TEMPLATES = {
    "grinding": " ".join([
        "Mechanochemical synthesis was carried out using a [Mixing Apparatus].",
        "The mixture was processed at [Mixing Frequency] [Frequency Unit] for [Mixing Time] [Mixing Time Unit] at [Mixing Temperature] [Mixing Temperature Unit].",
        "A blend of [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] was prepared in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "Additionally, [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent] were added.",
        "The mixture was then ground.",
        "The resulting co-crystal was dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    "hot_melt_extrusion": " ".join([
        "Hot-melt extrusion was performed using a [Type of Extruder] with a screw diameter of [Screw Diameter] [Screw Diameter Unit] and an L/D ratio of [L/D Ratio].",
        "[Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] were weighed in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "[Amount of Additional Substance] [Amount of Additional Substance Unit] of [Additional Substance] was added, and the components were pre-mixed using a [Mixing Apparatus] for [Mixing Time] [Mixing Time Unit].",
        "The batch size was [Batch Size] [Batch Size Unit].",
        "The blend was fed into the extruder at [Feed Rate] [Feed Rate Unit].",
        "The extruder comprised [Amount of Types of Zones] zones ([List of Types of Zones]) with temperatures set to [List of Temperature in Zones] [Temperature in Zones Unit].",
        "The screw configuration ([List of Screw Type]) and screw speed ([Screw Speed] [Screw Speed Unit]) were selected according to the zone design.",
        "Extrusion was carried out using a [Type of Die] with a diameter of [Die Diameter] [Die Diameter Unit].",
        "The resulting co-crystal was pulverized using an agate mortar and pestle.",
    ]),
    "solution_crystallization": " ".join([
        "Solution crystallization was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were dissolved in [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The solution was stirred at [Mixing Temperature] [Mixing Temperature Unit] for [Mixing Time] [Mixing Time Unit].",
        "The resulting solution was filtered and covered with [Covering Method] featuring [Description of Holes].",
        "The solution was then left at room temperature for [Time of Cooling or Evaporation] [Time of Cooling or Evaporation Unit].",
        "The resulting solid was collected by filtration and dried to obtain the co-crystal.",
    ]),
    "antisolvent": " ".join([
        "Anti-solvent crystallization was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were dissolved in [Amount of Solvent] [Solvent Amount Unit] of [Solvent].",
        "An anti-solvent stream containing [Amount of Anti-solvent] [Anti-solvent Amount Unit] of [Anti-solvent] was added to the solution at [Speed of Addition] [Speed of Addition Unit] using a peristaltic pump, while mixing at [Mixing Frequency] [Frequency Unit] and [Mixing Temperature] [Mixing Temperature Unit].",
        "The resulting suspension/solution was filtered and dried at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    "slurry": " ".join([
        "Slurry crystallization was conducted by suspending [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The solids were suspended in [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The suspension was stirred at [Mixing Temperature] [Mixing Temperature Unit] for [Mixing Time] [Mixing Time Unit].",
        "The solid product was separated by filtration, and residual solvent was evaporated at [Evaporation Temperature] [Evaporation Temperature Unit] for [Evaporation Time] [Evaporation Time Unit].",
        "The resulting co-crystal was dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    "freeze_drying": " ".join([
        "Freeze-drying co-crystal synthesis was performed using a [Freeze-Dryer Apparatus] at [Freeze-Drying Temperature] [Freeze-Drying Temperature Unit] and under [Freeze-Drying Pressure] [Freeze-Drying Pressure Unit].",
        "A mixture containing [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] was prepared in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were dissolved in [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The solution was then frozen at [Cooling Temperature] [Cooling Temperature Unit] and lyophilised to obtain the co-crystal.",
    ]),
    "spray_drying": " ".join([
        "Spray-drying was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were dissolved in [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The resulting solution was spray-dried using a [Spray Dryer Model] with [Drying Gas] as the drying gas.",
        "Processing conditions were: air flow [Air Flow Speed] [Air Flow Unit], inlet temperature [Inlet Temperature] [Inlet Temperature Unit], aspiration rate [Aspiration Rate]% ([Aspiration Flow Rate] [Flow Rate Unit]), and feed rate [Feed Rate] [Feed Rate Unit].",
        "The outlet temperature was [Outlet Temperature] [Outlet Temperature Unit].",
    ]),
    "ultrasound": " ".join([
        "Ultrasound-assisted synthesis was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were mixed with [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The mixture was sonicated for [Sonication Time] [Sonication Time Unit] using an [Ultrasonic Apparatus] operated at [Mixing Frequency] [Mixing Frequency Unit] and [Mixing Temperature] [Mixing Temperature Unit], with a power output of [Power] [Power Unit].",
        "The resulting solid was isolated by filtration and dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    "supercritical_fluid": " ".join([
        "Supercritical fluid synthesis was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were mixed with [Amount of Solvent] [Solvent Amount Unit] of [Solvent].",
        "The mixture was processed in a [Supercritical Apparatus] at [Pressure] [Pressure Unit] and [Mixing Temperature] [Mixing Temperature Unit], with a flow rate of [Flow Rate] [Flow Rate Unit].",
        "The resulting co-crystal was dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    "electrospray": " ".join([
        "Electrospraying synthesis was conducted using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were dissolved in [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent], and loaded into a [Syringe Volume] [Syringe Volume Unit] syringe.",
        "The prepared solution was electrosprayed using an [Electrospraying Apparatus].",
        "The flow rate, voltage, and needle tip-to-collector distance were set to [Flow Rate] [Flow Rate Unit], [Voltage] [Voltage Unit], and [Tip to Collector Distance] [Tip to Collector Distance Unit], respectively.",
        "The deposited co-crystal was collected on the collector and dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    # [Formula] -> (removed)
    # [API Amount] -> [Amount of API]
    # [Coformer Amount] -> [Amount of Coformer]
    # [Amount Unit] (API) -> [Amount Unit of API]
    # [Amount Unit] (Coformer) -> [Amount Unit of Coformer]
    # [Solvent Amount Unit] (2nd solvent) -> [Second Solvent Amount Unit]
    # [Solvent Amount Unit] (3rd solvent) -> [Third Solvent Amount Unit]
    # [Electronic Apparatus] -> [Electrospraying Apparatus]
    
    "resonant_acoustic": " ".join([
        "Resonant acoustic synthesis was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were combined with [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The reaction mixture was processed for [Reaction Time] [Reaction Time Unit] at [Reaction Times of Gravity Acceleration] [Reaction Times of Gravity Acceleration Unit] × g and a frequency of [Reaction Frequency] [Reaction Frequency Unit].",
        "The resulting co-crystal was dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
    # resonant acoustic changes
    # [Formula] -> (removed)
    # [API Amount] -> [Amount of API]
    # [Coformer Amount] -> [Amount of Coformer]
    # [Amount Unit] (API) -> [Amount Unit of API]
    # [Amount Unit] (Coformer) -> [Amount Unit of Coformer]
    # [Solvent Amount] -> [Amount of Solvent]
    # [Reaction Temperature] -> [Mixing Temperature]
    # [Reaction Temperature Unit] -> [Mixing Temperature Unit]
    
    "laser_irradiation": " ".join([
        "Laser irradiation synthesis was performed using [Amount of API] [Amount Unit of API] of [API] and [Amount of Coformer] [Amount Unit of Coformer] of [Coformer] in a ratio of [Part of Ratio API]:[Part of Ratio Coformer].",
        "The components were mixed with [Amount of Solvent] [Solvent Amount Unit] of [Solvent], [Amount of Second Solvent] [Second Solvent Amount Unit] of [Second Solvent], and [Amount of Third Solvent] [Third Solvent Amount Unit] of [Third Solvent].",
        "The mixture was spread as a thin layer on [Foil Material] foil.",
        "Irradiation was performed using a [Laser Apparatus] with a focal length of [Focal Length] [Focal Length Unit], operated at [Power] [Power Unit] and a raster speed of [Raster Speed] [Raster Speed Unit].",
        "The resulting co-crystal was collected from the foil and dried for [Drying Time] [Drying Time Unit] at [Drying Temperature] [Drying Temperature Unit].",
    ]),
}
 
 
PARAMETER_FAMILIES = {
    "Ratio": ["Part of Ratio API", "Part of Ratio Coformer"],
    "Amounts": [
        "Amount of API",
        "Amount of Coformer",
        "Amount of Solvent",
        "Amount of Second Solvent",
        "Amount of Third Solvent",
    ],
    "Solvent": ["Solvent"],
    "Additional solvent": ["Second Solvent", "Third Solvent"],
    "Time": [
        "Mixing Time",
        "Drying Time",
        "Evaporation Time",
        "Time of Cooling or Evaporation",
    ],
    "Temperature": [
        "Mixing Temperature",
        "Drying Temperature",
        "Evaporation Temperature",
    ],
    "Frequency": ["Mixing Frequency"],
    "Setup": [
        "Mixing Apparatus",
        "Covering Method",
        "Description of Holes",
    ],
}
 
 
__all__ = [
    "METHODS",
    "METHODS_SMALL",
    "NO_VALUE",
    "MISSING_MARKER",
    "SMILES_COLS",
    "NECESSARY_COLS",
    "RATIO_COLS",
    "NUMERIC_COLS",
    "NUMERIC_COLS_FILL",
    "PARAMETERS_RANGES",
    "ROUNDING_STEPS",
    "STRING_COLS",
    "STRING_COLS_FILL",
    "SOLVENT_COLS",
    "APPARATUS_COLS",
    "COVERING_AND_HOLES_COLS",
    "REPLACE_COLS",
    "REMOVE_UNIT_COLS",
    "UNIT_DEPENDENCIES",
    "UNIT_COLS",
    "FINAL_COLS",
    "STANDART_VALUES",
    "GROUP_LEVELS_CANDIDATES",
    "SECOND_THIRD_SOLVENT_PAIRS",
    "SECOND_AMOUNT_PREV",
    "THIRD_AMOUNT_PREV",
    "METHOD_TEMPLATES",
    "PARAMETER_FAMILIES",
]
