CASHE_MANUAL = {
    # --- Grinding ---
    "schiﬀbase derived from 2-hydroxy-1-naphthaldehyde": "C1=CC=C2C(=C1)C=CC(=C2C=O)O",
    "n-salicylideneaniline": "C1=CC=C(C=C1)N=CC2=CC=CC=C2O",
    "2,2′-bispyridylethylene": "C1=CC=NC(=C1)/C=C/C2=CC=CC=N2",
    "β-estradiol": "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O",
    "estrone": "C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CCC4=C3C=CC(=C4)O",
    "nicorandil": "C1=CC(=CN=C1)C(=O)NCCO[N+](=O)[O-]",
    "1,4-diazabicyclo-[2.2.2]-octane": "C1CN2CCN1CC2",
    "hydrochlorothiazide": "C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl",
    "lonidamine": "C1=CC=C2C(=C1)C(=NN2CC3=C(C=C(C=C3)Cl)Cl)C(=O)O",
    "p-toluenesulfonamide": "CC1=CC=C(C=C1)S(=O)(=O)N",
    "niﬂumic acid": "C1=CC(=CC(=C1)NC2=C(C=CC=N2)C(=O)O)C(F)(F)F",
    "mefenamic acid": "CC1=C(C(=CC=C1)NC2=CC=CC=C2C(=O)O)C",
    "theophylline": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "bexarotene": "CC1=CC2=C(C=C1C(=C)C3=CC=C(C=C3)C(=O)O)C(CCC2(C)C)(C)C",
    "1,4,5,8-naphthalenetetracarboxylic dianhydride": "C1=CC2=C3C(=CC=C4C3=C1C(=O)OC4=O)C(=O)OC2=O",
    "piroxicam": "CN1C(=C(C2=CC=CC=C2S1(=O)=O)O)C(=O)NC3=CC=CC=N3",
    "theophylline": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "ethyl diclofenac": "CCOC(=O)CC1=CC=CC=C1NC2=C(C=CC=C2Cl)Cl",
    "clotrimazole": "C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3Cl)N4C=CN=C4",
    "chlorothiazide": "C1=C2C(=CC(=C1Cl)S(=O)(=O)N)S(=O)(=O)N=CN2",
    "gallic acid": "C1=C(C=C(C(=C1O)O)O)C(=O)O",
    "proxyphylline": "CC(CN1C=NC2=C1C(=O)N(C(=O)N2C)C)O",
    "2,2′-bispyridylethylene": "C1=CC=NC(=C1)/C=C/C2=CC=CC=N2",
    "β-estradiol": "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O",
    "estrone": "C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CCC4=C3C=CC(=C4)O",
    "nicorandil": "C1=CC(=CN=C1)C(=O)NCCO[N+](=O)[O-]",
    "1,4-diazabicyclo-[2.2.2]-octane": "C1CN2CCN1CC2",
    "hydrochlorothiazide": "C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl",
    "lonidamine": "C1=CC=C2C(=C1)C(=NN2CC3=C(C=C(C=C3)Cl)Cl)C(=O)O",
    "p-toluenesulfonamide": "CC1=CC=C(C=C1)S(=O)(=O)N",
    "niﬂumic acid": "C1=CC(=CC(=C1)NC2=C(C=CC=N2)C(=O)O)C(F)(F)F",
    "mefenamic acid": "CC1=C(C(=CC=C1)NC2=CC=CC=C2C(=O)O)C",
    "theophylline": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "bexarotene": "CC1=CC2=C(C=C1C(=C)C3=CC=C(C=C3)C(=O)O)C(CCC2(C)C)(C)C",
    "1,4,5,8-naphthalenetetracarboxylic dianhydride": "C1=CC2=C3C(=CC=C4C3=C1C(=O)OC4=O)C(=O)OC2=O",
    "piroxicam": "CN1C(=C(C2=CC=CC=C2S1(=O)=O)O)C(=O)NC3=CC=CC=N3",
    "caffeine": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",
    "theophylline": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "ethyl diclofenac": "CCOC(=O)CC1=CC=CC=C1NC2=C(C=CC=C2Cl)Cl",
    "clotrimazole": "C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3Cl)N4C=CN=C4",
    "chlorothiazide": "C1=C2C(=CC(=C1Cl)S(=O)(=O)N)S(=O)(=O)N=CN2",
    "gallic acid": "C1=C(C=C(C(=C1O)O)O)C(=O)O",
    "proxyphylline": "CC(CN1C=NC2=C1C(=O)N(C(=O)N2C)C)O",
    "p-hydroxybenzoic acid": "C1=CC(=CC=C1C(=O)O)O",
    "chrysin": "C1=CC=C(C=C1)C2=CC(=O)C3=C(C=C(C=C3O2)O)O",
    "dibenzyl sulfoxide": "C1=CC=C(C=C1)CS(=O)CC2=CC=CC=C2",
    "meloxicam": "CC1=CN=C(S1)NC(=O)C2=C(C3=CC=CC=C3S(=O)(=O)N2C)O",
    "salicylamide": "C1=CC=C(C(=C1)C(=O)N)O",
    "5-fluorouracil": "C1=C(C(=O)NC(=O)N1)F",
    "triphenylphosphine oxide": "C1=CC=C(C=C1)P(=O)(C2=CC=CC=C2)C3=CC=CC=C3",
    "orcinol": "CC1=CC(=CC(=C1)O)O",
    "favipiravir": "C1=C(N=C(C(=O)N1)C(=O)N)F",
    "agomelatine": "CC(=O)NCCC1=CC=CC2=C1C=C(C=C2)OC",
    "bisphenol a": "CC(C)(C1=CC=C(C=C1)O)C2=CC=C(C=C2)O",
    "2,20-bis(4-hydroxyphenyl)hexaﬂuoropropane": "C1=CC(=CC=C1C(C2=CC=C(C=C2)O)(C(F)(F)F)C(F)(F)F)O",
    "1,4-bis-p-cyanostyrylbenzene": "C1=CC=C(C(=C1)/C=C/C2=CC=C(C=C2)/C=C/C3=CC=CC=C3C#N)C#N",
    "phenylacetic acid": "C1=CC=C(C=C1)CC(=O)O",
    "flufenamic acid": "C1=CC=C(C(=C1)C(=O)O)NC2=CC=CC(=C2)C(F)(F)F",
    "sulfamerazine": "CC1=NC(=NC=C1)NS(=O)(=O)C2=CC=C(C=C2)N",
    "bumetanide": "CCCCNC1=C(C(=CC(=C1)C(=O)O)S(=O)(=O)N)OC2=CC=CC=C2",
    "11-azaartemisinin": "C[C@@H]1CC[C@H]2[C@H](C(=O)N[C@H]3[C@@]24[C@H]1CC[C@](O3)(OO4)C)C",
    "ethenzamide": "CCOC1=CC=CC=C1C(=O)N",
    "phenazine": "C1=CC=C2C(=C1)N=C3C=CC=CC3=N2",
    "sulfaguanidine": "C1=CC(=CC=C1N)S(=O)(=O)N=C(N)N",
    "s-naproxen": "C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O",
    "rs-naproxen": "C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O",
    "kojic acid": "C1=C(OC=C(C1=O)O)CO",
    "p-sulfonamide benzoic acid": "C1=CC(=CC=C1C(=O)O)NS(=O)(=O)C2=CC=C(C=C2)N",
    "racemic bis-b-naphthol": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "n-(3-ethynylphenyl)-6-7-dimethoxyquinazolin-4-amine": "COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC=CC(=C3)C#C)OC",
    "theophylline (form ii)": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "febuxostat": "CC1=C(SC(=N1)C2=CC(=C(C=C2)OCC(C)C)C#N)C(=O)O",
    "diiodomethyl-p-tolylsulfone": "CC1=CC=C(C=C1)S(=O)(=O)C(I)I",
    "sulfacetamide": "CC(=O)NS(=O)(=O)C1=CC=C(C=C1)N",
    "isonicotinamide": "C1=CN=CC=C1C(=O)N",
    "urea": "C(=O)(N)N",
    "theobromine": "CN1C=NC2=C1C(=O)NC(=O)N2C",
    "1,3,5,7-tetraazatricyclo[3.3.1.13,7]decane": "C1N2CN3CN1CN(C2)C3.C1=CC=C(C=C1)C(=O)O",
    "1,3,6,8-tetraazatricyclo[4.4.1.13,8]dodecane": "C1CN2CN3CCN(C2)CN1C3",
    "thymol": "CC1=CC(=C(C=C1)C(C)C)O",
    "carvacrol": "CC1=C(C=C(C=C1)C(C)C)O",
    "curcumin": "COC1=C(C=CC(=C1)/C=C/C(=O)CC(=O)/C=C/C2=CC(=C(C=C2)O)OC)O",
    "9-phenylacetylene anthracene": "C1=CC=C(C=C1)C#CC2=C3C=CC=CC3=C(C4=CC=CC=C42)C#CC5=CC=CC=C5",
    "ciproﬂoxacin": "C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O",
    "hexamethylenetetraamine": "C1N2CN3CN1CN(C2)C3",
    "ellagic acid": "C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O)O)O",
    "3-hydroxyl-2-naphthoic acid": "C1=CC=C2C=C(C(=CC2=C1)C(=O)O)O",
    "catechin": "C1[C@@H]([C@H](OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O",
    "naphthalene-2,3-diol": "C1=CC=C2C=C(C(=CC2=C1)O)O",
    "1,4-diazabicyclo[2.2.2]octane": "C1C[NH+]2CC[NH+]1CC2",
    "2-chloro-4-nitrobenzoic acid": "C1=CC(=C(C=C1[N+](=O)[O-])Cl)C(=O)O",
    "nevirapine": "CC1=C2C(=NC=C1)N(C3=C(C=CC=N3)C(=O)N2)C4CC4",
    "1,2,3,4-tetrafluoro-5,6-diiodobenzene": "C1(=C(C(=C(C(=C1F)I)I)F)F)F",
    "(e)-2-methoxy-6-(pyridin-3-yliminomethyl)phenol": "CC1=CC=C(C=C1)NCC2=C(C(=CC=C2)OC)O",
    "1,2,4,5-tetrafluoro-3,6-diiodobenzene": "C1(=C(C(=C(C(=C1F)I)I)F)F)F",
    "11-azaartemisinin": "C[C@@H]1CC[C@H]2[C@H](C(=O)N[C@H]3[C@@]24[C@H]1CC[C@](O3)(OO4)C)C",
    "(rs)-2-(2-oxopyrrolidin-1-yl)butanamide": "CCC(C(=O)N)N1CCCC1=O.C1CC(=O)NC1",
    "imine derived from o-vanillin and 4-aminoacetophenone": "C[CH+]C=N",
    "clonidine": "C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl",
    "pentoxifylline": "CC(=O)CCCCN1C(=O)C2=C(N=CN2C)N(C1=O)C",
    "caffeic acid": "C1=CC(=C(C=C1/C=C/C(=O)O)O)O",
    "linsidomine": "C1COCCN1[N+]2=CC(=N)O[N-]2",
    "4-aminoacetophenone": "CC(=O)C1=CC=C(C=C1)N.Cl",
    "4-nitroaniline": "C1=CC(=CC=C1N)[N+](=O)[O-]",
    "3-aminopyridine": "C1=CC(=CN=C1)N",
    "3-aminobenzonitrile": "C1=CC(=CC(=C1)N)C#N",
    "anthracene": "C1=CC=C2C=C3C=CC=CC3=CC2=C1",
    "9-methylanthracene": "CC1=C2C=CC=CC2=CC3=CC=CC=C13",
    "indomethacin": "CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O",
    "nicotinamide": "C1=CC(=CN=C1)C(=O)N",
    "trans-1,2-bis (4-pyridyl) ethylene": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "fisetin": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(O2)C=C(C=C3)O)O)O)O",
    "pyrazinoic acid": "C1=CN=C(C=N1)C(=O)O",
    "(e)-acetophenone oxime": "C/C(=N\O)/C1=CC=CC=C1",
    "acetophenone oxime": "C/C(=N\O)/C1=CC=CC=C1",
    "2-methylresorcinol": "CC1=C(C=CC=C1O)O",
    "triphenylphosphine oxide": "C1=CC=C(C=C1)P(=O)(C2=CC=CC=C2)C3=CC=CC=C3",
    "triphenylphosphine": "C1=CC=C(C=C1)P(=O)(C2=CC=CC=C2)C3=CC=CC=C3",
    "tetracene": "C1=CC=C2C=C3C=C4C=CC=CC4=CC3=CC2=C1",
    "coronene": "C1=CC2=C3C4=C1C=CC5=C4C6=C(C=C5)C=CC7=C6C3=C(C=C2)C=C7",
    "aripiprazole": "C1CC(=O)NC2=C1C=CC(=C2)OCCCCN3CCN(CC3)C4=C(C(=CC=C4)Cl)Cl",
    "nefiracetam": "CC1=C(C(=CC=C1)C)NC(=O)CN2CCCC2=O",
    "trimethoprim": "COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N",
    "ezetimibe": "C1=CC(=CC=C1[C@@H]2[C@H](C(=O)N2C3=CC=C(C=C3)F)CC[C@@H](C4=CC=C(C=C4)F)O)O",
    "lorazepam": "C1=CC=C(C(=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O)Cl",
    "4,4′-biphenol": "C1=CC(=CC=C1C2=CC=C(C=C2)O)O",
    "resorcinol": "C1=CC(=CC(=C1)O)O",
    "theophylline hydrate": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "dapsone": "C1=CC(=CC=C1N)S(=O)(=O)C2=CC=C(C=C2)N",
    "1,4-diiodotetrafluorobenzene": "C1(=C(C(=C(C(=C1I)F)F)I)F)F",
    "racemic-bis-b-naphthol": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "tenoxicam": "CN1C(=C(C2=C(S1(=O)=O)C=CS2)O)C(=O)NC3=CC=CC=N3",
    "5-chlorouracil": "C1=C(C(=O)NC(=O)N1)Cl",
    "5-bromouracil": "C1=C(C(=O)NC(=O)N1)Br",
    "5-iodouracil": "C1=C(C(=O)NC(=O)N1)I",
    "1,3,5-triﬂuoro-2,4,6-triiodobenzene": "C1(=C(C(=C(C(=C1I)F)I)F)I)F",
    "barbituric acid": "C1C(=O)NC(=O)NC1=O",
    "salicylic acid": "C1=CC=C(C(=C1)C(=O)O)O",
    "aspirin": "CC(=O)OC1=CC=CC=C1C(=O)O",
    "p-nitroaniline": "C1=CC(=CC=C1N)[N+](=O)[O-]",
    "ferulic acid": "COC1=C(C=CC(=C1)/C=C/C(=O)O)O",
    "l-tryptophan": "C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N",
    "thioamide": "C1=CC=C(C=C1)C(C2=CC=CC=C2)C(=S)NCCCN3C=CN=C3",
    "thiobenzamide": "C1=CC=C(C=C1)C(=S)N",
    "2-fluorothiobenzamide": "C1=CC=C(C(=C1)C(=S)N)F",
    "bis-pyridineacetamide": "C1=CC=NC(=C1)CC(=O)N",
    "r-proxyphylline": "CC(CN1C=NC2=C1C(=O)N(C(=O)N2C)C)O",
    "4,40-bipyridine": "C1=CN=CC=C1C2=CC=NC=C2",
    "chiral bis-b-naphthol": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(r)-6,6'-dibromo-bis-b-naphthol": "C1=CC2=C(C=CC(=C2C3=C(C=CC4=C3C=CC(=C4)Br)O)O)C=C1Br",
    "racemic 6,6'-dibromo-bis-b-naphthol": "C1=CC2=C(C=CC(=C2C3=C(C=CC4=C3C=CC(=C4)Br)O)O)C=C1Br",
    "(r)-3,3'-dibromo-bis-b-naphthol": "C1=CC2=C(C=CC(=C2C3=C(C=CC4=C3C=CC(=C4)Br)O)O)C=C1Br",
    "racemic (r)-3,3'-dibromo-bis-b-naphthol": "C1=CC2=C(C=CC(=C2C3=C(C=CC4=C3C=CC(=C4)Br)O)O)C=C1Br",
    "(r)-bis-b-naphthol": "C1=CC2=C(C=CC(=C2C3=C(C=CC4=C3C=CC(=C4)Br)O)O)C=C1Br",
    "theophylline (form iv)": "CN1C2=C(C(=O)N(C1=O)C)NC=N2",
    "s-2-(2-oxopyrrolidin-1-yl)butanamide": "CCC(C(=O)N)N1CCCC1=O.C1CC(=O)NC1",
    "4-(n,n-dimethylamino)benzoic acid": "CN(C)C1=CC=C(C=C1)C(=O)O",
    "seselin (8,8-dimethyl-2h,8h-benzo[1,2-b:3,4-b']dipyran-2-one)": "CC1(C=CC2=C(O1)C=CC3=C2OC(=O)C=C3)C",
    "s-etiracetam": "CC[C@H](C(=O)N)N1CCCC1=O",
    "benzo-[18]crown-6": "C1COCCOCCOC2=CC=CC=C2OCCOCCO1",
    "pyridine-3,5-bis(1-methyl-benzimidazole-2-yl)": "CN1C2=CC=CC=C2N=C1C3=NC(=CC=C3)C4=NC5=CC=CC=C5N4C",
    "2,29-bis(4-hydroxyphenyl)hexafluoropropane": "C1=CC(=CC=C1C(C2=CC=C(C=C2)O)(C(F)(F)F)C(F)(F)F)O",
    "2,29-bis(4-hydroxy-3-methylphenyl)propane": "CC1=C(C=CC(=C1)C(C)(C)C2=CC(=C(C=C2)O)C)O",
    "n,n'-bis[(pyridin-4-yl)methyl]ethanediamide": "C1=CN=CC=C1CNC(=O)C(=O)NCC2=CC=NC=C2",
    "4-(n,n-dimethylamino)-benzaldehyde": "CN(C)C1=CC=C(C=C1)C=O",
    "s-oxiracetam": "C1[C@@H](CN(C1=O)CC(=O)N)O",
    "β-estradiol hemihydrate": "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O.C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O.O",
    "aniline 2": "C1=CC=C(C=C1)N",
    "trans-1,4-bis(iodoethynyl)cyclohexane-1,4-diol": "C1CC(CCC1(C#CI)O)(C#CI)O",
    "cis-1,4-bis(iodoethynyl)cyclohexane-1,4-diol": "C1CC(CCC1(C#CI)O)(C#CI)O",
    "trans-1,4-diethynylcyclohexane-1,4-diol": "C1CC(CCC1(C#CI)O)(C#CI)O",
    "o-methyl-n-(4-nitrophenyl)thiocarbamate": "CN(C)C(=S)OC1=CC=C(C=C1)SC",
    "o-ethyl-n-phenylthiocarbamate": "CCOC(=S)NC1=CC=CC=C1",
    "o-isopropyl-n-phenylthiocarbamate": "CC(C)C1=CC=CC=C1OC(=O)N",
    "()-3-o-tolylbutanoic acid": "CC1=CC(=CC=C1)[C@@H](C)CC(=O)O",
    "thieno[3,2-b]benzo[b]thiophene": "C1=CC=C2C(=C1)C3=C(S2)C4=CC=CC=C4S3",
    "4-pyridinecarbxaldehyde": "C1=CN=CC=C1C=O",
    "4,4'-azobipyridine": "C1=CN(C=CC1=NN=C2C=C[N+](=O)C=C2)[O-]",
    "1,4-diiotetrafluorobenzene": "C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])F",
    "gentistic acid": "C1=CC(=C(C=C1O)C(=O)O)O",
    "(r,r)-(-)-trans-2,3-bis(hydroxydiphenylmethyl)-1,4-dioxaspiro[4.4]nonane (5a)": "C1CCC2(C1)O[C@H]([C@@H](O2)CP(C3=CC=CC=C3)C4=CC=CC=C4)CP(C5=CC=CC=C5)C6=CC=CC=C6",
    "(r,r)-(-)-trans-2,3-bis(hydroxydiphenylmethyl)-1,4-dioxaspiro[5.4]-decane (5b)": "C1CCC2(C1)O[C@H]([C@@H](O2)CP(C3=CC=CC=C3)C4=CC=CC=C4)CP(C5=CC=CC=C5)C6=CC=CC=C6",
    "s-2-chloro-s-mandelic acid": "C1=CC=C(C(=C1)C(C(=O)O)O)Cl",
    "pyrazine mono n-oxide": "C1=C[N+](=CC=N1)[O-]",
    "tetramethylpyrazine mono n-oxide": "CC1=C([N+](=C(C(=N1)C)C)[O-])C",
    "1,2,3,6-4 hydrophthalimide": "C1=CC=C2C(=C1)C(=O)N(C2=O)O",
    "s-methylsuccinic acid": "C[C@@H](CC(=O)O)C(=O)O",
    "s-3-phenyllactic acid": "C1=CC=C(C=C1)C[C@@H](C(=O)O)O",
    "4-(n,n′-dimethylamino)pyridine": "CN(C)C1=CC=NC=C1",
    "o-quinone (a)": "CC1C(C2=C(C(O1)C)C(=O)C3=C(C2=O)C=C(C=C3O)O)O",
    "o-quinone (c)": "CC1C(C2=C(C(O1)C)C(=O)C3=C(C2=O)C=C(C=C3O)O)O",
    "o-quinone (d)": "CC1C(C2=C(C(O1)C)C(=O)C3=C(C2=O)C=C(C=C3O)O)O",
    "mono- or di-carboxylic acid": "COC(=O)C1=C(C2C3C(C1O2)O3)C(=O)OC",
    "4-carboxylic acid phthalic anhydride": "C1=CC=C2C(=C1)C(=O)OC2=O",
    "4- dimethylaminpyridine": "CN(C)C1=CC=NC=C1",
    "4-hydroxy ethylbenzoate": "C1=CC(=CC=C1CCO)C(=O)[O-]",
    "4-hydroxy propyl benzoate": "C1=CC=C(C=C1)C(=O)OCCCC2=CC=C(C=C2)O",
    "4-hydroxy isopropyl benzoate": "CC(C)C1=CC(=CC(=C1O)C(C)C)C(=O)OC(C)C",
    "pyrazine-n-oxide": "C1=C[N+](=CC=N1)[O-]",
    "4-dtrophenol": "C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])O",
    "trans-1,4-di(4-pyridyl)ethylene": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "2,2’-dipyridylamine": "C1=CC=NC(=C1)NC2=CC=CC=N2",
    
    # --- Slurry ---
    "mestanolone": "C[C@]12CCC(=O)C[C@@H]1CC[C@@H]3[C@@H]2CC[C@]4([C@H]3CC[C@]4(C)O)C",
    "ethyl D/L-lactate": "CCOC(=O)C(C)O",
    "azoxystrobin": "COC1=CC=C(C=C1)OC2=NC(=NO2)C3=CC=CC=C3OC(=O)N(C)OC",
    "methyl-phenyl-propylphosphine oxide (2)": "CCC[P](C)(=O)C1=CC=CC=C1",
    "mandelic acid (RMA and SMA mixture)": "O=C(O)C(O)c1ccccc1",
    "stanolone": "CC12CCC3C(C1CCC2O)CCC4=CC(=O)CCC34C",
    "(S)-methyl-phenyl-propylphosphine oxide (2)": "CPCCCC1=CC=CC=C1",
    "2,2′-BIPY": "n1cccc(c1)c2ccccn2",
    "4,4′-BIPY": "C1=CN=CC=C1C2=CC=NC=C2",
    "scoparone": "COc1cc2oc(=O)ccc2cc1OC",
    "Aceclofenac": "CCOC(=O)COC1=CC=C(C=C1)C(C2=CC=CC=C2Cl)NC(=O)C3=CC=CC=C3",
    "ethyl-propyl-phenylphosphine oxide (3)": "CCCP(=O)(CC)C1=CC=CC=C1",
    "acetaminophen": "CC(=O)NC1=CC=C(O)C=C1O",
    "Sulfoxide 3": "CCCCCCCCS(=O)C(C)CC1=CC2=C(C=C1)OCO2",
    "carbamazepine (III)": "O=C1NC2=CC=CC=C2C3=CC=CC=C13",
    "butyl-methyl-phenylphosphine oxide (4)": "C1(P(=O)(C(C)(C)C)C)=CC=CC=C1",
    "Sulfoxide 2": "CCCCCCCCS(=O)C(C)CC1=CC2=C(C=C1)OCO2",
    "thiophanate-ethyl": "CCOC(=O)NNC(=S)NCCNC(=S)NN=C(OC)OC",
    "racemic menthol": "CC1CCC(C(C1)O)C(C)C",
    "Neﬁracetam": "CCC1=CC(=O)N(C(=O)N1CC)CCOC",
    "O,O’-dibenzoyl-(2R,3R)-tartaric acid monohydrate": "O.OC(=O)[C@@H](OC(=O)C1=CC=CC=C1)[C@H](OC(=O)C1=CC=CC=C1)C(O)=O",
    "tadalaﬁl": "CCOC(=O)N1CCN(CC1)C2=C(C3=CC=CC=C3N2C)C(=O)N4CCC5=CC=CC=C5C4",
    "O,O’-dibenzoyl-(2R,3R)-tartaric acid": "OC(=O)[C@@H](OC(=O)c1ccccc1)[C@H](OC(=O)c2ccccc2)C(O)=O",
    "racemic methyl-phenyl-propylphosphine oxide (2)": "CCC[P](C)(=O)C1=CC=CC=C1",
    "Sulfoxide 4": "CCCCCCCCS(=O)C(C)CC1=CC2=C(C=C1)OCO2",
    "β-sitosterol": "CC[C@H](CC[C@@H](C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)C)C(C)C",
    "Lenvatinib": "COC1=CC2=C(C=C1)N=C(N2)NC3=CC(=C(C=C3)Cl)C4=CN=C(N=C4)C",
    "racemic methyl-phenyl-propylphosphine oxide": "CCC[P](C)(=O)C1=CC=CC=C1",
    "dimetronidazole": "O=[N](C(N1C)=CN=C1C)=O",
    
    # --- Ultrasound ---
    "4,6-di-Cl-resorcinol": "Oc1cc(O)c(Cl)cc1Cl",
    "4,6-di-Br-resorcinol": "Oc1cc(O)c(Br)cc1Br",
    
    # --- Antisolvent ---
    "(4-C6H4F)3SiH": "c1ccc(cc1F)[SiH](c2ccc(F)cc2)c3ccc(F)cc3",
    "Ph3SiF": "F[Si](c1ccccc1)(c2ccccc2)c3ccccc3",
    "Benzo-15-Krone-5": "C1COCCOC2=CC=CC=C2OCCOCCO1",
    "CL 20": "C12C3N(C4C(N3[N+](=O)[O-])N(C(N1[N+](=O)[O-])C(N2[N+](=O)[O-])N4[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]",
    "6-methoxy-gossypol": "CC1=CC2=C(C(=C(C(=C2C(C)C)O)O)C=O)C(=C1C3=C(C4=C(C=C3C)C(=C(C(=C4C=O)O)OC)C(C)C)O)O",
    "bis[di(2-phenethyl)selenophosphoryl]selenide (4)": "C1=CC=C(C=C1)CCP(=[Se])(CCC2=CC=CC=C2)[Se]P(=[Se])(CCC3=CC=CC=C3)CCC4=CC=CC=C4",
    "(PriO)3SiH": "CC(C)O[SiH](OC(C)C)OC(C)C",
    "1,2-di-4-pyridylethane N,N′-dioxide": "[O-][n+]1ccc(CCc2ccc[n+]([O-])c2)cc1",
    "perylo[1,12-b,c,d]thiophene": "C1=CC2=C3C(=C1)C4=CC=CC5=C4C6=C(C=C5)SC(=C36)C=C2",
    "1,1,6,6-tetraphenylhexa-2,4-diyne-1,6-diol (A)": "C1=CC=C(C=C1)C(C#CC#CC(C2=CC=CC=C2)(C3=CC=CC=C3)O)(C4=CC=CC=C4)O",
    "2-amino-6-pyrimidin-4(1H)-one hydrochloride": "C1=CN=C(NC1=O)N.Cl",
    "5-aminouracyl": "C1=C(C(=O)NC(=O)N1)N",
    
    # --- Solution crystallization ---
    "(D, L) malic acid": "C(C(C(=O)O)O)C(=O)O",
    "(E)-4,40-diazastilbene": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "(E)-O-ethyl-N-phenylthiocarbamate": "CCOC(=S)NC1=CC=CC=C1",
    "(E)-O-methyl-N-phenyl-thiocarbamate": "COC(=S)NC1=CC=CC=C1",
    "(L) malic acid": "O[C@@H](CC(O)=O)C(O)=O",
    "(R)-phenibut": "C1=CC=C(C=C1)[C@@H](CC(=O)O)CN",
    "1,10-binaphthyl-2,20-diol": "C1=CC=C2C(=C1)C=C(C=C2C3=CC(=CC4=CC=CC=C43)O)O",
    "1,10-biphenyl-2,20-dicarboxylic acid": "O=C(C1=CC=CC=C1C2=CC=CC=C2C(O)=O)O",
    "1,2-bis(2'-methyl-5'-(pyrid-4''-yl)thien-3'-yl)perflourocyclopentene": "CC1=C(SC(=C1C2=C(C(C(C2(F)F)(F)F)(F)F)C3=C(SC(=C3C)C4=CC=CC=C4)C)C)C5=CC=CC=C5",
    "1,2-bis(4'-pyridyl)ethene": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "1,2-bis(4'-pyridyl)ethyne": "C1=CN=CC=C1C#CC2=CC=NC=C2",
    "1,2-bis(4′-pyridyl)ethyne": "C1=CN=CC=C1C#CC2=CC=NC=C2",
    "1,2-bis(diphenylphosphoryl)ethane dioxide": "C1=CC=C(C=C1)P(=O)(CCP(=O)(C2=CC=CC=C2)C3=CC=CC=C3)C4=CC=CC=C4",
    "1,2-diiodotetra¯uoroethane (1a)": "C(C(F)(F)I)(F)(F)I",
    "1,3-dimethyl-4,5-diphenyl-1H-imidazol-2(3H)-one (imidazolinone) 10a": "CC1=C(N(C(=O)N1)C(=O)C)C",
    "1,3cis,5cis-cyclohexanetricarboxylic acid": "C1C(CC(CC1C(=O)O)C(=O)O)C(=O)O",
    "1,4-DITFB": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,4-di(pyrdin-3-yl)buta-1,3-diyne": "C1(C#CC#CC2=CC=CN=C2)=CC=CN=C1",
    "1,4-di(pyrdin-4-yl)buta-1,3-diyne": "C(C#CC1=CC=NC=C1)#CC1=CC=NC=C1",
    "1,4-diazabicyclo[2.2.2]octane N,N9-dioxide": "[O-][N+]12CC[N+]([O-])(CC1)CC2",
    "1,4-diazabicylo[2.2.2]-octane": "C1CN2CCN1CC2",
    "1,4-diiodoper¯uorobutane (1b)": "IC(F)(F)C(F)(F)C(F)(F)C(F)(F)I",
    "1,4-diiodoper¯uorobuthane (1b)": "IC(F)(F)C(F)(F)C(F)(F)C(F)(F)I",
    "1,4-diiodotetra¯uorobenzene (1e)": "C1(=C(C(=C(C(=C1I)F)F)I)F)F",
    "1,4–di(4’–pyridyl)–1,3–diacetylene": "C(C#CC1=CC=NC=C1)#CC1=CC=NC=C1",
    "1,6-diiodoper¯uorohexane (1c)": "IC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)I",
    "1,8-diiodoper¯uorooctane (1d)": "IC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)I",
    "14-thia-crown-4": "S1CCSCCCSCCSCCC1",
    "18-thia-crown-6": "C1CSCCSCCSCCSCCSCCS1",
    "2,20,6,60-tetracarboxybiphenyl": "O=C(O)C1=C(C2=C(C(O)=O)C=CC=C2C(O)=O)C(C(O)=O)=CC=C1",
    "2,20-dipyridyl-N,N0-dioxide": "C1=CC(=C2C=CC=C[N+]2=O)N(C=C1)[O-]",
    "2,20-dithiodibenzoic acid": "C1=CC=C(C(=C1)C(=O)O)SSC2=CC=CC=C2C(=O)O",
    "2,29-dithiodibenzoic acid": "C1=CC=C(C(=C1)C(=O)O)SSC2=CC=CC=C2C(=O)O",
    "2,2A-dithiobis(pyridine N-oxide)": "[O-][N+]1=CC=CC=C1SSC2=CC=CC=[N+]2[O-]",
    "2,2′-BIPY": "n1ccccc1-c2ccccn2",
    "2,2′-dipyridylacetylene": "c1ccc(nc1)C#Cc1ccccn1",
    "2,2′-dithiobis(pyridine N-oxide)": "[O-][N+]1=CC=CC=C1SSC2=CC=CC=[N+]2[O-]",
    "2,3,5,6-tetramethyl-1,4-benzodicarbonitrile": "CC1=C(C(=C(C(=C1C#N)C)C)C#N)C",
    "2,3,6,7-tetramethyl-1,4,5,8-tetrathiafulvalene": "CC1=C(SC(=C2SC(=C(S2)C)C)S1)C",
    "2-ammino-5-nitropyridine": "Nc1ccc(cn1)[N+]([O-])=O",
    "2-bromo-6-[3-methyl-butyn-3-ol]pyridine": "CC(C)(O)C#Cc1cccc(Br)n1",
    "2-hydroxyl-1,3,5-tricarboxylic acid": "O=C(C1=CC(C(O)=O)=CC(C(O)=O)=C1O)O",
    "3,3’-azobipyridine": "C1=CC(=CN=C1)N=NC2=CN=CC=C2",
    "3,4'-bpe": "C1=CC(=CN=C1)/C=C/C2=CC=NC=C2",
    "3,4-dicyano-1,2,5-selenodiazole": "N#CC1=N[Se]N=C1C#N",
    "3,5-Di-tert-butyl-1,2-benzoquinone (1)": "CC(C)(C)c1cc(=O)c(=O)cc1C(C)(C)C",
    "3,6-bis(30-pyridyl)-1,2,4,5-tetrazine": "C1=CC(=CN=C1)C2=NN=C(N=N2)C3=CN=CC=C3",
    "3-epiursodeoxycholic acid": "C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C",
    "3-pyridylacetylene (3PA)": "C#CC1=CN=CC=C1",
    "4,4',5,5'-tetramethyl-A2,2'-bi-1,3-diselenole": "CC1=C([Se]C(=C2[Se]C(=C([Se]2)C)C)[Se]1)C",
    "4,4-isopropylidene bisphenol": "CC(c1ccc(cc1)O)(c2ccc(cc2)O)C",
    "4,40,400-(ethane-1,1,1-triyl)triphenol": "CC(C1=CC=C(C=C1)O)(C2=CC=C(C=C2)O)C3=CC=C(C=C3)O",
    "4,40-(cyclohexane-1,1-diyl)diphenol": "Oc1ccc(C2(c3ccc(O)cc3)CCCCC2)cc1",
    "4,40-(fluorene-9,9-diyl)diphenol": "OC1=CC=C(C=C1)C1(C2=CC=CC=C2C2=CC=CC=C12)C1=CC=C(O)C=C1",
    "4,40-bis(dimethylamino)-benzophenone": "CN(C)C1=CC=C(C=C1)C(=O)C2=CC=C(C=C2)N(C)C",
    "4,49-(1,3-adamantanediyl)diphenol": "C1C2CC3(CC1CC(C2)(C3)C4=CC=C(C=C4)O)C5=CC=C(C=C5)O",
    "4,4’-BPE": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "4,4’-azobipyridine": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "4,4’-bipy": "C1=CN=CC=C1C2=CC=NC=C2",
    "4,4’-bpe": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "4,4′-bipy": "C1=CN=CC=C1C2=CC=NC=C2",
    "4,4′-dipyridine": "C1=CN=CC=C1C2=CC=NC=C2",
    "4,4′-dipyridyl sulfide": "C1=CN=CC=C1SC2=CC=NC=C2",
    "4,4′-dipyridylacetylene": "C1=CN=CC=C1C#CC2=CC=NC=C2",
    "4,7-PHEN": "C1=CC2=C(C=CC3=C2C=CC=N3)N=C1",
    "4-(4-Aminobenzyl)aniline (5)": "Nc1ccc(Cc2ccc(N)cc2)cc1",
    "4-(4-Aminophenylsulfanyl)aniline (6)": "NC1=CC=C(SC2=CC=C(N)C=C2)C=C1",
    "4-(4-aminophenylsulfonyl)aniline (dapsone)": "NC1=CC=C(S(=O)(=O)C2=CC=C(N)C=C2)C=C1",
    "4-Bromophenylcyanoxime": "C1=CC(=CC=C1/C(=N/O)/C#N)Br",
    "4-N,N′-Dimethylaminopyridine": "CN(C)C1=CC=NC=C1",
    "4-N,N′-dimethylaminopyridine": "CN(C)C1=CC=NC=C1",
    "4-amino-3,5-bis(2-pyridyle)-l,2,4-triazole": "Nn1c(nnc1-c2ccccn2)-c3ccccn3",
    "4-amino-3-methybenzoic acid": "CC1=C(C=CC(=C1)C(=O)O)N",
    "4-amino-N-(4,6-dimethylpyrimidin-2-yl)benzenesulfonamide (sulfamethazine)": "O=S(=O)(Nc1nc(cc(n1)C)C)c2ccc(N)cc2",
    "4-iodianiline": "Nc1ccc(I)cc1",
    "4-pyridylacetylene (4PA)": "C#CC1=CC=NC=C1",
    "4CNpy": "N#CC1=CC=NC=C1",
    "4′,5,7-trihydroxyﬂavanone (3)": "C1C(OC2=CC(=CC(=C2C1=O)O)O)C3=CC=C(C=C3)O",
    "5,5-diethylbarbituric acid (Barbital)": "CCC1(CC)C(=O)NC(=O)NC1=O",
    "6, 12-dioxaanthanthrene": "C1=CC2=C3C(=C1)OC4=C5C3=C(C=C2)OC6=CC=CC(=C65)C=C4",
    "6,6′-dimethyl-1,1′-bi-2-naphthol": "OC1=CC=C2C=C(C)C=CC2=C1C3=C4C=CC(C)=CC4=CC=C3O",
    "6,7-dicyanolumazine": "O=C1NC(=O)Nc2nc(c(nc12)C#N)C#N",
    "6-meth- oxyquinoline N-oxide (MQNO)": "COC1=CC2=C(C=C1)[N+](=CC=C2)[O-]",
    "9(10H)-thioacridinone": "C1=CC=C2C(=C1)C(=S)C3=CC=CC=C3N2",
    "Acide L-Malique": "O=C(O)C[C@H](O)C(=O)O",
    "Anhydrous gallic acid": "Oc1c(cc(cc1O)C(=O)O)O",
    "BINOL (2,2'-dihydroxy-1,1'-binaphthalene)": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "Bis(diphenylphosphino)ethane dioxide": "C1=CC=C(C=C1)P(=O)(CCP(=O)(C2=CC=CC=C2)C3=CC=CC=C3)C4=CC=CC=C4",
    "CBr3CN": "C(#N)C(Br)(Br)Br",
    "CBr3H": "C(Br)(Br)Br",
    "Carbenoxolone free acid": "O=C(O)CCC(=O)O[C@H]4CC[C@@]3([C@H]5C(=O)/C=C2/[C@@H]1C[C@](C(=O)O)(C)CC[C@]1(C)CC[C@]2([C@@]5(CC[C@H]3C4(C)C)C)C)C",
    "Cy3PO": "C1CCC(CC1)P(=O)(C2CCCCC2)C3CCCCC3",
    "D-Abu": "CC[C@@H](N)C(=O)O",
    "Dibenzo-18-Krone-6": "C1COc2ccccc2OCCOCCOc3ccccc3OCCO1",
    "Dibenzotetrathiafulavalene": "S1C(\\Sc2ccccc12)=C3/Sc4ccccc4S3",
    "Dicyclohexyl-18-Krone-6": "C1CCC2C(C1)OCCOCCOC3CCCCC3OCCOCCO2",
    "Dimetronidazole": "CC1=NC=C(N1C)[N+](=O)[O-]",
    "FEN (Fenamic acid)": "OC(=O)c1ccccc1Nc2ccccc2",
    "FLU (Flufenamic acid)": "FC(F)(F)c1cc(ccc1)Nc2ccccc2C(=O)O",
    "H3CTA": "OC(=O)[C@@H]1C[C@@H](C[C@@H](C1)C(=O)O)C(=O)O",
    "H3TIBTC": "O=C(O)C1=C(I)C(C(=O)O)=C(I)C(C(=O)O)=C1I",
    "HSi(OiPr)3": "CC(C)O[SiH](OC(C)C)OC(C)C",
    "Hexamethyltetramine": "C1N2CN3CN1CN(C2)C3",
    "Indole-3-acetylhydrazine": "NNC(=O)Cc1c[nH]c2ccccc12",
    "Kemp's tri-acid": "C[C@@]1(C[C@](C)(C[C@](C)(C1)C(O)=O)C(O)=O)C(O)=O",
    "L(þ)-tartaric acid": "O=C(O)[C@H](O)[C@@H](O)C(=O)O",
    "L-(R)-cysteine": "SC[C@H]([NH3+])C(=O)[O-]",
    "L-Leu-L-Leu dipeptide": "CC(C)C[C@H](N)C(=O)N[C@@H](CC(C)C)C(O)=O",
    "MEF (Mefenamic acid)": "OC(=O)c1ccccc1Nc1cccc(c1C)C",
    "N,N-Dimethypyridin-4-amine": "CN(C)C1=CC=NC=C1",
    "N,N0-diphenylthiourea": "S=C(Nc1ccccc1)Nc2ccccc2",
    "N,N9-Bis(2,4,6-trimethylphenyl)oxalamide": "O=C(C(NC1=C(C=C(C=C1C)C)C)=O)NC2=C(C=C(C=C2C)C)C",
    "N,N9-Bis(2,6-dimethylphenyl)oxalamide": "CC1=C(C(=CC=C1)C)NC(=O)C(=O)NC2=C(C=CC=C2C)C",
    "N,Nº-Bis(2-hydroxyethyl)oxalamide": "C(CO)NC(=O)C(=O)NCCO",
    "N-ethyl-3-hydroxypyrrolidine": "CCN1CCC(O)C1",
    "N-methylcabazole": "CN1C2=CC=CC=C2C3=CC=CC=C31",
    "N-methylmorpholine betaine": "C[N+]1(CC(=O)[O-])CCOCC1",
    "N-methylpiperidine betaine": "C[N+]1(CC(=O)[O-])CCCCC1",
    "N-phthaloyl-b-alanine": "OC(=O)CCN1C(=O)C2=CC=CC=C2C1=O",
    "Naphthalene-2,3-diol (7)": "OC1=CC2=CC=CC=C2C=C1O",
    "Naphtoquinone-1,4": "C1=CC=C2C(=O)C=CC(=O)C2=C",
    "Neﬁracetam": "Cc1cccc(C)c1NC(=O)CN2CCCC2=O",
    "P-butyrolactone": "O=C1OCCC1",
    "Ph2Se2": "c1ccc(cc1)[Se][Se]c2ccccc2",
    "Ph2SiD2": "[2H][Si]([2H])(c1ccccc1)c2ccccc2",
    "Ph2Te2": "c1ccc(cc1)[Te][Te]c2ccccc2",
    "Ph3PNSiMe3": "C[Si](C)(C)N=P(C1=CC=CC=C1)(C2=CC=CC=C2)C3=CC=CC=C3",
    "Ph3SiF": "F[Si](c1ccccc1)(c2ccccc2)c3ccccc3",
    "R-(+)-Dianin’s compound": "C[C@]1(c2ccc(O)cc2)CC(C)(C)Oc3ccccc31",
    "R-(+)-α-lipoic acid": "O=C(O)CCCC[C@H]1SSCC1",
    "S-PZQ": "C1CCC(CC1)C(=O)N2C[C@@H]3C4=CC=CC=C4CCN3C(=O)C2",
    "TOL (Tolfenamic acid)": "CC1=C(C=CC=C1Cl)NC2=CC=CC=C2C(=O)O",
    "Tadalaﬁl": "[H][C@]12CC3=C(NC4=CC=CC=C34)[C@H](N1C(=O)CN(C)C2=O)C1=CC2=C(OCO2)C=C1",
    "Tetrathiafulvalen": "C1=CSC(=C2SC=CS2)S1",
    "a-amino-e-caprolactam": "N1CCCCC(N)C1=O",
    "anti-4,4'-azopyridine": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "benzene-1,4-dioxyacetic acid": "C1=CC(=CC=C1OCC(=O)O)OCC(=O)O",
    "bezaﬁbrate": "CC(C)(C(=O)O)OC1=CC=C(C=C1)CCNC(=O)C2=CC=C(C=C2)Cl",
    "cis-(-)-2-Hydroxymethyl-5-(cytosin-1-yl)-1,3-oxathiolane (4)": "NC1=NC(=O)N(C=C1)[C@@H]1CS[C@H](CO)O1",
    "cis-1,4-cyclohexanecarboxylic acid": "O=C([C@H]1CC[C@@H](C(O)=O)CC1)O",
    "cyananilic acid": "N#CC1=CC(O)=C(O)C=C1C#N",
    "cyclic disarcosine": "CN1CC(=O)N(C)CC1=O",
    "cycloocta-2,4,6-trien-l-one": "C1/C=C\\C=C/C=C\\C1=O",
    "cycloocta-2,4-dien-l-one": "C1CC=CC=CC(=O)C1",
    "dipic": "O=C(O)c1cccc(n1)C(=O)O",
    "diﬂunisal": "O=C(O)c1cc(ccc1O)c2ccc(F)cc2F",
    "flurbiprofen (R/S)": "CC(C(=O)O)c1ccc(-c2ccccc2F)cc1",
    "hydroquinone-O,O′-diacetic acid": "O=C(O)COc1ccc(OCC(=O)O)cc1",
    "ibuprofen (racemic mixture)": "CC(C)Cc1ccc(C(C)C(=O)O)cc1",
    "isoquinoline 1-oxide": "[O-][n+]1ccc2ccccc2c1",
    "ketoprofen (R/S)": "CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1",
    "lamivudine form 2": "Nc1ccn([C@H]2CS[C@@H](CO)O2)c(=O)n1",
    "mesitaldehyde 1a": "Cc1cc(C)c(C=O)c(C)c1",
    "meta-Trifluoromethyl-N-ethynylphenyl benzamide": "C#Cc1ccc(NC(=O)c2cccc(C(F)(F)F)c2)cc1",
    "n-Pr 9-anthracenecarboxylate": "CCCOC(=O)c1c2ccccc2cc2ccccc12",
    "nopinic acid": "CC1(C)C2CCC(O)(C(=O)O)C1C2",
    "o-dipyridylurea": "O=C(Nc1ccccn1)Nc1ccccn1",
    "p-amino-p’-nitrobiphenyl": "C1=CC(=CC=C1C2=CC=C(C=C2)[N+](=O)[O-])N",
    "p-chloro-4-stilbazole": "C1=CC(=CC=C1/C=C/C2=CC=NC=C2)Cl",
    "p-dipyridylurea": "O=C(Nc1ccncc1)Nc1ccncc1",
    "para-tetrachlorodicyanobenzene": "N#CC1=C(Cl)C(Cl)=C(C#N)C(Cl)=C1Cl",
    "phenyl carbamidonitrile": "C1=CC=C(C=C1)NC#N",
    "pyridine betaine": "c1cc[n+](cc1)CC([O-])=O",
    "pyridyl-2-methyl-5-acetylene (PMA)": "CC1=NC=C(C=C1)C#C",
    "quinoline-4-carbaldoxime": "C1=CC=C2C(=C1)C(=CC=N2)/C=N/O",
    "rac-6,68-dibromo-bis-b-naphthol": "Brc1cc2c(c(c(cc2)O)c3c4c(cc(cc4)Br)ccc3O)cc1",
    "rac-BINOL": "Oc1ccc2ccccc2c1-c3c(O)ccc4ccccc34",
    "rac-VANOL": "Oc1c(c(cc2ccccc12)-c3ccccc3)-c4c(O)c5ccccc5cc4-c6ccccc6",
    "rac-VANOL 1": "Oc1c(c(cc2ccccc12)-c3ccccc3)-c4c(O)c5ccccc5cc4-c6ccccc6",
    "racemic 3-methyl-2-pyrrolidinone": "CC1CCNC(=O)1",
    "racemic 4-tolylsulfinamide": "Cc1ccc(cc1)S(N)=O",
    "racemic tert-butanethiosulfinate": "CC(C)(C)OS(=S)C(C)(C)C",
    "racemic-bis-â-naphthol": "Oc1ccc2ccccc2c1-c3c(O)ccc4ccccc34",
    "sildenaﬁl": "CCCC1=NN(C2=C1N=C(NC2=O)C3=CC(=C(C=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C",
    "sodium salt of 1- hydroxyl benzotriazole": "C1=CC=C2C(=C1)N=NN2[O-].[Na+]",
    "supermesitylamine": "CC(C)(C)C1=CC(=C(C(=C1)C(C)(C)C)N)C(C)(C)C",
    "tetrabromobisphenol-F": "C1=C(C=C(C(=C1Br)O)Br)CC2=CC(=C(C(=C2)Br)O)Br",
    "tetrabromoterepthalic acid": "O=C(O)c1c(Br)c(Br)c(C(=O)O)c(Br)c1Br",
    "tetrachlorophthalonitrile (TCPN)": "Clc1c(Cl)c(Cl)c(C#N)c(C#N)c1Cl",
    "trans-(-)-2-Hydroxymethyl-5-(cytosin-1-yl)-1,3-oxathiolane (5)": "C1[C@H](O[C@H](S1)CO)N2C=CC(=NC2=O)N",
    "trans-b-(2-thienyl)acrylamide": "O=C(N)/C=C/C1=CC=CS1",
    "tris-2,4,6-(4-methylphenyl)-1,3,5-triazine": "CC1=CC=C(C=C1)C2=NC(=NC(=N2)C3=CC=C(C)C=C3)C4=CC=C(C)C=C4",
    "β-sitosterol": "C[C@H](CC[C@@H](CC)C(C)C)[C@H]1CC[C@@]2([H])[C@]3([H])CC=C4CC(O)CC[C@]4(C)[C@@]3([H])CC[C@]12C",
    "ﬂuconazole": "C1=CC(=C(C=C1F)F)C(CN2C=NC=N2)(CN3C=NC=N3)O",
    "ﬂuorescein": "C1=CC=C2C(=C1)C(=O)OC23C4=C(C=C(C=C4)O)OC5=C3C=CC(=C5)O",
    "( )-2-ethylpiperidine": "CCC1CCCCN1",
    "( )-3-methylcyclohexanone": "CC1CCCC(=O)C1",
    "(1R)-(2)-camphorquinone": "CC1(C)[C@@H]2CC[C@@]1(C)C(=O)C2=O",
    "(1S)-(1)-camphorquinone": "CC1(C)[C@H]2CC[C@]1(C)C(=O)C2=O",
    "(1S,2S)-(+)-diaminocyclohexane": "C1CC[C@@H]([C@H](C1)N)N",
    "(1S,2S)-(+)-diaminocyclohexane 2": "C1CC[C@@H]([C@H](C1)N)N",
    "(D) proline": "C1C[C@@H](NC1)C(=O)O",
    "(E)-1,2-bis(4-pyridyl)ethylene (3)": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "(E)-1,2-bis-(4-pyridyl)-ethylene (6)": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "(Et4N)(FeCl4)": "CC[N+](CC)(CC)CC.Cl[Fe-](Cl)(Cl)Cl",
    "(R)-a-phenylethylamine": "C[C@H](C1=CC=CC=C1)N",
    "(R,S)-2-Pentanol": "CCCC(C)O",
    "(R,S)-2-butanol": "CCC(C)O",
    "(S)-( )-BINOL": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S)-( )-BINOL 4": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S)-(-)-2,2'-dihydroxy-1,1'-binaphthyl (BINOL)": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S)-(-)BINOL": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S)-(−)-binol": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S)-1,1’-bi-2-naphthol": "C1=CC=C2C(=C1)C=CC(=C2C3=C(C=CC4=CC=CC=C43)O)O",
    "(S,S)-(-)-1,6-di(o-chlorophenyl)-1,6-diphenylhexa-1,4-diyne-1,6-diol": "[C@@](C1=CC=CC=C1Cl)(C1=CC=CC=C1)(O)C#CC#C[C@](C1=CC=CC=C1Cl)(C1=CC=CC=C1)O",
    "(cis/trans)-3,5-dimethylpiperidne": "CC1CC(CNC1)C",
    "(l)-(+)-Tartaric acid": "O[C@H]([C@@H](O)C(=O)O)C(=O)O",
    "(lS,2S)-trans-1,2-cyclohexanediol (2)": "C1CC[C@@H]([C@H](C1)O)O",
    "(thio)barbituric acid": "C1C(=O)NC(=S)NC1=O",
    "1, 1, 6, 6-tetraphenylhexa-2, 4-diyne-1, 6-diol (1)": "C1=CC=C(C=C1)C(C#CC#CC(C2=CC=CC=C2)(C3=CC=CC=C3)O)(C4=CC=CC=C4)O",
    "1,1,6,6-tetrahphenyl-2,4-hexadiyne-1,6-diol": "C1=CC=C(C=C1)C(C#CC#CC(C2=CC=CC=C2)(C3=CC=CC=C3)O)(C4=CC=CC=C4)O",
    "1,2,-bis(4-pyridyl)ethane": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "1,2,3,4-tetra(4-pyridlyl)thiophene": "C1(C5=CC=NC=C5)=C(C3=CC=NC=C3)C(C2=CC=NC=C2)=C(C4=CC=NC=C4)S1",
    "1,2,3,4-tetracarboxylic-cyclobutane": "C1(C(C(C1C(=O)O)C(=O)O)C(=O)O)C(=O)O",
    "1,2,4,5-benzenetetracarobylic acid": "C1=C(C(=CC(=C1C(=O)O)C(=O)O)C(=O)O)C(=O)O",
    "1,2-Cyclohexyl diamine": "C1CCC(C(C1)N)N",
    "1,2-bis(4-pyridyl ethane)": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "1,2-bis(40-pyridyl)ethane": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "1,2-bis-(4-pyridyl)ethane (8)": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "1,2-bisĲ4-pyridyl)acetylene": "C1=CN=CC=C1C#CC2=CC=NC=C2",
    "1,2-diiodotetraﬂorobenzene": "C1(=C(C(=C(C(=C1F)I)I)F)F)F",
    "1,2-trans-bis(2-pyridyl)ethylene": "c1ccc(\\C=C\\c2ccccn2)nc1",
    "1,3,3-trimethyl-2-oxabicyclo[2,2,2]octane (cineole)": "O2C1(CCC(CC1)C2(C)C)C",
    "1,3,5-Benzenetricarboxylic Acid (7)": "C1=C(C=C(C=C1C(=O)O)C(=O)O)C(=O)O",
    "1,3,5-tris(p-hydoxyphenyl)benzene": "C1=CC(=CC=C1C2=CC(=CC(=C2)C3=CC=C(C=C3)O)C4=CC=C(C=C4)O)O",
    "1,3-bis(4-pyridyl)propane N,N'-dioxide": "C1=C[N+](=CC=C1CCCC2=CC=[N+](C=C2)[O-])[O-]",
    "1,3-diiodotetraﬂorobenzene": "C1(=C(C(=C(C(=C1F)I)F)I)F)F",
    "1,3-diĲ4-pyridyl)propane": "C1=CN=CC=C1CCCC2=CC=NC=C2",
    "1,3-tetraﬂuorodiiodobenzene": "C1(=C(C(=C(C(=C1F)I)F)I)F)F",
    "1,3-trimethylenedipiperidine": "C1CCN(CC1)CCCN2CCCCC2",
    "1,4,7,10,13,16-Hexaoxaeyclooetadeeane (18-Crown-6)": "O1CCOCCOCCOCCOCCOCC1",
    "1,4-Diiodotetrafluorbenzene": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,4-Diiotetraﬂuorobenzene": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,4-bis(imidazol) butane": "C1=CN(C=N1)CCCCN2C=CN=C2",
    "1,4-diiodotetraflorobenzene": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,4-diiodotetraﬂorobenzene": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,4-hydroquinone": "Oc1ccc(O)cc1",
    "1,4-tetraﬂuorodiiodobenzene": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "1,5-diaminonaphthalene 9D": "Nc1cccc2c(N)cccc12",
    "1,5-naphtalenedisulfonic acid": "C1=CC2=C(C=CC=C2S(=O)(=O)O)C(=C1)S(=O)(=O)O",
    "1,5-naphtirydyne": "c1cnc2cccnc2c1",
    "1-butylthymine 5": "CCCCn1c(C)cc(=O)[nH]c1=O",
    "1-cyanoadamantane (AdCN)": "N#CC12CC3CC(CC(C3)C1)C2",
    "1-hydroxy-2-napthoic acid": "OC(=O)c1ccc2ccccc2c1O",
    "10b ((1)-methyl phenyl sulfoxide)": "CS(=O)c1ccccc1",
    "18-Krone-6": "O1CCOCCOCCOCCOCCOCC1",
    "1H,4H-3,6-dinitropyrazolo[4,3-c]pyrazole (DNPP)": "C12=C(N=NC1=C(N=N2)[N+](=O)[O-])[N+](=O)[O-]",
    "2,2’-dipyridyl": "n1ccccc1-c2ccccn2",
    "2,3 : 8,9-Bis(ethylendithio)-1,4,7,10-tetrathiafulvalen": "C1CSC2=C(S1)SC(=C3SC4=C(S3)SCCS4)S2",
    "2,3-O-isopropylidene-β-D-ribofuranose": "CC1(O[C@H]2C(O1)[C@H](OC2O)CO)C",
    "2,3-dichloro-5,6-dicyano-l,4-quinone": "ClC=1C(=O)C(\\C#N)=C(\\C#N)C(=O)C=1Cl",
    "2,5-dibromo-TCNQ": "Brc1cc(=C(C#N)C#N)c(Br)cc1=C(C#N)C#N",
    "2,5-dichloro 1,4-hydroquinone": "C1=C(C(=CC(=C1Cl)O)Cl)O",
    "2,5-difluoro-7,7,8,8-tetracyano-p-quinodimethane": "N#CC(C#N)=c1cc(F)c(=C(C#N)C#N)cc1F",
    "2,5-diﬂuoro-7,7,8,8-tetracyanoquinodimethane": "N#CC(C#N)=c1cc(F)c(=C(C#N)C#N)cc1F",
    "2,5DHBA": "O=C(O)c1cc(O)ccc1O",
    "2,6-dimethyl-γ-pyrone": "CC1=CC(=O)C=C(O1)C",
    "2,6-tBu2-4-Me(C6H2OH)": "CC(C)(C)c1cc(C)c(O)cc1C(C)(C)C",
    "2-amino-3-methypyridine": "CC1=C(N=CC=C1)N",
    "2-amino-5-methylopyridine": "CC1=CN=C(C=C1)N",
    "2-carboxypridine": "O=C(O)c1ccccn1",
    "2-naphthanoic acid": "OC(=O)c1ccc2ccccc2c1",
    "2A-acetonaphthone": "CC(=O)C1=CC2=CC=CC=C2C=C1",
    "3,4,5-trifluorobenzoic acid (e)": "O=C(O)c1cc(F)c(F)c(F)c1",
    "3,4,5-trifluorophenol (b)": "Oc1cc(F)c(F)c(F)c1",
    "3,4-dinitropyrazole (3,4-DNP)": "C1=NNC(=C1[N+](=O)[O-])[N+](=O)[O-]",
    "3,5-dinitro-4-methylbenzoic acid 4": "CC1=C(C=C(C=C1[N+](=O)[O-])C(=O)O)[N+](=O)[O-]",
    "3,5-dinitrobenzoic acid 2": "O=[N+]([O-])c1cc(cc([N+]([O-])=O)c1)C(=O)O",
    "3,5-dinitromethyl salicylate": "O=C(OC)c1c(O)c([N+](=O)[O-])cc([N+](=O)[O-])c1",
    "3-(sulfonyl-glycine)benzoic acid": "C1=CC(=CC(=C1)S(=O)(=O)NCC(=O)O)C(=O)O",
    "3-Methylpyridine and 4-Methylpyridine mixture": "Cc1cccnc1.Cc1ccncc1",
    "3-methylpyridine, 2-methylpyridine": "Cc1cccnc1.Cc1ccccn1",
    "3-methylpyridine, 4-methylpyridine": "Cc1cccnc1.Cc1ccncc1",
    "3-picoline and 4-picoline mixture": "Cc1cccnc1.Cc1ccncc1",
    "3MP (3-methylpyridine)": "Cc1cccnc1",
    "3β-hydroxydihydrocostunolide": "C[C@@H]1[C@@H]2CC/C(=C\\C[C@@H](/C(=C\\[C@H]2OC1=O)/C)O)/C",
    "4,4 -azopyridine": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "4,4 -oxybis-benzoic acid": "O=C(O)c1ccc(Oc2ccc(C(=O)O)cc2)cc1",
    "4,4'-bipyridine dehydrate": "c1cnccc1-c2ccncc2",
    "4,4-bipyridine (2)": "c1cnccc1-c2ccncc2",
    "4,4-bispyridylethene": "c1ccncc1/C=C/c2ccncc2",
    "4,40-bipyridyl N,N0-dioxide": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1",
    "4,40-dipyridyl (2)": "c1cnccc1-c2ccncc2",
    "4,40-oxydibenzoic acid": "O=C(O)c1ccc(Oc2ccc(C(=O)O)cc2)cc1",
    "4,49-dipyridyl N,N9-dioxide": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1",
    "4,4’-bipyridylethylene": "c1ccncc1/C=C/c2ccncc2",
    "4,4’-dipyridine": "c1cnccc1-c2ccncc2",
    "4,4’-dipyridyldisulphide": "S(SC1=CC=NC=C1)C1=CC=NC=C1",
    "4,4′-BIP": "c1cnccc1-c2ccncc2",
    "4,4′-Dipyridyl": "c1cnccc1-c2ccncc2",
    "4,4′-bipyridine (BiPy)": "c1cnccc1-c2ccncc2",
    "4,4′-bipyridyl disulﬁde": "S(SC1=CC=NC=C1)C1=CC=NC=C1",
    "4,4′-bipyridylethane": "c1ccncc1CCc2ccncc2",
    "4,4′-bis(dimethylamino)diphenylmethane": "CN(C)c1ccc(cc1)C(c2ccc(N(C)C)cc2)",
    "4,4′-dipyridyl N,N′-dioxide": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1",
    "4,4′-dipyridyl N,N′-dioxide dihydrate": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1.O.O",
    "4,4′-dipyridyl disulﬁde": "S(SC1=CC=NC=C1)C1=CC=NC=C1",
    "4,4′−bipyridylethylene": "c1ccncc1/C=C/c2ccncc2",
    "4,5,7-trinitro-9H-fluoren-9-one-2-carboxylic acid": "O=C(O)c1cc2c(c([N+](=O)[O-])c1)-c1c(cc([N+](=O)[O-])cc1[N+](=O)[O-])C2=O",
    "4,5,7-trinitro-9H-fluoren-9-one-2-carboxylic acid methyl ester": "COC(=O)c1cc2c(c([N+](=O)[O-])c1)-c1c(cc([N+](=O)[O-])cc1[N+](=O)[O-])C2=O",
    "4,6-Dimethydibenzothiophene": "CC1=CC2=C(C=C1)SC3=CC=CC(=C32)C",
    "4,6-di-Br-res": "Oc1cc(O)c(Br)cc1Br",
    "4,6-di-Cl-res": "Oc1cc(O)c(Cl)cc1Cl",
    "4,6-di-I-res": "Oc1cc(O)c(I)cc1I",
    "4,6-di-tert-butyl-3-nitrobenzene-1,2-diol (11)": "",
    "4,6-diCl-res": "Oc1cc(O)c(Cl)cc1Cl",
    "4,6-diiodo-res": "Oc1cc(O)c(I)cc1I",
    "4- Dimethylaminpyridine": "CN(C)c1ccncc1",
    "4-(2-pyridine-4-ethyl)pyridine": "",
    "4-(4-Hydroxybenzyl)phenol (7)": "Oc1ccc(cc1)Cc2ccc(O)cc2",
    "4-(4-Hydroxyphenylsulfanyl)phenol (8)": "Oc1ccc(cc1)Sc2ccc(O)cc2",
    "4-(N,N0-dimethylamino)pyridine": "CN(C)c1ccncc1",
    "4-N,N-dimethylaminobenzoic acid": "CN(C)c1ccc(cc1)C(=O)O",
    "4-aminobenzenosulfonamide": "Nc1ccc(cc1)S(=O)(=O)N",
    "4-bromo-benzo-18-crown-6": "C1COCCOCCOC2=C(C=CC(=C2)Br)OCCOCCO1",
    "4-chloro-7-nitro-2,1,3-benzoxadiazole (2i)": "[O-][N+](=O)c1ccc(Cl)c2nonc12",
    "4-nitro-benzo-18-crown-6": "C1COCCOCCOC2=C(C=CC(=C2)[N+](=O)[O-])OCCOCCO1",
    "4MP (4-methylpyridine)": "Cc1ccncc1",
    "5,5'-dimethyl-2,2'-dipyridine": "CC1=CN=C(C=C1)C2=NC=C(C=C2)C",
    "5,5′-dipyrimidine": "C1=C(C=NC=N1)C2=CN=CN=C2",
    "5-CN-res": "Oc1cc(O)cc(C#N)c1",
    "5-I-res": "Oc1cc(O)cc(I)c1",
    "5-amino-3-nitro-1H-1,2,4-triazole (ANTA)": "N=c1nc([N+](=O)[O-])[nH][nH]1",
    "5-bromorouracil": "O=C1NC=C(Br)C(=O)N1",
    "5-sulfonisophthalic acid": "OC(=O)c1cc(cc(c1)S(=O)(=O)O)C(=O)O",
    "7,7, 8,8-Tetracyano-p-quinodimethane": "C1=CC(=C(C#N)C#N)C=CC1=C(C#N)C#N",
    "8-hydroxyqunoline": "Oc1cccc2ncccc12",
    "Aniline, N,N-dimethylaniline": "CN(C)c1ccccc1",
    "Aniline, N-methylaniline": "CNc1ccccc1",
    "Azopy": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "B18C6": "C1COCCOCCOc2ccccc2OCCOCCO1",
    "BP (4,4’-bipyridine)": "c1cnccc1-c2ccncc2",
    "BPNO": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1",
    "BPzH2": "C1(C2=CNN=C2)=CNN=C1",
    "Bipyridine-N,N’-dioxide BPNO": "[O-][N+]1=CC=C(C2=CC=[N+]([O-])C=C2)C=C1",
    "C6Et6": "CCC1=C(C(=C(C(=C1CC)CC)CC)CC)CC",
    "D-(R)-mandelic acid": "O=C(O)[C@H](O)c1ccccc1",
    "D-aminobutanoic acid": "CC[C@@H](N)C(O)=O",
    "D18C6": "C1COC2=CC=CC=C2OCCOCCOC3=CC=CC=C3OCCO1",
    "DABCO (4)": "C1CN2CCN1CC2",
    "DABCO (6)": "C1CN2CCN1CC2",
    "DITFBs": "C1(=C(C(=C(C(=C1I)F)F)I)F)F",
    "DMTCNQ": "CC1=CC(=C(C#N)C#N)C(C)=CC1=C(C#N)C#N",
    "F2TCNQ": "C1=C(C(=C(C#N)C#N)C=C(C1=C(C#N)C#N)F)F",
    "F4DIB": "C1(=C(C(=C(C(=C1I)F)F)I)F)F",
    "Gentistic acid": "C1=CC(=C(C=C1O)C(=O)O)O",
    "H-TMG": "CN(C)C(=NC)N(C)C",
    "IPFB": "C1(=C(C(=C(C(=C1F)F)I)F)F)F",
    "L(+)a-hydroxy-phenylacetic acid": "O[C@H](C(=O)O)c1ccccc1",
    "L(1)-tartaric acid": "[C@@H]([C@H](C(=O)O)O)(C(=O)O)O",
    "L-Nva": "CCC[C@@H](C(=O)O)N",
    "Leuco Crystal Violet (4,4',4''-methylidynetris(N,N-dimethylaniline))": "CN(C)C1=CC=C(C=C1)C(C2=CC=C(C=C2)N(C)C)C3=CC=C(C=C3)N(C)C",
    "Leucomalachite Green (4,4'-benzylidene(N,N-dimethylaniline))": "CN(C)C1=CC=C(C=C1)C(C2=CC=CC=C2)C3=CC=C(C=C3)N(C)C",
    "Me3NO·2H2O": "C[N+](C)(C)[O-].O.O",
    "Monothioessigsäure": "CC(=O)S",
    "N,N'-Diformohydrazide": "O=CNNC=O",
    "N,N,N0,N0-Tetramethyl-1,6-hexanediamine": "CN(C)CCCCCCN(C)C",
    "N,N,N0,N0-tetramethylethane-1,2-diamine": "CN(C)CCN(C)C",
    "N,N,N0,N0-tetramethylethylenediamine (5)": "CN(C)CCN(C)C",
    "N,N-diethyl-m-toluamide (DEET)": "CCN(CC)C(=O)c1cccc(C)c1",
    "N,N0-bis(pyridin-2-ylmethyl)oxalamide": "O=C(NCC1=NC=CC=C1)C(NCC2=NC=CC=C2)=O",
    "N,N0-bis(pyridin-3-ylmethyl)oxalamide": "O=C(NCc1cccnc1)C(=O)NCc1cccnc1",
    "N,N0-bis(pyridin-4-ylmethyl)oxalamide": "O=C(NCC1=CC=NC=C1)C(NCC2=CC=NC=C2)=O",
    "N,N0-dimethylpiperazine": "CN1CCN(CC1)C",
    "N,N0-thiocarbonyldiacetamide": "CC(=O)NC(=S)NC(=O)C",
    "N,Nº-Bis(pyridin-4-ylmethyl)oxalamide": "O=C(NCC1=CC=NC=C1)C(NCC2=CC=NC=C2)=O",
    "PYR (pyridine)": "n1ccccc1",
    "Perchlorsäure (15% wässriger)": "O[Cl](=O)(=O)=O",
    "Ph2Si(OH)2": "O[Si](O)(c1ccccc1)c2ccccc2",
    "Pyromellitsauredianhydrid": "C1=C2C(=CC3=C1C(=O)OC3=O)C(=O)OC2=O",
    "Q(CN)2": "C1=CC(=O)C(=C(C1=O)C#N)C#N",
    "QBr2(OH)2": "C1(=C(C(=O)C(=C(C1=O)Br)O)Br)O",
    "QBr4": "C1(=C(C(=O)C(=C(C1=O)Br)Br)Br)Br",
    "QCl2(OH)2": "OC1=C(Cl)C(=O)C(=C(Cl)C1=O)O",
    "QCl4": "O=C1C(Cl)=C(Cl)C(=O)C(Cl)=C1Cl",
    "R-(+)-1-phenylethanol": "C[C@@H](O)c1ccccc1",
    "R-(þ)-methyl p-tolyl sulfoxide": "CC1=CC=C(C=C1)[S@](=O)C",
    "S-2CLMA": "O[C@H](C(O)=O)c1ccccc1Cl",
    "S-3-Phenylbutyric acid": "C[C@@H](CC(O)=O)c1ccccc1",
    "S-Mandelic Acid": "O[C@H](C(O)=O)c1ccccc1",
    "S-endo-3-bromocamphor": "CC1(C)[C@H]2CC[C@]1(C)C(=O)[C@@H]2Br",
    "S-serine": "C([C@@H](C(=O)O)N)O",
    "Schwefelsäure (konzentrierte)": "OS(=O)(=O)O",
    "TBA·Br": "CCCC[N+](CCCC)(CCCC)CCCC.[Br-]",
    "TBA·HSO4": "CCCC[N+](CCCC)(CCCC)CCCC.O=S(=O)(O)[O-]",
    "TBA·I": "CCCC[N+](CCCC)(CCCC)CCCC.[I-]",
    "TBA·NO3": "CCCC[N+](CCCC)(CCCC)CCCC.[O-][N+](=O)O",
    "Tetraeyanoethylene": "C(#N)C(=C(C#N)C#N)C#N",
    "[12]-crown-4": "O1CCOCCOCCOCC1",
    "[D4]urea": "[2H]N([2H])C(=O)N([2H])[2H]",
    "acetylated glutamic acid": "CC(=O)N[C@@H](CCC(=O)O)C(=O)O",
    "acetylcysteine (ACC) (6)": "CC(=O)N[C@@H](CS)C(=O)O",
    "anhydrous piperazine": "C1CNCCN1",
    "caprolacatam": "O=C1NCCCCC1",
    "chloranillic acid": "O=C1C(=O)C(Cl)=C(O)C(Cl)=C1O",
    "cis, cis-cyclohexane-1,3,5-tricarboxylic acid": "O=C([C@H]1C[C@@H](C(O)=O)C[C@@H](C(O)=O)C1)O",
    "cis-DCE": "Cl/C=C\\Cl",
    "d,l-mandelic acid": "O=C(O)C(O)c1ccccc1",
    "d- -aminobutyric acid": "CC[C@@H](N)C(O)=O",
    "deuterated urea": "[2H]N([2H])C(=O)N([2H])[2H]",
    "dibenzoyl-D D-tartaric acid": "OC(=O)[C@@H](OC(=O)C1=CC=CC=C1)[C@H](OC(=O)C1=CC=CC=C1)C(O)=O",
    "dibenzoyl-LL-tartaric acid": "OC(=O)[C@H](OC(=O)C1=CC=CC=C1)[C@@H](OC(=O)C1=CC=CC=C1)C(O)=O",
    "dimethyl 4-nitrophenylphosphate": "COP(=O)(OC)Oc1ccc([N+](=O)[O-])cc1",
    "dimethyl methylphosphate": "COP(=O)(OC)OC",
    "ethylene-di(4-oxybenzoic acid)": "C1=CC(=CC=C1C(=O)O)OCCOC2=CC=C(C=C2)C(=O)O",
    "fluoranilic acid": "O=C1C(O)=C(F)C(=O)C(O)=C1F",
    "fluorinated 7,7,8,8-tetracyanoquinodimethane": "C(#N)C(=C1C(=C(C(=C(C#N)C#N)C(=C1F)F)F)F)C#N",
    "fluoroanilic acid": "O=C1C(O)=C(F)C(=O)C(O)=C1F",
    "hexamethyltetramine": "C1N2CN3CN1CN(C2)C3",
    "impure 4,4′-azopyridine": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "iodanilic acid": "OC1=C(I)C(=O)C(=C(I)C1=O)O",
    "iodopentaflourobenzene": "C1(=C(C(=C(C(=C1F)F)I)F)F)F",
    "krypto®x 2.2. (4)": "C1COCCOCCNCCOCCOCCN1",
    "krypto®x 2.2.2. (7)": "N12CCOCCOCCN(CCOCCOCC2)CCOCCOCC1",
    "m-DITFB": "C1(=C(C(=C(C(=C1F)I)F)I)F)F",
    "malonic acid 6": "O=C(O)CC(=O)O",
    "monoiodoperfluorobenzene": "C1(=C(C(=C(C(=C1F)F)I)F)F)F",
    "monophosphoric acid": "OP(=O)(O)O",
    "n-Valerophenone": "CCCC(=O)c1ccccc1",
    "o-DITFB": "Fc1c(F)c(F)c(I)c(I)c1F",
    "p-CF3-benzoic acid": "O=C(O)C1=CC=C(C=C1)C(F)(F)F",
    "p-DITFB": "FC1=C(F)C(I)=C(F)C(F)=C1I",
    "p-dicyanobenzene (DCNB, 21)": "N#Cc1ccc(cc1)C#N",
    "p-toluenesulfonic acid 1-hydrate (h)": "Cc1ccc(cc1)S(=O)(=O)O.O",
    "p-tolunitrile (p-MeC6H4CN)": "Cc1ccc(cc1)C#N",
    "pDNB": "O=[N+]([O-])c1ccc([N+](=O)[O-])cc1",
    "pentafluorobenzoic acid (g)": "O=C(O)c1c(F)c(F)c(F)c(F)c1F",
    "pentafluorophenol (c)": "C1(=C(C(=C(C(=C1F)F)F)F)F)O)",
    "phathalic acid": "O=C(O)c1ccccc1C(=O)O",
    "phenol (a)": "Oc1ccccc1",
    "phenzine": "N=1C2=CC=CC=C2N=C3C=CC=CC13",
    "phlouroglucinol": "Oc1cc(O)cc(O)c1",
    "phluoroglucinol": "Oc1cc(O)cc(O)c1",
    "pyNO": "[O-][n+]1ccccc1",
    "pyrazine mono N-oxide": "[O-][n+]1ccncc1",
    "pyrene 2": "C=1C=C2C=CC3=CC=CC=4C=CC(C1)=C2C34",
    "racemic ethyl phenyl sulfoxide": "CCS(=O)C1=CC=CC=C1",
    "salicylic acid (f)": "O=C(O)c1ccccc1O",
    "silver(1) nitrate": "O=[N+]([O-])=O.[Ag+]",
    "sym-C6F3I3": "FC1=C(I)C(F)=C(I)C(F)=C1I",
    "sym–triiodo–trifluorobenzene": "FC1=C(I)C(F)=C(I)C(F)=C1I",
    "t6tracyanoquinodim6thane": "c1cc(=C(C#N)C#N)ccc1=C(C#N)C#N",
    "tetracyano-para-quinodimethane": "c1cc(=C(C#N)C#N)ccc1=C(C#N)C#N",
    "tetracyanochinodimethane (TCNQ, 24)": "c1cc(=C(C#N)C#N)ccc1=C(C#N)C#N",
    "tetraphenylphosphium iodide": "C1=CC=C(C=C1)[P+](C2=CC=CC=C2)(C3=CC=CC=C3)C4=CC=CC=C4.[I-]",
    "thiobarbutaric acid": "C1C(=O)NC(=S)NC1=O",
    "trans-1,2-bis(4'-pyridyl)ethane": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "trans-1,2-bis(4-pyridyl)ethane": "C1=CN=CC=C1CCC2=CC=NC=C2",
    "trans-1,2-bis-(4-pyridyl)acetylene": "C1=CN=CC=C1C#CC2=CC=NC=C2",
    "trans-1,2-bisĲ4-pyridyl)ethylene": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "trans-1,2-di(4-pyridyl)-ethylene (DPE)": "C1=CN=CC=C1/C=C/C2=CC=NC=C2",
    "trans-1,4-dithiane-1,4-dioxide": "C1CS(=O)CCS1=O",
    "trans-4,4'-azopyridine": "C1=CN=CC=C1N=NC2=CC=NC=C2",
    "tri(2-amintheyl)amine": "C(CN(CCN)CCN)N",
    "trichloracetonitrile": "N#CC(Cl)(Cl)Cl",
    "tris(N,N-dimethyl)trimesamide": "O=C(C1=CC(C(N(C)C)=O)=CC(C(N(C)C)=O)=C1)N(C)C",
    "tétracyano-7,7,8,8 p-quinodiméthane": "c1cc(=C(C#N)C#N)ccc1=C(C#N)C#N",
    "zinc acetate (II)": "CC(=O)[O-].CC(=O)[O-].[Zn+2]",
    "α,α,α′,α′-tetraphenyl-1,3-dioxolane-4,5-dimethanols (6a)": "CC1(O[C@@H]([C@@H](O)C(c2ccccc2)c2ccccc2)O[C@@H]([C@@H]1O)C(c1ccccc1)c1ccccc1)C",
}
